fedora-toolbox
Rootless podman shuld mount a tmpfs at /dev/shm by default. Until that
happens, it's worked around by explicitly specifying the mount point.
Also, the --shm-size flag isn't working with rootless podman [1], so
--tmpfs is used instead.
It tries to mimic the in-kernel tmpfs default [2] of using half the
amount of total RAM. If for some reason /proc/meminfo can't be parsed,
it falls back to using podman's default of 65536k for tmpfs. It's not
clear whether podman uses kibibytes or kilobytes for 'k'. The former
was picked here for consistency.
[1] https://github.com/containers/libpod/issues/1770
[2] https://www.kernel.org/doc/Documentation/filesystems/tmpfs.txt
https://github.com/debarshiray/fedora-toolbox/issues/9
=> Make shm_open work

fedora-toolbox
Currently, the non-root interactive shells were being spawned with a
full set of capabilities. This led to unexpected root-like behaviour
for non-root users. All capability sets, except the Permitted (or
CapBnd) set, should be cleared to match the usual state of a host
interactive shell for non-root users.
It doesn't look like podman offers a way to forward CapBnd from the
host without touching the other sets. If '--privileged' is used with
'podman create', then it forwards CapBnd but also initializes the
others to have a full set of capabilities. If it's not used, then it
doesn't touch anything other than CapBnd, but only forwards a subset
of the host's CapBnd, which means that using sudo to attain elevated
privileges inside the toolbox won't give the full set of capabilities
as on the …
=> Avoid spooky root-like behaviour for non-root interactive shells

fedora-toolbox
Silverblue, and rpm-ostree more generally are moving to
HOME=/var/home/$USER and make the /home symlink just a compatibility
feature. See:
https://github.com/projectatomic/rpm-ostree/pull/1726
Matching what the host does will reduce weird side-effects, so
propagate $HOME into the container, and if the host has /home as
a symlink to /var/home, do the same for the toolbox.
=> Set up $HOME and /home to match the host

README.md
- OSTree systems aren't fully immutable, you *can* install things
we just discourage it
- fedora-toolbox can (and should!) be used on non-ostree based
systems as well
=> README.md: Rework in various ways

fedora-toolbox
Add the list command providing the possibility to list all images and containers created by fedora-toolbox (i.e those that have the "com.redhat.component=fedora-toolbox" label). Two flags can be used: --images and --containers, to list only images or containers. If none of these flags is used, the command lists both. Additionally, containers that are currently running are highlighted by green color.
=> Add list command

fedora-toolbox
Using "$0" leads to printing the entire path to the fedora-toolbox
script, which adds visual noise to the output. Command line tools like
GNU Coreutils and Git remove any leading directory components from
the path, which seems like a reasonable trade-off between aesthetics
and verbosity.
=> Shorten the prefix for debug and error messages

toolbox
Otherwise, it breaks 'podman start ...' in Podman commit
52df1fa7e054d577 [1]. Even though the podman regression was fixed in
commit 21bc766ee3829776 [2], it's prudent to also fix the toolbox
script to be more correct.
This problem isn't localized to a single command, but spans across
'create' and 'enter'. If a customized toolbox image created by the
'create' command has volumes for host bind mounts, then it will break
'podman start ...' in the 'enter' command. Therefore, users need to be
encouraged to recreate both their customized toolbox images. This is
currently done through the --verbose debug logs to avoid needless
noise because the regression was restricted to development snapshots
of podman.
Toolbox containers created from images built by broken Podman versions
between commits …
=> Don't create volumes in the image for bind mounts from the host

doc/meson.build, doc/toolbox-create.1.md, doc/toolbox-enter.1.md, doc/toolbox-list.1.md, doc/toolbox.1.md, meson.build
It's customary for command-line tools to have manuals in the form of `man` pages.
=> Add manuals

doc/meson.build, doc/toolbox-rm.1.md, doc/toolbox-rmi.1.md, doc/toolbox.1.md, toolbox
Add rm and rmi commands for images/containers removal. Both commands take ID or name as an argument and if the specified image/container was created by fedora-toolbox, it's removed. 
Both commands have two flags: --all and --force. With the --all flag, the argument is not needed, as the command tries to remove all fedora-toolbox images/containers. The --force flag just runs force removal (i.e podman rm/rmi --force <ID>)
=> Add rm and rmi commands

toolbox
The current implementation of the --image flag, including the commit
message in commit 31de3ff96fe4eea2 that added it, was a total fiasco
and didn't match the intended behaviour or the documentation in the
manual at all. At the moment it overrides the name of the user-specific
customized image. This doesn't make sense because it's mostly an
implementation detail of the toolbox script - a way to get from the
base image to a toolbox container that's seamlessly integrated with the
host.
In other words, there's no need for a separate flag to allow having
multiple user-specific customized images from the same base image. It
already happens as a side effect of creating multiple toolbox
containers from the same base image using the --container flag.
What it really should do is override the base …
=> Make the --image flag override the base toolbox image, as documented

toolbox
This enables things like:
$ colormgr get-sensor-reading lcd
=> Give access to /dev/bus for control transfers from USB devices

images/fedora/f28/extra-packages, images/fedora/f29/extra-packages, images/fedora/f30/extra-packages, images/fedora/f31/extra-packages, toolbox
There's no easy way to introspect the Kerberos configuration from the
command line. eg., the credential cache type being used, or the value
of the socket_path setting that denotes which socket the KCM service
will listen on. Therefore, it's assumed that the former is KCM if the
socket's path can be parsed from the sssd-kcm.socket unit.
Given the immutable nature of Podman containers, the toolbox container
and its corresponding image will have to be re-created if the host OS
is sufficiently re-configured.
The krb5-libs package was added to the base toolbox images to ensure
the presence of the /etc/krb5.conf.d directory with the correct
permissions. Currently, the package is already pulled in by various
dependencies. Therefore, it doesn't increase the size of the base
image, but serves as a …
=> Give access to Kerberos if KCM credential caches are being used

toolbox
I tried to remove all bashisms, and now checkbashisms does not complain anymore:
- POSIX only supports single digit file descriptors. I used 3 instead of 42 as the file descriptor for /dev/null.
- echo -e replaces certain backslash expressions. Since, there were none of them, I just removed the -e flag. The `${variable}` syntax should still work.
- POSIX does not set the $UID environment variable. I replaced it with the custom variable $uid.
- The $'' syntax for backslash expressions does not exists in POSIX.  Since it was only used for the tab character, I just replaced it with the custom $tab variable at the beginning of the script.
In my (limited) testing, create, enter and list still works, using both bash and dash as interpreter. The --verbose option also still works, although I …
=> Remove all bashisms (resolves #53)

toolbox
Line 21:
arguments="$@"
^-- SC2124: Assigning an array to a string! Assign as
array, or use * instead of @ to concatenate.
See: https://github.com/koalaman/shellcheck/wiki/SC2124
POSIX doesn't support arrays other than the one for positional
parameters (ie. "$@"); and "$@" is generally recommended for
forwarding the positional parameters, not $@ or "$*" or $* [1,2].
Therefore, the original contents of "$@" are saved in a scalar variable
after quoting them in a way that's resilient against spaces and
wildcards in the elements, and are later restored using 'set -- ...'
based on Rich's sh (POSIX shell) tricks:
http://www.etalabs.net/sh_tricks.html
Since the forward_to_host to function isn't passed any positional
parameters but still …
=> Fix the saving and restoring of the array of positional parameters

toolbox
Line 286:
while read variable; do
^-- SC2162: read without -r will mangle backslashes.
See: https://github.com/koalaman/shellcheck/wiki/SC2162
Note that currently none of these cases were handling backslashes in
the input, but it's better to stick to standard practice than silencing
the warning.
https://github.com/debarshiray/toolbox/pull/83
=> Prevent read from mangling backslashes

toolbox
Line 288:
echo "$base_toolbox_command: $variable=$value" >&3
^-- SC2154: value is
referenced but not assigned.
See: https://github.com/koalaman/shellcheck/wiki/SC2154
https://github.com/debarshiray/toolbox/pull/83
=> Initialize the variable before assigning to it with eval

toolbox
Line 754:
capsh --caps="" -- -c 'cd "$1"; export PS1="$2"; shift 2; exec "$@"'
^-- SC2016: Expressions don't expand in single
quotes, use double quotes for that.
See: https://github.com/koalaman/shellcheck/wiki/SC2016
The entire command string argument is meant to be passed as is,
without any variable expansion, to the shell started by capsh(1) inside
the toolbox container.
https://github.com/debarshiray/toolbox/pull/83
=> Silence SC2016

toolbox
Now that toolbox containers no longer use a separate PID namespace [1],
the entry point specified in 'podman create ...' doesn't act as PID 1
inside the toolbox container. It's just a process that's spawned by
'podman start' to denote the state of the container. This opens the
possibility of using something even more lightweight, such as
'sleep +Inf'.
sleep(1) takes 64 kB compared to the 432 kB taken by /bin/sh.
This wouldn't have been possible with a separate PID namespace. In that
case, the entry point would also become PID 1, and since the only
signals that can be sent to a PID 1 are those for which it has
explicitly installed handlers, this would cause various problems.
[1] Commit 67522f0ad7637768
=> Use a lighter entry point than /bin/sh

toolbox
First we need to get the containers with an old label and then with the
new label. We have to change the format of the query to only include the
name of the containers and not the other informations like 'created' as
they could make a problem when removing the duplicates with uniq. When
we have the final list of containers we pass them to
containers_get_details() where we obtain the final details for them.
https://github.com/debarshiray/toolbox/pull/101
=> Include containers tagged with c.gh.debarshiray.toolbox in 'list'

toolbox
When '--all' is applied then first query the containers with an old label,
then with the new label, combine them and process them.
When the exact container name is specified, then we need to check
whether the container has the new or old label and only then remove it.
https://github.com/debarshiray/toolbox/pull/101
=> Include containers tagged with c.gh.debarshiray.toolbox in 'rm'

toolbox
Unlike OCI images, OCI containers can't be tagged and their names [can't have colons](https://github.com/containers/libpod/pull/2793) in them. Therefore, from now on the version suffix will be separated by a hyphen.
https://github.com/debarshiray/toolbox/issues/106
=> Ensure that names of toolbox containers don't have a colon

doc/toolbox-create.1.md, doc/toolbox-enter.1.md, toolbox
having short options for enter and create would be nice as i'm calling these quite often. i didn't add a short option for `create --candidate-registry`, `-r` is already taken and i'm currently not using `--candidate-registry`.
thanks
toni
=> added short options for create and enter

toolbox
Commit 5b3d234c9e9ef45f had made the toolbox script work inside a
toolbox container, but most people didn't get to use it because it
needed extra effort to get access to the script inside the container.
One either had to grab the Toolbox sources or had to install the RPM.
Both options were inconvenient - the former needed knowing too many
technical details, while the latter would drag in dependencies like
Buildah and Podman that don't work inside the toolbox container.
This makes it easier to use the toolbox script inside a toolbox
container by bind mounting the script from the host inside the
container and keeping track of the path using the TOOLBOX_PATH
environment variable. The environment variable ensures that running
'toolbox create' from inside a toolbox container would continue to …
=> Make it available inside the toolbox container

profile.d/toolbox.sh
The welcome text uses the OSC 8 [1] escape sequence to add a hyperlink
to the Silverblue documentation [2].
Silence a SC1003 [3] because the intention is to print the 'ESC \'
string terminator (or ST), and not escape a single quote.
[1] https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda
[2] https://docs.fedoraproject.org/en-US/fedora-silverblue/toolbox/
[3] https://github.com/koalaman/shellcheck/wiki/SC1003
=> Show a welcome text on interactive shells running inside a toolbox

completion/bash/toolbox, meson.build
Make using toolbox a bit more convenient by properly completing its
options. The completions should be complete (that is, there are
completions for all the commands and options shown in --help),
but no attempt is made to filter out conflicting options (for
example "toolbox rm --all my-container").
=> completion: Add bash completion

completion/bash/toolbox, doc/toolbox.1.md, toolbox
Currently, there's no easy way to get the size of the impending
download. Skopeo doesn't offer the size of the OCI image [1] and it's
debatable whether another 23 MB binary ought to be pulled in as a
dependency just for this.
Given that the default fedora-toolbox images are the only base images
available via a public repository, the size of the download is hard
coded to reflect the approximate size of the fedora-toolbox images.
These images are between 451 MB and 483 MB, so 500 MB should be a
reasonably suggestive approximate that shouldn't negatively surprise
users.
[1] https://github.com/containers/skopeo/issues/641
https://github.com/debarshiray/toolbox/issues/134
=> Ask for confirmation before downloading the base image

toolbox
When there aren't any toolbox containers, 'toolbox enter' will offer to
create a new container, and if there's only one it will fallback to it.
https://github.com/debarshiray/toolbox/issues/128
=> Make 'toolbox enter' create or fallback to a container when possible

profile.d/toolbox.sh, toolbox
This is a lot more clear and explicit than TOOLBOX_PATH, which is more
of an implementation detail to bind mount the toolbox script inside the
toolbox container.
=> Set TOOLBOX_CONTAINER in the environment to identify as a toolbox

toolbox
https://github.com/debarshiray/toolbox/issues/129
=> Keep /etc/hosts and /etc/resolv.conf synchronized with the host

profile.d/toolbox.sh, toolbox
The shell start-up scripts are where the PS1 is meant to be set. So
far, the absence of a toolbox-specific start-up script was being worked
around by setting the PS1 as part of the 'podman exec' invocation. This
came with certain limitations. eg., using su(1) or sudo(8) to get a
root shell can overwrite the PS1 set during 'podman exec' with a value
set by the operating system's existing start-up scripts depending on
which environment variables were being retained.
Now that the toolbox has it's own /etc/profile.d/toolbox.sh start-up
script, it's time to move the PS1 to its rightful home.
Since the start-up script and /run/.toolboxenv are present in older
toolbox containers, this change should be fully backwards compatible
and lead to a more robust PS1 without breaking older containers.
=> Retain the PS1 across su(1) and sudo(8)

completion/bash/toolbox, doc/meson.build, doc/toolbox-run.1.md, toolbox
This makes 'toolbox enter' similar to 'toolbox run $SHELL'.
The 'run' command is meant to spawn arbitrary binaries present inside
the toolbox container. Therefore it doesn't make sense for it to fall
back to /bin/bash, like it does for 'enter' if $SHELL is absent.
It's expected that users might use 'run' to create ad-hoc *.desktop
files. That's why it neither offers to create nor falls back to an
existing container like 'enter' does, because such interactions can't
happen when used in a *.desktop file. It's also a more advanced command
that new users are less likely to be interested in. Hence, this
shouldn't affect usability.
Some changes by Debarshi Ray.
https://github.com/debarshiray/toolbox/pull/76
=> Add a run command

toolbox
Currently, the toolbox script depends on both the buildah and podman
commands. However, both are Go programs, and like all Go programs the
absense of shared libraries leads to bigger binaries. eg., the buildah
and podman binaries are approximately 22 MB and 48 MB respectively,
whereas the flatpak binary is a mere 1.4 MB.
Due to this, there's some nascent desire from the Endless OS folks to
reduce the dependency footprint of the toolbox script by replacing
Buildah with the corresponding Podman commands. This is a step in that
direction.
=> Reduce reliance on Buildah by switching to 'podman create --user ...'

toolbox
Currently, the toolbox script depends on both the buildah and podman
commands. However, both are Go programs, and like all Go programs the
absense of shared libraries leads to bigger binaries. eg., the buildah
and podman binaries are approximately 22 MB and 48 MB respectively,
whereas the flatpak binary is a mere 1.4 MB.
Due to this, there's some nascent desire from the Endless OS folks to
reduce the dependency footprint of the toolbox script by replacing
Buildah with the corresponding Podman commands. This is a step in that
direction.
=> Reduce reliance on Buildah by switching to 'podman create --workdir'

toolbox
KCM is the only type of Kerberos credential cache that can seamlessly
work across the host and the toolbox container. In case the host isn't
using KCM, then Kerberos will error out inside the toolbox container,
which is fine.
=> Set the Kerberos credential cache type in the container unconditionally

toolbox
Missing dashes prevented execution of commands in `buildah unshare` session, which led to the fact that `/run/host/etc/resolv.conf` and `/run/host/etc/hosts` were not correctly linked into the toolbox, leaving the container without network connectivity.
=> Fix issue 152

README.md, completion/bash/toolbox, doc/meson.build, doc/toolbox-init-container.1.md, doc/toolbox.1.md, toolbox
Currently, the toolbox script depends on both the buildah and podman commands. However, both are Go programs, and like all Go programs the absense of shared libraries leads to bigger binaries. eg., the buildah and podman binaries are approximately 22 MB and 48 MB respectively, whereas the flatpak binary is a mere 1.4 MB.
Due to this, there's some nascent desire from the Endless OS folks to reduce the dependency footprint of the toolbox script by dropping the Buildah dependency.
Tied to this is the use of the user-specific customized image. If nothing else, the purpose of this second image is hard to explain to users in Toolbox documentation. 
Secondly, since the configuration happens during the `toolbox create` command, backwards compatibility becomes difficult. Since these are pet …
=> Drop the Buildah dependency and the need for the user-specific customized image

toolbox
The prefixed spinner messages look odd because neither the download
confirmation prompts nor the hints on how to enter a container have
them. It's better to only prefix the debug and error messages so as to
disambiguate their origins.
=> Drop the prefix from spinner messages

toolbox
This was triggered by changes to rootless Podman containers in
podman-1.3.0 [1]. Containers created with version 1.2.0 or older need
to be migrated.
[1] https://github.com/containers/libpod/issues/2935
=> Migrate existing containers when Podman is updated

toolbox
The unary logical negation operator (ie. !) was getting associated with
the 'cd /etc' instead of the entire sequence. As a result, neither
/etc/hosts nor /etc/resolv.conf were getting symlinked.
Fallout from 8b84b5e4604921fad818ede5267591de7f0993e6
=> Unbreak the initialization of /etc/hosts and /etc/resolv.conf

toolbox
Fedora ships with 'column' cmd from util-linux which supports more
options than the one shipped by Debian (from bsdmainutils).
This change updates toolbox to also compatible with column from
bsdmainutils.
=> Fix to work with column cmd from bsdmainutils

toolbox
This reverts commit fdc00a2778afab061bf165429c4a3f3497dd091d.
https://github.com/debarshiray/toolbox/issues/163
=> Allow Qt applications to work without QT_X11_NO_MITSHM

toolbox
This needs https://github.com/flatpak/flatpak/pull/2916 to sort out some corner cases with file permissions, but should already work for the vast majority of cases when used as `$USER` or `root` inside the toolbox container.
https://github.com/debarshiray/toolbox/issues/70
=> Keep /etc/host.conf, /etc/localtime and /etc/timezone synchronized with the host

toolbox
This is useful for accessing devices such as ttyUSB* which wouldn't
previously appear in the /dev tree when in a toolbox container.
This is a simple solution to #97, passing the entirety of `/dev` into the container, rather than mounting specific portions of it. There may be some security concerns to address when using this particular approach, especially as the container is being run with the `privileged` flag.
EDIT: It should be noted that while the /dev tree is passed into the container, `/dev` belongs to `nobody:nobody` and as such files are unaccessible without changing permissions on the host.
=> Change volume mounts to include all of /dev.

toolbox
Rootless containers cannot be paused while data is copied into them.
The '--pause' flag used to default to 'true', but it would be silently
ignored until recently [1,2] when it got turned into an error in
podman-1.4.0. Therefore, it has to be explicitly toggled using
'--pause=false'. Otherwise, it would lead to:
toolbox: copying /etc/profile.d/toolbox.sh to container fubar
Error: cannot copy into running rootless container with pause set -
pass --pause=false to force copying
toolbox: unable to copy /etc/profile.d/toolbox.sh to container fubar
The '--pause' flag was latter changed to default to 'false' [3], but
it's good to be defensive and have this addressed from both sides.
Note that 'podman cp --pause false ...' doesn't work. It's necessary to
use the '=' because it gets confused …
=> Prevent Podman from complaining about 'podman cp --pause=true ...'

toolbox
The '--pause' flag for 'podman cp' was only introduced in
podman-1.4.0 [1]. Having it work with older Podman versions is useful
when bisecting regressions.
Fallout from e715ff2f9b2312714e5241ca1f17a126093e64f0
[1] Podman commit 49dc18552a13ee76
https://github.com/containers/libpod/commit/49dc18552a13ee76
=> Unbreak 'podman cp ...' to work with podman-1.3.1

profile.d/toolbox.sh
Enclose non-printable sequences in the `PS1` with `\[\]` so its length gets calculated properly. Fixes #190.
=> Fix PS1 line wrapping

completion/bash/toolbox, doc/toolbox-init-container.1.md, toolbox
Check in create() if /home on the host redirects to /var/home,
and modify the container accordingly in init-container(). This
restores the logic introduced in commit 66e982a which was
accidentally undone by commit 8b845e.
Closes #185
=> Fix check for whether host's /home is a symlink.

toolbox
The OSC 777 escape sequence is taken from Enlightenment's Terminology:
https://phab.enlightenment.org/T1765
It's a VTE-specific extension until a standard escape sequence is
agreed upon across multiple different terminal emulators [1].
[1] https://gitlab.freedesktop.org/terminal-wg/specifications/issues/17
=> Notify the terminal about the current toolbox container in use

toolbox
```
Copying files into a running container is considered inherently hacky.
Rootful Podman can pause a container using 'podman cp --pause ...'
during the copy, but that's not possible when used rootless.
Secondly 'podman cp' has suffered from a series of regressions lately.
First there was the problem with how the --pause flag was handled [1],
and then /etc/profile.d/toolbox.sh was getting created as a
directory [2], not regular file, by:
$ podman cp \
--pause=false \
/etc/profile.d/toolbox.sh \
"$container":/etc/profile.d
Try to side-step all that by using $XDG_RUNTIME_DIR as a conduit to
share the file with the container and using plain cp(1) to place it in
the toolbox container's /etc/profile.d.
[1] Commit e715ff2f9b231271
https://github.com/debarshiray/toolbox/pull/193
[2] …
```
=> Don't use 'podman cp' to copy toolbox.sh to old containers

toolbox
Creating /run/.toolboxenv in run(), outside the entry point, has the
advantage of automatically working with older toolbox containers.
However, at some point those containers are going to get end-of-lifed.
Then it would be nice to have this bit of initialization tucked away
inside the entry point.
=> Create /run/.toolboxenv inside the toolbox container's entry point too

toolbox
Toolbox containers created prior to commit 8db414ddc2d73719 didn't have
/run/host/monitor inside them. Therefore, for those containers
/etc/localtime and /etc/timezone were getting redirected to locations
that didn't exist.
=> Unbreak /etc/localtime & /etc/timezone if /run/host/monitor is absent

profile.d/toolbox.sh
The Silverblue welcome message was being displayed incorrectly on
other ostree based OS's (Fedora Atomic Host, Fedora CoreOS).
Silverblue is the only one that runs a desktop so the gdm check
was used to distinguish between the other Fedora variants.
=> profile.d: make silverblue check more specific

completion/bash/toolbox, doc/meson.build, doc/toolbox-help.1.md, doc/toolbox.1.md, toolbox
Hi, I recently started to experiment with Fedora Silverblue and naturally with toolbox and during it's usage I found the help screen to be a bit confusing and too verbose. So I took inspiration from other projects and reorganized it a little bit.
Current help screen:
Help screen with update:
=> Update toolbox help screen

toolbox
This lets podman do the calculations for mapping the host UID into the
user namespace within the container. See cfcf4eb31e14b3a3 for original
context.
The '--userns=keep-id' option was introduced in Podman 1.4.0, which is
old enough to be in even RHEL 7.
https://github.com/debarshiray/toolbox/issues/244
=> Simplify code by taking advantage of 'podman create --userns=keep-id'

toolbox
The '--workdir ...' option was added to 'podman exec' in Podman 1.0.0,
which is within the current minimum required Podman version of 1.4.0.
=> Simplify code by taking advantage of 'podman exec --workdir ...'

toolbox
to keep same terminal window size on host.
Both COLUMNS and LINES isn't actually environment variables.
So the existing create_environment_options() can't be used for this purpose.
This fixes https://github.com/debarshiray/toolbox/issues/242
=> Inherit COLUMNS and LINES at host

toolbox
This is helpful when running a development build of GNOME Shell from
within a toolbox container. It enables populating the application grid
with Flatpak applications installed system-wide on the host.
=> Give access to the system Flatpak directory

toolbox
This is useful when the session libvirt instance doesn't offer all the
bells and whistles needed for running virtual machines.
=> Give access to the system libvirt instance

toolbox
When listing only images, 'exit' was picking up the non-zero exit code
from the following (failing) statement meant for containers. An
explicit 'if' branch prevents the exit code of the condition from
leaking out.
Fallout from 5e4e63a11b21de97be65c4c7ec4a62c943084287
=> Don't exit with a non-zero code from 'toolbox list -i'

toolbox
When running nested, stty(1) is invoked against the inner
pseudo-terminal pair created by 'podman exec --tty' which may not have
a valid size due to: https://github.com/containers/libpod/issues/3946
In such cases, the COLUMNS and LINES variables set by toolbox(1) in the
outer environment should be forwarded.
This should have been part of commit 05544fb2714ec096.
https://github.com/debarshiray/toolbox/issues/242
=> Try to unbreak the terminal size when working nested

toolbox
No /run/media is available on Chromebook so it should be optional to get this work on Chromebook.
=> Check if /run/media is available

toolbox
Adjust the grep match pattern to be more specific.
Here is an example that shows the difference:
$ export USER=foo
$ echo -e "foo:100000:65536\nfoobar:165536:65536" 
foo:100000:65536
foobar:165536:65536
$ echo -e "foo:100000:65536\nfoobar:165536:65536" | grep "$USER"
foo:100000:65536
foobar:165536:65536 
$ echo -e "foo:100000:65536\nfoobar:165536:65536" | grep "^$USER:"
foo:100000:65536
$
Signed-off-by: Erik Sjölund <erik.sjolund@gmail.com>
=> Adjust the grep match pattern to be more specific

toolbox
This is meant to alleviate some of the pain of not being able to modify
the list of bind mounts once a toolbox container has been created. For
some cases, where read-only access is enough, one can get by with
setting up symbolic links inside the toolbox container.
Based on an idea from Colin Walters.
=> Expose a few more host locations inside the container under /run/host

toolbox
The '--dns=none --no-hosts' options were added to 'podman create' in
Podman 1.2.0, which is within the current minimum required Podman
version of 1.4.0.
=> Simplify code by dropping compatibility with 'podman create' < 1.4.0

toolbox
On systemd-based systems /etc/os-release is a symbolic link to
/usr/lib/os-release. So this avoids one extra lookup.
=> Switch to using /usr/lib/os-release instead of /etc/os-release

toolbox
In practice, the OSC 777 escape sequence is only supported in Fedora's
fork of VTE. It's completely useless on other distributions.
Moreover, the user experience of tracking and preserving the user's
current toolbox container in GNOME Terminal was designed specifically
for Fedora Silverblue and Workstation, and it still has some rough
edges. eg., not being able to request a shell running on the host from
inside the toolbox, which can make the user feel trapped. While those
kinks get worked out, it's better to not expose users of other Fedora
variants, like CoreOS, to this.
=> Let the terminal know the active container only on some Fedora variants

toolbox
The /etc/subgid and /etc/subuid files are only meant to be used when
running rootless, and hence don't have an entry for root.
https://github.com/debarshiray/toolbox/issues/267
=> Don't sanity check /etc/subgid and /etc/subuid when running as root

toolbox
Podman defaults to bind-mounting locations as read-write when neither
'rw' nor 'ro' is explicitly specified.
On Silverblue /usr is mounted read-only on the host. Therefore, it's
not possible to bind-mount it as read-write inside the toolbox
container.
It turns out that Podman doesn't downgrade the default mount flag to
read-only when the source location is such, and this breaks creating
new toolbox containers on Silverblue. See:
https://github.com/containers/libpod/issues/4061
Fallout from d63b0a9c0f1cd8a137ebc818b297f3b9303b5c32
=> Unbreak 'create' on Silverblue

toolbox
It's common for people to run the toolbox script straight out of the
source tree without installing it system-wide. In such cases, it's
likely that /etc/profile.d/toolbox.sh would be absent on the host, and
as a result also absent from the toolbox container.
The welcome messages and the primary shell prompt (or PS1) are set
through /etc/profile.d/toolbox.sh, so not having it does degrade the
user experience, but it's probably not severe enough to fail the 'run'
command.
This should have been part of commit 0db54946b43e040 which split the
copying of /etc/profile.d/toolbox.sh into a container into two steps to
avoid using 'podman cp'. It already tried to handle the missing file
in the first step, but not in the second step.
It's also nice to at least make the user aware of the situation by …
=> Be forgiving of a missing /etc/profile.d/toolbox.sh in 'run'

toolbox
This should make it more obvious which part of the two-step process of
copying /etc/profile.d/toolbox.sh into a container the strings are
coming from.
=> Tweak the debug output and error messages

toolbox
It seems cleaner to limit the use of colour to only marking running
containers. It's redundant to mention that the containers and images
were created by Toolbox because they are being shown by 'toolbox list'
anyway; and there's a second uncoloured heading in a different case,
that differentiates containers from images.
=> Drop the coloured heading from 'list'

toolbox, toolbox-sudo
A year ago, when rootless Podman was in its infancy, it was often
necessary to run rootful to test and shake out bugs in Podman. Things
are lot more mature now and this hasn't been necessary in the past few
months. Therefore, it's time to sunset this option.
Removing the --sudo option doesn't break backwards compatibility
because it was never documented or advertised to the user in any way.
It was a hidden option only meant to be used by those hacking on
Toolbox itself.
Note that this is different from running 'sudo toolbox ...', which is a
different use-case and uses separate code paths. This is about running
the rest of toolbox(1) as non-root and only invoking the container
tools like Podman as root.
This reverts commit 66ab4da724d066bdeacaf7e03f027d44ecc37f05.
=> Remove the hidden --sudo option and the /etc/sudoers.d snippet

images/fedora/f29/Dockerfile, images/fedora/f30/Dockerfile, images/fedora/f31/Dockerfile, images/fedora/f32/Dockerfile, toolbox
The older com.github.debarshiray.toolbox label is still used in most
places as an alias for the new name for the sake of simplicity and
compatibility; except in 'create', where the new label is explicitly
specified in addition to the older one to help popularize it via newly
created toolbox containers.
The older com.github.debarshiray.toolbox label should eventually be
dropped, but before that, the even older use of com.redhat.component
for tagging needs to be phased out. The com.github.debarshiray.toolbox
label was introduced in commit 0ab6eb7401fb3964, as part of Toolbox
0.0.8, right before the release of Fedora 30 [1]. Therefore,
com.redhat.component needs to stay at least until Fedora 29 is
supported.
[1] https://fedoraproject.org/wiki/Releases/30/Schedule
=> Update the label for tagging to reflect the project's new home

README.md
Toolbox is being used with Endless OS, which is an OSTree based
operating system built out of Debian packages, not RPMs; and in the
Fedora universe, CoreOS is being increasingly treated as a primary
use-case for Toolbox alongside Silverblue.
=> README.md: Tweak

completion/bash/toolbox, doc/meson.build, doc/toolbox-reset.1.md, doc/toolbox.1.md, toolbox
The 'reset' command is meant to factory reset a local Podman and
Toolbox installation. Every now and then early adopters and testers of
Toolbox have to do this when their local Podman state has gotten
irrecoverably broken due to some Podman bug.
It's useful to have a command that encapsulates all the steps to do a
factory reset, as opposed to having to spell them out separately. It's
easier to document, helps with user support, and can enable less opaque
error messages that suggest a way forward when nothing is working.
Note that when running as root, some care has been taken to avoid
removing directories that might be owned by the operating system. eg.,
on Fedora /var/lib/containers/sigstore is owned by the
containers-common RPM.
=> Add a reset command

toolbox
In the 'run' script are two main Podman commands. 'podman start' and
'podman exec'. 'podman start' is used for container initalization using
the 'init_container' function. But because this function is executed in
a subshell the next call doesn't wait for it to finish. Such an issue
isn't very common but it may happen.
This solves the potential issue by using a dirty hack. A simple while
loop that'll block the function until a 'block file' is deleted by the
preceeding process.
=> Make 'podman exec' wait for container init

toolbox
Toolbox containers using runc as their runtime don't work on host
operating systems using cgroups v2. They need to be migrated to crun.
'podman start' throws a specific error for such containers:
ERRO[0000]: oci runtime "runc" does not support CGroups V2: use
system migrate to mitigate
Error: unable to start container "fedora-toolbox-30": this version
of runc doesn't work on cgroups v2: OCI runtime error
This error is identified by the phrase "use system migrate to mitigate"
to avoid encoding any assumptions about updating from cgroups v1 to v2
or downgrading in the other direction.
If the migration fails, 'toolbox reset' is suggested as the last hope.
=> Try to migrate to a supported OCI runtime if 'podman start' suggests so

toolbox
While the rewrite in Go continues, this makes two high level changes to the current code.
First, it gives access to the host's systemd journal inside toolbox containers. This is something that users have been asking for a while and can be useful in the short-term. One can both query the journal using `journalctl(1)` and send log messages to it. However, queries only work for messages logged by the current user when running rootless.
As a fallout from the above, this also changes the way bind mounts are set up to align with the future direction of the Go rewrite and should make it easier to switch. In short, it reduces the number of bind mounts that are specified during `podman create ...` and instead moves them into the containers' entry point, as Colin has been suggesting.
=> Bind mount some locations at runtime and enable the systemd journal

completion/bash/toolbox, doc/toolbox.1.md, toolbox
Toolbox only offers a --verbose | -v option that shows debug information
only of Toolbox itself. We have no way of getting debug info right from
Podman without altering the code or running the commands themselves.
This just adds a new variable 'podman' that translates to a string
depending on the presence of '--very-verbose | -v' option. If this
option is used, every Podman command in the code is ran with '--log-level
debug' option. Use wisely, it can be 'very verbose'.
=> Add a '--very-verbose | -vv' option

toolbox
`run` should take one argument for command at least
=> Fix shift count out of range error

toolbox
Toolbox containers created prior to commit 8b84b5e4604921fa didn't use
'toolbox init-container' as their entry points. This prevents the
container from being configured at runtime through the entry point.
Being able to configure a toolbox container at runtime through the
entry point is very handy, as compared to doing it statically via
'podman create', because the configuration doesn't get permanently
baked into the container's definition. Instead, it's codified in
toolbox(1), which can be updated over time, and the container
reconfigured everytime it's started.
A deprecation notice is the precursor to actually dropping support for
these old containers in the future.
=> Deprecate all toolbox containers that don't use a reflexive entry point

toolbox
This is the second time a selinuxfs instance has leaked into
/sys/fs/selinux, tricking various components into trying to use
SELinux. Might be better to work this around in Toolbox until the
situation in Podman is figured out.
Based on an idea from Colin Walters.
https://github.com/containers/libpod/issues/4452
=> Wipe out the container's /sys/fs/selinux to stop advertising SELinux

doc/toolbox-init-container.1.md, toolbox
This is meant to help with the following issues in the immediate short-term:
* Some hosts don't have `/media`: https://github.com/containers/toolbox/issues/230
* Weird side-effects when `/media` is a symbolic link on the host: https://github.com/containers/toolbox/issues/330
=> Be more sophisticated when handling /media

toolbox
On Silverblue, /mnt is a symbolic link to /var/mnt. Matching the
presence of /var/mnt on the host inside the toolbox container would
make things less confusing for users.
https://github.com/containers/toolbox/issues/92
=> Give access to /var/mnt from the host operating system

doc/toolbox-init-container.1.md, toolbox
On Silverblue /mnt is a symbolic link to /var/mnt. Matching what the
host does will reduce weird side-effects.
https://github.com/containers/toolbox/issues/92
=> Set up /mnt to match the host

toolbox
/sys/fs/selinux is only present when SELinux is 'enforcing' or
'permissive'. When it's disabled, /sys/fs/selinux doesn't exist and
sysfs doesn't let you create it either. Therefore, the attempt to wipe
out the toolbox container's /sys/fs/selinux by bind mounting
/usr/share/empty over it fails, and in turn prevents the container from
starting up.
Fallout from f9cca5719d0a3f944647cdd2319fa2596bd4a878
https://github.com/containers/toolbox/issues/344
=> Unbreak 'enter' when SELinux is disabled

toolbox
/usr/share/profile.d is the default location where toolbox.sh is
installed, even though, in practice, most (all?) distributions use
/etc/profile.d. It's reasonable to at least make the code work with the
default build values.
=> Check /usr/share/profile.d when bind mounting toolbox.sh

meson.build, src/meson.build
The Go implementation is now considered stable enough for wider use,
and should have feature parity with its POSIX shell counterpart.
=> build: Ship the Go implementation by default, not the POSIX shell one

playbooks/shellcheck.yaml
Otherwise, the test fails with:
```
meson.build:8:0: ERROR: Program(s) ['go'] not found or not executable
```
=> playbooks/shellcheck: Add Go to the list of build dependencies

.zuul.yaml, playbooks/shellcheck.yaml
Toolbox requires Go 1.13, while Fedora 30 only has Go 1.12.17.
Therefore the test environment needs to be upgraded to something more
recent.
Otherwise, the test fails with:
```
note: module requires Go 1.13
```
The name of the go-md2man package changed in Fedora 31, and hence had
to be updated.
=> .zuul, playbooks/shellcheck: Use Go 1.13

src/cmd/run.go, toolbox
This is a suggestion to address #369, input and changes welcome.
I didn't want to count on `coreutils` so ran `test` inside `sh`, but perhaps that's fine.
=> Adding a test for $PWD in the container

src/pkg/utils/utils.go
The syscall.Dup2 wrapper isn't defined on aarch64, which breaks the
build as:
../../pkg/utils/utils.go:551:12: undefined: syscall.Dup2
=> pkg/utils: Make it build on aarch64

src/go-build-wrapper, src/meson.build, src/pkg/version/version.go
This removes the need to manually update the version in the Go source code when making a release.
=> build, pkg/version: Embed the version from Meson into the binary

src/pkg/podman/podman.go
We call `podman version` every time we want to check Podman's version. This slows Toolbox down considerably. It's more efficient if we call `podman version` just once and remember the output during runtime and use the cached value.
On Intel i5-6300U calling `time podman version --format json` takes roughly a bit over 100ms.
=> pkg/podman: Remember Podman's version during runtime

src/go-build-wrapper
The go compiler embeds full paths to modules and dependencies into the
binary. This prevents people from reconstructing a bit-for-bit identical
toolbox binary without going through several hoops.
Without patch:
$ strings build/src/toolbox | grep "$HOME" | wc -l
105
With patch:
$ strings build/src/toolbox | grep "$HOME" | wc -l
0
Signed-off-by: Morten Linderud <morten@linderud.pw>
=> go-build-wrapper: Ensure reproducible builds

src/cmd/root.go
Minor fix on root command, it was using slice verb format(`%p`) on an string instead of the corresponding verb (`%s`).
=> [cmd/root] Use string verb format for string path instead of slice

src/cmd/create.go, src/go.mod, src/go.sum
It doesn't make sense to show a spinner when the output is redirected
to something other than a terminal.
The spinner package we're using [0] has a problem with printing
additional characters when it's output (the standard output, in this
case) is not connected to a terminal.
This causes problems in our test suite (corrupts the output that is
checked). To prevent this the spinner should only be started when the
output of the program is not piped.
This uses the golang.org/x/crypto/ssh/terminal package to check if the
standard output is connected to a terminal or not, which is also what
Podman uses. The other option was the github.com/mattn/go-isatty
package but using it leads to a slightly bigger binary - 7778323 bytes
versus 7782284.
[0] https://github.com/briandowns/spinner
=> cmd/create: Show the spinner only when connected to a terminal

src/cmd/create.go
This doesn't seem to have any user-visible effect. However, since the
line was inadvertently removed, it's good to put it back.
Fallout from 950f510872404da8089ad7ce5911d8342bf7a116
Fix-up for https://github.com/containers/toolbox/pull/496
=> cmd/create: Restore the spinner, when pulling an image, to stdout

playbooks/fedora-31/setup-rpm-env.yaml, playbooks/fedora-rawhide/setup-rpm-env.yaml
Otherwise, the tests on Fedora 31 and Rawhide fail with:
meson.build:8:0: ERROR: Program(s) ['go'] not found or not executable
=> playbooks: Add Go to the list of build dependencies

test/system/201-run.bats
Now that the rewritten version is the [default](#437), the tests need to be adjusted.
Also, we did not enable tests on Fedora 32 -> enabling with this.
=> test/system: Don't check the output of 'toolbox run'

src/cmd/list.go
The rewritten Toolbox did not highlight running containers because the
code uses a special table writter from 'text/tabwriter' that does not
support ANSI color codes[0]. The solution used here is to use color
codes on _every_ lines of the output (including headers) and make the
color codes use the same number of characters.
=> cmd/list: Re-enable highlighting of running containers

src/cmd/create.go
Rewritten version of Toolbox supports newer syntax for entering a
container: `toolbox enter <name-of-container>`. This new workflow should
be shown in the hint after creating a container with `toolbox create`.
Before this change:
```
$ toolbox create 123
Created container: 123
Enter with: toolbox enter --container 123
```
After this change:
```
$ toolbox create 123
Created container: 123
Enter with: toolbox enter 123 | toolbox enter --container 123
```
Closes #489
=> cmd/create: Update hint after creating a container

src/cmd/run.go
The key containing the container's name (ie., "Names") is no longer a
string, but a slice of strings.
=> cmd/run: Adjust for changes in 'podman ps' in Podman 2.0

src/cmd/list.go, src/cmd/run.go, src/go.mod, src/go.sum, src/pkg/utils/utils.go
Every time Podman changes their JSON API Toolbox breaks horribly. That
is caused by the complete lack of type guards. With this, the verbosity
of the code goes up a bit but it should be much more resistant to API
changes.
If a field is of a not-expected type, the field is set to "<error>" and
an error message is printed after the rest of the table is printed into
the console.
An alternative to this solution is to unmarshal the JSON response to a
strongly typed structure, as pointed out by @owtaylor.
Closes: #502
=> cmd/list: Make listing of containers/images more robust

src/cmd/run.go
Users, who prefer shells other than Bash, tend to get confused when
Toolbox presents a Bash prompt to them. It would be better to be more
upfront about what the problem is, so that users can self-support
themselves.
https://github.com/containers/toolbox/issues/18
=> cmd/run: Make it more obvious when falling back to /bin/bash

src/cmd/initContainer.go
Podman doesn't mount a tmpfs at /tmp by default - it needs to be
separately requested. However, doing it as part of 'podman create ...'
won't add a tmpfs at /tmp for existing toolbox containers. Therefore,
it's best done as part of the entry point.
The mount options are the same as used by systemd (see tmp.mount) to
provide a tmpfs at the host's /tmp.
For what it's worth, the mount flags do differ slightly from the host.
The host has:
$ findmnt --output OPTIONS,PROPAGATION /tmp
OPTIONS                  PROPAGATION
rw,nosuid,nodev,seclabel shared
The container has:
$ findmnt --output OPTIONS,PROPAGATION /tmp
OPTIONS                                        PROPAGATION
rw,nosuid,nodev,seclabel,uid=100000,gid=100000 private
This difference was ignored because it doesn't appear to cause any …
=> cmd/initContainer: Mount a tmpfs at /tmp to match the host

meson.build
This adds a new option to Meson called `with_tests` making it possible to install whole 'test' subdir into the system's data dir (usually `/share` or `/usr/share`).
=> meson: Add option for installing tests

src/cmd/rm.go, src/cmd/rmi.go, src/pkg/podman/podman.go
The functions for removing containers/images are wrappers around Podman's commands. They should be in the `podman` package.
=> Move remove functions to the podman package

README.md
I was following the instructions for building and testing the project and I found that the parameter `builddir` was missing.
Without that, it won't install.
=> README.md: Add missing parameter at the installation instructions

src/libc-wrappers/libc-wrappers.c
This is based on the output of 'gcc -dM -E - </dev/null' on a ppc64le
system. For what it's worth, the _CALL_ELF macro is defined as 1 on
the big endian variants of the architecture.
The original intention in commit 6ad9c631806961f3 was to support the
architectures that Fedora builds for, and it doesn't care about PowerPC
variants that aren't ppc64le [1].
[1] https://fedoraproject.org/wiki/Architectures/PowerPC
=> libc-wrappers: Tighten the definition of the ppc64le definition

toolbox
Line 729:
if $podman_command image exists localhost/$base_toolbox_image
>/dev/null 2>&3; then
^-----------------^
SC2086: Double quote to prevent globbing and word splitting.
See: https://github.com/koalaman/shellcheck/wiki/SC2086
=> Silence SC2086

src/cmd/initContainer.go
There has been a long-standing issue[0] when symlinking /etc/resolv.conf
to /run/host/etc/resolv.conf (host's resolv.conf). Many solutions were
proposed. Hardcode other paths, where the file could be, completely rely
on tools like flatpak-session-helper that will track such files in a
single directory, or update the symlinking function to follow symlinks
and update the target path.
The first solution is the easiest short-term but not very good
long-term. The second solution is possibly the best long-term but there
is a problem with using flatpak-session-helper. It cannot be used as
root. That leaves the third option, follow symlinks and update the
target path if the target is an invalid symlink.
This commit takes the third approach to solve the issue. Now the target
of the symlinking is …
=> cmd/initContainer: Reinforce symlink redirection

profile.d/toolbox.sh
It tries to loosely mimic ncurses to look up a terminfo entry for the
current terminal, as mentioned in the terminfo(5) manual. Unlike
ncurses, it doesn't handle TERMINFO_DIRS, though, to avoid parsing an
array of directories for the sake of simplicity.
Every line of code in this file is part of the interactive shell's
start-up sequence, which makes it a trade-off between correctness and
speed. Therefore, the purpose of this warning is not to exhaustively
catch all possible corner cases, but to serve as a convenience in the
majority of cases. Ultimately, if someone is using an exotic terminal
set-up, then a missing warning is a minor price to pay in order to not
slow things down for the vast majority of users who don't.
Based on code written by Mert Alp Taytak: …
=> profile.d: Warn if $TERM has no terminfo entry in the container

src/cmd/initContainer.go
Fallout from 772b66bf3e962785730e55f6242fa74066de0743
=> cmd/initContainer: Fix typo

src/cmd/create.go, toolbox
Don't call get_group_for_sudo() on the host during create(). That runs
on the host, and thus will check which sudo group exists on the host.
But that is entirely irrelevant for sudo inside the container, and it
breaks when trying to create a Debian or Ubuntu based toolbox on a
Fedora host (or vice versa).
Also, there is no point in running the `podman create` command with an
extra sudo group, normal user privileges are just fine.
init_container() will call get_group_for_sudo() inside the container and
initialize the groups correctly there.
=> Drop unnecessary and wrong group detection on host

README.md, src/cmd/initContainer.go
Since Podman 2.0.5, containers that were created with
`podman create --userns=keep-id ...` automatically get the user added
to `/etc/passwd` [1]. However, this user isn't as fully configured as it
needs to be. The home directory is specified as `/` and the shell is
`/bin/sh`.
Note that Podman doesn't add the user's login group to `/etc/group` [2].
This leads to the following error when entering the container:
/usr/bin/id: cannot find name for group ID 1000
Therefore, the entry point needs to call usermod(8) to update the user,
instead of using useradd(8) to create it.
[1] Podman commit 6c6670f12a3e6b91
https://github.com/containers/podman/pull/6829
[2] https://github.com/containers/podman/issues/7389
https://github.com/containers/toolbox/issues/523
=> Unbreak 'sudo' inside toolbox containers with Podman 2.0.5

src/pkg/utils/utils.go
fedora 30 went EOL this may, thus it makes sense to update the default fallback image to fedora 32.  This only affects distributions w/o a vendor-supplied toolbox image, e.g. ArchLinux.
=> Update fallback fedora version from EOL 30

src/cmd/run.go
Podman sets keys 'ctrl-p' and 'ctrl-q' as the default detach keys. This behaviour is not desirable in Toolbox. Since Podman v1.8.2[0] it is possible to have set no detach keys by passing an empty string to the --detach-keys option.
Thanks to this the 'Ctrl+p' and 'Ctrl-q' combinations are doing what they should do normally in a terminal.
Fixes: https://github.com/containers/toolbox/issues/394
This PR is a reincarnation of #396 that I mistakenly closed by badly updating the author's branch.
=> cmd/run: Unset detach keys when executing commands

.zuul.yaml, playbooks/fedora-33/pre-common.yaml, playbooks/fedora-33/setup-env.yaml, playbooks/fedora-33/system-test-fedora-33.yaml
Fedora 33 branched out recently from Fedora Rawhide.
This should not be merged until [softwarefactory](https://softwarefactory-project.io) offers a Fedora 33 [label](https://softwarefactory-project.io/zuul/t/local/labels) (I expect it to be called `cloud-fedora-33-small`).
=> zuul, playbooks: Enable system tests on Fedora 33

.zuul.yaml
The tests were defined but not actually enabled in any pipeline.
Fallout from https://github.com/containers/toolbox/pull/550
=> zuul: Really enable system tests on Fedora 33

src/cmd/initContainer.go
The `redirectPath()` function does not work correctly if `containerPath`
does not exist (like `/media`). The error message often looks like this:
```
Error: failed to redirect /media to /run/media: remove /media: no such file or directory
```
This makes `redirectPath` try to remove `containerPath` only if it exists.
The existence of `containerPath` is checked using `utils.PathExist()`.
Fixes #539
=> cmd/initContainer: Remove path on redirection when it exists

src/cmd/initContainer.go
Enumeration of audio devices using libudev seems to work without this
but some properties are missing. This complicates the development of
software like pipewire.
Closes #468
=> cmd/initContainer: Give access to the udev database

src/cmd/initContainer.go
Some users tend to put random throwaway files in /tmp, so having that
location shared across the host operating system and toolbox containers
makes it a more pleasant user experience.
One nice side-effect of this is that it also makes the local file
system socket in /tmp/.X11-unix used by X11 clients available to
toolbox containers. So far, X11 clients inside toolbox containers used
the local abstract socket. However, since GNOME 3.38, Mutter no longer
listens on the abstract socket and only uses the file system socket to
start the Xwayland server [1]. Therefore, this makes it possible to
run X11 clients inside toolbox containers running on a GNOME 3.38 host.
[1] Mutter commit e2123768f635ee89
https://gitlab.gnome.org/GNOME/mutter/-/issues/1289 …
=> cmd/initContainer: Give access to /tmp from the host operating system

test/system/201-run.bats
This is useful for getting more info if a container fails to start. The current set of tests does not provide that information.
=> test/system: Test that toolboxes start alright

README.md
CoreOS hasn't existed since late 2016 and refers to the now-defunct
Container Linux. Fedora CoreOS is an entirely separate project.
=> docs: fix reference to Fedora CoreOS

profile.d/toolbox.sh
On Ubuntu, both /usr/share/terminfo and /lib/terminfo can have contents, and xterm-256color is at /lib/terminfo (provided by ncurses-base package) while xterm+256color is at /usr/share/terminfo (provided by ncurses-term package). This PR checks both directory to suppress the warning.
=> Fix warning for Ubuntu containers: "Error: terminfo entry not found for xterm-256color"

src/cmd/create.go
As suggested by Giuseppe Scrivano.
However, I don't understand the issue well enough to actually come up with a meaningful commit message. We should at least explain the user-facing problem that this solves.
=> cmd/create: Mount a new devpts file system at /dev/pts

src/cmd/initContainer.go
... by giving access to /var/lib/libvirt from the host operating
system.
Discussed with Daniel P. Berrangé.
https://github.com/containers/toolbox/issues/379
=> cmd/initContainer: Enable running minikube on Silverblue

test/system/201-run.bats, test/system/helpers.bash
When I added the test that looked at the logs of a toolbox, I did not
realize that the startup of a toolbox takes some time. That caused the
CI to flake even more than usual.
The solution I used was inspired by a helper function in Podman's test
suite (WaitContainerReady()).
=> test/system: Rework check if toolbox started successfully

src/cmd/create.go, src/cmd/initContainer.go, src/cmd/run.go, src/go.mod, src/go.sum, test/system/helpers.bash
This is one more step towards enabling toolbox(1) to be run as root.
When invoked as 'sudo toolbox ...' there's no user or session D-Bus
instance available for the root user, which prevents the use of D-Bus
services like o.fd.Flatpak.SessionHelper.
https://github.com/containers/toolbox/issues/267
=> cmd/initContainer: Don't rely on user D-Bus to track time zone configuration

README.md
Using the word 'unprivileged' confuses readers because it means
different things to different people. eg., it can mean 'rootless' or
'sandboxed', which are quite different things. It becomes even more
confusing given the ongoing work to make 'sudo toolbox ...' work.
It's nice to mention that Toolbox is targetted at Linux operating
systems and that it relies on standard container technologies from OCI.
=> README.md: Improve the introductory paragraph

src/cmd/create.go
As requested by Colin Walters.
=> cmd/create: Expose the host's /boot inside the container at /run/host

src/cmd/initContainer.go, test/system/helpers.bash
... by running updatedb(8) at 24 hour intervals.
https://github.com/containers/toolbox/issues/391
=> cmd/initContainer: Make locate(1) work inside toolbox containers

src/cmd/create.go
One of the biggest advantages of running as root is the ability to have
all the UIDs from the host operating system mapped into the container
by using the host's user namespace.
This can be a big help when faced with permission problems.
https://github.com/containers/toolbox/issues/267
=> cmd/create: Use the host's user namespace when running as root

images/fedora/f28/extra-packages, images/fedora/f29/extra-packages, images/fedora/f30/extra-packages, images/fedora/f31/extra-packages, images/fedora/f32/extra-packages, images/fedora/f33/extra-packages, images/fedora/f34/extra-packages, src/cmd/create.go
This series mounts the Avahi daemon socket inside the toolbox container and adds the needed dependencies for having Avahi working out of the box (avahi & nss-mdns).
/cc @debarshiray @HarryMichal 
It also fixes https://github.com/containers/toolbox/issues/209
=> Mount Avahi Daemon socket inside the toolbox container

profile.d/toolbox.sh
All the fields defined in /usr/lib/os-release were being injected into
the shell as environment variables. This is unintentional. Some of the
variables have relatively generic names, and having them in the
environment can lead to unexpected surprises.
Fallout from c6e37cdef37e2276207b34a42919f1e0ac4a04dc
=> profile.d: Don't leak all the os-release fields into the shell

playbooks/fedora-33/pre-common.yaml
The system tests for Fedora 33 were failing:
```
not ok 21 Remove all images (2 should be present; --force should not
be necessary)
3ac100502d2123aff1cf6314760c7a89c55108b8de6ea3c10ddc79a1479f0fca
has dependent children
4a6adf1f2a96adf5ea0c02b61f9fa574306f77fc522f39c2ce6bb164daead882
has dependent children
3ac100502d2123aff1cf6314760c7a89c55108b8de6ea3c10ddc79a1479f0fca
has dependent children'
4a6adf1f2a96adf5ea0c02b61f9fa574306f77fc522f39c2ce6bb164daead882
has dependent children'
```
Fallout from ff4e4905daeb7e65f3fae765fab9f7a0a2ac74a7
=> playbooks/fedora-33: Fix the image URLs by adding the version suffix

src/cmd/run.go
This will let GNOME Terminal handle toolbox(1) running as root, by not
trying to preserve the current toolbox container if it's running as
root. This is similar to how terminals don't preserve the current
working directory for interactive shells running as root.
This needs a VTE that supports the UID parameter in the OSC 777 escape
sequence, as given below:
```
OSC 777 ; container ; push ; NAME ; RUNTIME ; UID BEL
OSC 777 ; container ; push ; NAME ; RUNTIME ; UID ST
OSC 777 ; container ; pop ; NAME ; RUNTIME ; UID BEL
OSC 777 ; container ; pop ; NAME ; RUNTIME ; UID ST
```
=> cmd/run: Notify the terminal about the real UID of 'toolbox enter'

src/cmd/initContainer.go
Hi!
I simply add the mapping of `/run/host/var/lib/systemd/coredump` to `/var/lib/systemd/coredump` so `coredump` can be used to read coredump file inside the toolbox.
To test it, simply run the following:
```bash
me@host:~$ toolbox enter
...
me@toolbox:~$ perl -e 'unpack p, 1x8'
Segmentation fault (core dumped)
me@toolbox:~$ coredumpctl dump
PID: 3545 (perl)
UID: 1000 (me)
GID: 1000 (me)
Signal: 11 (SEGV)
Timestamp: Mon 2020-11-23 21:18:56 CET (52s ago)
Command Line: perl -e unpack p, 1x8
Executable: /usr/bin/perl
...
```
I took a bit of time to figure out this PR because I was using `./toolbox` to test my code which is a shell script and not the go code I was modifying...
By the way, how the old shell script is still used in `toolbox`?
Best regards.
=> Access coredump log from toolbox.

playbooks/fedora-31/setup-env.yaml, playbooks/fedora-32/setup-env.yaml, playbooks/fedora-33/setup-env.yaml, playbooks/fedora-rawhide/setup-env.yaml
The most important bit is the use of the 'creates' parameter of the
'command' module [1] because it conditionalizes the invocation of
'systemd-tmpfiles' on the presence of /run/media and self-documents its
purpose.
[1] https://docs.ansible.com/ansible/2.4/command_module.html
=> playbooks: Improve how 'systemd-tmpfiles --create' is invoked

src/cmd/create.go, src/cmd/enter.go, src/cmd/initContainer.go, src/cmd/list.go, src/cmd/rm.go, src/cmd/rmi.go, src/cmd/root.go, src/cmd/run.go
I noticed we put periods at the end of descriptions of flags while most tools (e.g. git, podman, skopeo, buildah, tools from coreutils,..) do not. Let's not deviate :). This is not very pressing because we don't show the description anyway.
=> cmd: Remove periods at the end of flag descriptions

src/cmd/create.go
These two options are incompatible -> make them mutually exclusive.
=> cmd/create: Make options --image and --release mutually exclusive

src/cmd/create.go, src/cmd/enter.go, src/cmd/run.go, src/pkg/utils/utils.go, test/system/102-create.bats
regexp.MatchString() should only return an error if a wrong pattern is
used. This does not need to be checked outside of the 'utils' package
because the used pattern does not change and it should work. The only
value that needs to be checked is 'matched' -> IsContainerNameValid
only returns a bool.
=> Correctly check validity of container name

src/go-build-wrapper
In some environments (e.g., Fedora's build system) 'go build' takes the
last of path passed to the -o option and uses it for the final binary
name instead of using the project's name.
=> src/go-build-wrapper: Explicitly specify final binary name

profile.d/toolbox.sh
Otherwise, every zsh instance was running into:
```
zsh: #: command not found...
```
Fallout from dcdfa3a1f5a3421330397ea72c0df132a260853d
=> profile.d: Restore compatibility with Z shell

completion/bash/toolbox, doc/toolbox-create.1.md
The --candidate-registry is a lesser known option only supported by
the POSIX shell implementation. The Go never implementation never
offered it, and nobody has felt its absence so far. So, it's safe to
assume that there's no urgent need to port it to Go, and it's better to
not confuse users by mentioning it.
=> completion, doc/toolbox-create: Remove --candidate-registry

completion/bash/toolbox, src/pkg/utils/utils.go
Rawhide currently points to Fedora 34, and Fedora 30 reached End of
Life on 24th November:
https://fedoraproject.org/wiki/End_of_life
=> completion, pkg/utils: Update the range of supported Fedora releases

src/cmd/list.go, src/cmd/rm.go, src/cmd/rmi.go, src/pkg/podman/podman.go
The com.github.debarshiray.toolbox label was introduced in commit
0ab6eb7401fb3964 to replace the com.redhat.component label for
filtering toolbox containers and images. This happened right before
the release of Fedora 30, which hasn't been supported for a while [1].
Therefore, it's time to stop using the old label.
It's also time to start using the newer com.github.containers.toolbox
label that was introduced in commit de5e5df9b793edc7 to reflect the
project's new home under the Containers organization on GitHub.
[1] https://fedoraproject.org/wiki/Releases/30/Schedule
=> Update the labels used for filtering toolbox containers images

src/cmd/create.go
The same image ID can be referred to by multiple names. It's common
that one of the names use the 'latest' tag, while another uses a
specific version number. It's better to resolve a short image name to
one with a specific version number, because the meaning of the tag is
clear and won't change with time.
=> cmd/create: Try to avoid 'latest' tags, when looking at RepoTags

completion/bash/toolbox, doc/toolbox-create.1.md, doc/toolbox-enter.1.md, doc/toolbox-run.1.md, profile.d/toolbox.sh, src/cmd/create.go, src/cmd/enter.go, src/cmd/run.go, src/pkg/utils/utils.go
This is based on https://github.com/containers/toolbox/pull/658
It splits up the commits a bit, contains some fix-ups, but most importantly skips some parts of the container & image tracking backend to side-step issues like the one caused by the use of `latest` tags. We can introduce the rest of the new backend later once we have solved all those issues.
=> Support RHEL hosts by creating containers based on UBI

src/cmd/initContainer.go
On Ubuntu host and images, the `/run/host/etc/localtime` points to `/usr/share/zoneinfo/SomeTimeZone`; which breaks current code that assumes it point to `/run/host/usr/share/zoneinfo/SomeTimeZone`.
=> cmd/initContainer: fix /etc/localtime handling for Ubuntu containers.

profile.d/toolbox.sh
While Toolbox's test suite explicitly uses --shell=sh when running
shellcheck(1) on profile.d/toolbox.sh, external tools like Coverity
can't be expected to do the same. So they complain:
Line 1:
[ "$BASH_VERSION" != "" ] || [ "$ZSH_VERSION" != "" ] || return 0
^-- SC2148: Tips depend on target shell and yours is unknown. Add a
shebang or a 'shell' directive.
See: https://github.com/koalaman/shellcheck/wiki/SC2148
=> profile.d: Silence SC2148

doc/toolbox-create.1.md, doc/toolbox-init-container.1.md
Ever since version 0.0.10, all newly created toolbox containers use a
reflexive entry point [1] and don't need a user-specific customized
image. Older containers that don't use a reflexive entry point were
deprecated in version 0.0.17 [2], and aren't even supported in the Go
implementation.
Therefore, it's time to finally update the manuals to document the
current way of doing things. Since the reflexive entry point is a key
feature of toolbox containers, some text was added to explain why it's
necessary and what it does.
[1] Commit 8b84b5e4604921fa
https://github.com/containers/toolbox/pull/160
[2] Commit 9dc52814301c5a3f
https://github.com/containers/toolbox/pull/336
=> doc/toolbox-create, doc/toolbox-init-container: Mention the entry point

doc/toolbox-create.1.md
The Go implementation prefers a newer syntax for assigning a custom
name to a toolbox container. The --container option is still supported
for backwards compatibility, but the manuals should show the new
workflow.
=> doc/toolbox-create: Update how toolbox containers are named

doc/toolbox-create.1.md, doc/toolbox-enter.1.md
The Go implementation prefers a newer syntax for assigning a custom
name to a toolbox container. The --container option is still supported
for backwards compatibility, but the manuals should show the new
workflow.
=> doc/toolbox-enter: Update how toolbox containers are named

README.md
Without this I get an error:
```
$ meson -Dprofile_dir=/etc/profile.d builddir
The Meson build system
Version: 0.55.3
Source dir: /home/user/toolbox
Build dir: /home/user/toolbox/builddir
Build type: native build
Project name: toolbox
Project version: 0.0.97
meson.build:1:0: ERROR: Unknown compiler(s): ['cc', 'gcc', 'clang', 'pgcc', 'icc']
The follow exceptions were encountered:
Running "cc --version" gave "[Errno 2] No such file or directory: 'cc'"
Running "gcc --version" gave "[Errno 2] No such file or directory: 'gcc'"
Running "clang --version" gave "[Errno 2] No such file or directory: 'clang'"
Running "pgcc --version" gave "[Errno 2] No such file or directory: 'pgcc'"
Running "icc --version" gave "[Errno 2] No such file or directory: 'icc'"
A full log can be found at …
```
=> Update the build requirements

test/system/README.md
The repositories under the ztombol namespace have been inactive since
2016, and the code is now maintained by the bats-core organization.
=> test/system/README.md: Update the URLs for bats-assert and bats-support

images/fedora/f32/Dockerfile, images/fedora/f33/Dockerfile, images/fedora/f34/Dockerfile, playbooks/fedora-32/setup-env.yaml, playbooks/fedora-33/setup-env.yaml, playbooks/fedora-34/setup-env.yaml, playbooks/fedora-rawhide/setup-env.yaml, src/pkg/utils/utils.go, test/system/101-create.bats, test/system/102-list.bats, test/system/libs/helpers.bash
Due to historical reasons, the 'fedora-toolbox' image hosted in Fedora's
image registry[0] needed to have a special prefix (so called Fedora
generational core). That puts more strain on the image registry because
the toolbox images are periodically refreshed and the previous ones are
kept in the registry. Also, the code of Toolbox needed to account for
this.
This special prefix is no longer required and so we'll start creating
images simply called 'fedora-toolbox'. To be able to use them, Toolbox
needs to be updated, too.
This cannot be merged until all required `fedora-toolbox` images are
available for use.
Here's a [link](https://src.fedoraproject.org/container/fedora-toolbox/pull-request/2) to the PR in Fedora's dist-git to remove the prefix.
=> src/cmd, playbooks: Drop image prefix for fedora-toolbox

toolbox
Shell Toolbox has been replaced by the Go implementation a quite long
time ago. People on several ocassions created PRs that still update it.
It was not clear that the Shell implementation has been deprecated and
is no longer maintained.
=> Add deprecation notices to Shell Toolbox

playbooks/setup-env.yaml, test/system/libs/helpers.bash
Since commit b27795a03ec8ae31, each section of the test suite starts
and ends with a clean Podman state. This includes removing all images
from the local containers storage. Therefore, the images get downloaded
multiple times during the course of the test suite.
This commit restores the earlier behaviour where the images would get
downloaded only once, by copying them to separate directories outside
the local containers storage and then restoring them when the tests
are run.
https://github.com/containers/toolbox/pull/517
=> playbooks, test/system: Avoid downloading the images multiple times

src/cmd/create.go
Some machine don't have /mnt. This just checks if it exists before trying to bind mount it into the container.
cc @tfmoraes
=> Check if /mnt exists before adding it as a volume mount

src/cmd/initContainer.go
This directory structure contains in distros that have systemd247
or higher (eg F34) systemd-resolved varlink socket which toolbox
guest can use
=> Also bind mount systemd-resolved /run directories

src/pkg/utils/utils.go
On Fedora Silverblue 33 the output of 'findmnt --noheadings --output
OPTIONS /usr' is:
ro,relatime,seclabel,ssd,space_cache,subvolid=257,subvol=/root
(Fedora uses btrfs as it's default filesystem since version 33[0]). But
when you make the current deployment mutable using 'ostree admin unlock'
the output of the command changes to something like this:
ro,relatime,seclabel,ssd,space_cache,subvolid=257,subvol=/root
rw,relatime,seclabel,lowerdir=usr,upperdir=/var/tmp/ostree-unlock-ovl.JLXHQ0/upper,workdir=/var/tmp/ostree-unlock-ovl.JLXHQ0/work
This causes utils.GetMountOptions to error out preventing a successful
creation of a container with 'toolbox create' when the deployment is
unlocked.
For Toolbox the first line is the more relevant because even though /usr
is technically writeable, it …
=> pkg/utils: Drop length check when getting mount options

src/cmd/create.go
CoreOS recently made /boot read-only[0]. This caused an issue with starting containers because /boot was mounted only with option rslave but missed the ro option. This caused a permission issue.
This scenario is very similar to the one with /usr on Fedora Silverblue. The solution for this is to check mount options of the path and check if it uses the rw option or ro and then add it to the mount options in the --volume option in 'podman create'.
Fixes: https://github.com/coreos/fedora-coreos-tracker/issues/734
https://github.com/coreos/fedora-coreos-config/commit/1de21ffa98bb22995e5b059501e1955bf52b562c
This, sadly, does not fix existing containers on CoreOS because the configuration of existing containers can not be changed. The only way to get this fix is to recreate toolboxes.
=> src/create: Handle read-only /boot

images/fedora/f32/README.md, images/fedora/f33/README.md, images/fedora/f34/README.md
A while ago, 'podman build' stopped supporting COPY with relative
symbolic links [1]. Therefore, these image definitions can't be used
without first temporarily removing the symbolic links, which is
annoying.
The downside is that the copies of README.md now has to be separately
updated, which isn't that big of a hassle compared to the problem that
it fixes.
[1] https://github.com/containers/buildah/issues/1952
=> images: Use a regular file, not a symbolic link, for README.md

src/cmd/create.go
Too many appends. Instead, put the required sequence into a single array
and append only the variable parts.
Instead of calling "init-container" with "--verbose", call it rather
with "--log-level debug".
=> cmd/create: Cleanup entry-point command assembly

src/cmd/initContainer.go
The init-container command uses several flags. In the future we'd like
to minimize their number. In order to be able to do that without
breaking systems with older versions of Toolbox, the command can't error
out due to usage of unknown flags.
=> cmd/initContainer: Ignore unknown flags

playbooks/system-test.yaml, playbooks/unit-test.yaml
Call "meson builddir" makes Meson create a build directory called
"builddir". It does not make it build the project. A subsequent call to
"meson compile" or "ninja" needs to be made. This subtle detail causes
a minor (purely visual) discrepancy in the CI output. Fix this for both
unit-test & system-test job definitions.
=> playbooks: Properly separate builddir setup & build

meson.build
Shell Toolbox has been replaced by the Go implementation a quite while
ago. It is kept in the repository but is no longer actively developed.
There is no need to continue checking it with ShellCheck.
=> build: Drop ShellCheck on Shell Toolbox

src/cmd/create.go, src/cmd/list.go, src/cmd/rm.go, src/cmd/rmi.go, src/cmd/root.go
While we mostly report an error correctly, we do not include (wrap) the
underlying cause. This can make debugging tricky at times.
=> cmd: Properly wrap around errors

src/cmd/rm.go, src/cmd/rmi.go
Fallout from: 06dcdbe2a6e057f28b1cf02a8193db77dfa2f4f2
=> cmd/rm,rmi: Properly rename called function

src/pkg/utils/utils.go
32 is approaching EOL
see also #546
=> utils: bump Fedora fallback version to 33

CONTRIBUTING.md, README.md, images/fedora/f32/README.md, images/fedora/f33/README.md, images/fedora/f34/README.md
The default branch was renamed from "master" to "main".
https://github.com/containers/toolbox/issues/740
=> Update references to the default branch name

playbooks/system-test.yaml
Execution time of a test can be a very useful tool.
=> playbooks/system-test: Show test execution time

src/cmd/create.go
The spinner needs to be explicitly stopped before showing the example
'enter' command for using the container. Otherwise, it gets misprinted:
```
$ toolbox create foo
Creating container foo: / Created container: foo
Enter with: toolbox enter foo
```
A comment was added to highlight this, since it might not be obvious at
first sight.
Due to such potential quirks, it might be better to keep the spinner
somewhat tightly encapsulated with the code that necessitates it, which
in this case is `podman create`. For instance, we already need to be
careful to avoid enclosing the `pullImage` function with a spinner
because it carries it's own.
The code lying between the `podman pull` and the `podman create` is so
light that a human user isn't able to discern the absence of a
spinner. So, it seems …
=> cmd/create: Unbreak the spinner and the hint about using the container

README.md
See discussion on #710. ArchLinux with a missing machine-id fails, but with a machine-id succeeds.
If this is not supposed to be required, I can open a bug report instead.
=> README: /etc/machine-id is required

src/cmd/run.go
Since v0.0.91[0] Toolbox throws an error if $PWD is not available in a
toolbox. While this fixes the problem with 'toolbox enter/run' silently
failing to enter/exec in a container, it still requires an action to be
made by the user. I believe it is better to handle such situations more
gracefully by falling back to entering the user's home folder + printing
a warning about doing so.
[0] https://github.com/containers/toolbox/pull/370
=> cmd/run: Use home folder when $PWD is not in toolbox

doc/toolbox-create.1.md, doc/toolbox-enter.1.md, doc/toolbox-help.1.md, doc/toolbox-init-container.1.md, doc/toolbox-list.1.md, doc/toolbox-rm.1.md, doc/toolbox-rmi.1.md, doc/toolbox-run.1.md, doc/toolbox.1.md
The manual pages were not updated for quite some time already. Several parts are not relevant anymore (e.g., mentions of 'candidate registry') and some could be more accurate/more elaborate.
I mainly expanded toolbox(1), toolbox-create(1) and toolbox-init-container(1) where I tried to explain more of the philosophy of toolbox containers/images, what defines them, what makes them different than common OCI containers/images.
=> doc: Match man pages with Go Toolbox and extend them

src/cmd/list.go
I did not like the way listing of containers was written. There was a lot of duplication and was very prone to error.
Now the labels are tracked in a variable, function for checking if a container/image is more lightweight (requires data to be passed to it) and functions for getting a list of toolboxes and toolbox images are much easier to understand.
=> Simplify container & image fetching using labels

test/system/001-version.bats, test/system/002-help.bats, test/system/101-create.bats, test/system/102-list.bats, test/system/103-run.bats, test/system/104-rm.bats, test/system/105-rmi.bats
The system test refactor[0] replaced the 'run_toolbox' helper function
with 'run toolbox', which is a normal invocation of Toolbox. This makes
it impossible to override Toolbox used during the tests using env var.
[0] https://github.com/containers/toolbox/pull/693
=> test/system: Use env var for invoking Toolbox

.zuul.yaml
Fedora 32 has reached EOL in 25/05/2021[0]. Bye bye...
[0] https://fedorapeople.org/groups/schedule/f-32/f-32-all-tasks.html
=> ci: Drop testing on Fedora 32

playbooks/setup-env.yaml, profile.d/toolbox.sh, test/system/101-create.bats, test/system/102-list.bats, test/system/libs/helpers.bash
The fedora-toolbox:32 image is the first of images in the renamed
toolbox image repository[0]. With the change we can drop the
pull_image_old() function because it was kept only for the old image.
[0] https://github.com/containers/toolbox/pull/615
=> test/system: Bump secondary fedora image from 29 to 32

src/cmd/list.go, test/system/000-setup.bats, test/system/102-list.bats, test/system/libs/helpers.bash
=> cmd/list: Recognize UBI images

src/cmd/list.go, test/system/000-setup.bats, test/system/102-list.bats, test/system/libs/helpers.bash
Not having the corresponding image for UBI toolbox containers show up
in 'toolbox list' is a rough edge. However, the whole UBI feature is
a bit experimental. It's about a gratis RHEL environment getting
created in a jiffy on any host, which is something that hasn't been
done before, and those containers also suffer from various shortcomings
because of the limited package set of UBI.
So it's not that big of a problem if it takes a release or two to
hammer out the details. Especially since it's likely that there will
be a special Toolbox-specific image that's created out of the UBI RPM
repositories, which will likely have the com.github.containers.toolbox
label.
There's also the issue that 0.1.0 needs to be finished, and for that
the the churn needs to be kept down. Changing the labels can …
=> cmd/list, test/system: Ignore the problem of UBI not being listed

README.md, src/cmd/initContainer.go
Since `/etc/machine-id` is bind mounted into the toolbox container from
the host operating system, it doesn't make sense to make it mandatory
for images to have that file. Apparently, (some?) Arch Linux images
don't have `/etc/machine-id`.
Since a missing `containerPath` for a directory is handled the same way,
there's no reason not to do the same for regular files. It will make
life a bit easier for those creating toolbox images for different
distributions.
https://github.com/containers/toolbox/pull/710
=> README.md, cmd/initContainer: Don't require /etc/machine-id in images

src/cmd/root.go
Fallout from 8bc0018eaa6e901f942d14d221270b8d5b1e1859
=> cmd/root: Style fix

src/cmd/rm.go, src/cmd/rmi.go
Fallout from 06dcdbe2a6e057f28b1cf02a8193db77dfa2f4f2
=> cmd/rm, cmd/rmi: Style fixes

src/cmd/list.go
Fallout from 2369da5d31830e5cd3e1a13857a686365875ae61
=> cmd/list: Style fixes

src/cmd/list.go, test/system/102-list.bats
Some people create images manually. If such created images are recognize
as toolbox images (they have the proper labels) but do not have
a name/tag then 'toolbox list' will panic due to index being out of
range.
=> cmd/list: Support images without names

src/cmd/create.go
It's good to avoid subtle variations in the logic for /boot and /usr,
unless actually necessary, because it makes the code easier to read.
Fallout from 7ec26a27df7199777b94a17b2935e7ff35757937
=> cmd/create: Style fixes

src/cmd/create.go, src/cmd/list.go, src/cmd/root.go
This builds upon commit eedfdda535f762dc, which added more information
to the error messages presented to the user by including the errors
thrown by the lower layers of the code.
However, if the errors are being thrown by external modules, or are
coming from functions that are too many layers below, then it is
difficult to guarantee their contents. They might be duplicating
information added by the upper layers, or in extreme cases might even
contain JSON blobs, simply because it made sense for the API contracts
of the functions generating the errors.
Therefore, it's better to put them in the debug logs to retain control
over what gets displayed to the user under normal (ie., non-debug)
operation.
=> Ensure that all unknown error messages are limited to the debug logs

src/cmd/initContainer.go
The reason for setting FParseErrWhitelist.UnknownFlags to 'true' was to
prepare for a future when the 'init-container' command would have fewer
options than it does now.
However, there's no need to prepare for it, because the version of
toolbox(1) that's bind mounted into the container is the same as the
one on the host. So, FParseErrWhitelist.UnknownFlags can be set in
future if, or when, the number of flags do get reduced.
This reverts commit 5c2086e9ea045f73bdc574734d659807a2d68d1e.
=> cmd/initContainer: Don't ignore unknown flags, yet

test/system/002-help.bats
This is a continuation of commit 9fdf10f2e1720b0e, which added a test
for the handling of unknown flags but without specifying any command.
=> test/system: Test the handling of unknown flags with each command

src/cmd/run.go
Currently, the `enter` command involves two extra invocations of
`podman exec` to detect if the user's chosen shell and current working
directory are present inside the toolbox container. Each invocation is
sufficiently expensive to add a noticeable overhead to the `enter` and
`run` commands. Moreover, file system operations being inherently racy,
it's always better to detect errors and handle them instead of trying
to pre-emptively avoid them.
Therefore, this shuffles the code around to attempt the non-fallback
invocation, and then handle the errors by attempting a series of
fallbacks for the command and the current working directory.
Unfortunately, in case of a missing command, `capsh(1)` adds an extra
error message that seems difficult to get rid of:
```
/bin/sh: …
```
=> cmd/run: Optimize 'enter' and 'run' in the non-fallback case

src/cmd/root.go, test/system/002-help.bats
One of requirements to get Toolbox to RHEL is to make the root command
('toolbox') have similar functionality as 'toolbox enter'.
Making 'toolbox' behave exactly the same as 'toolbox enter', making it
effectively an alias is not exactly desirable as the root command has
its own behaviour too. Instead, `toolbox` only translates to `toolbox
enter` when no arguments or flags (excluding the global ones) are
provided.
=> cmd/root: Wire root command to 'enter' command

meson.build, meson_options.txt
* in situations where that directory isn't accessable, it would be nice
to support installing everything else to a prefix and then instructing
the user to get those those files installed somehow else.
* I'm not sure if systemd is required if we don't use tmpfilesdir, but
I'm leaving it outside of the if
=> Allow override of tmpfilesdir folder

src/cmd/create.go, src/pkg/utils/utils.go, src/pkg/utils/utils_test.go
Turns out the braces do not need to be escaped. Let's fix it!
Method for matching strings against a regular expressions return
an error when the regular expressions is faulty. The first return value
tells if a match was found. So, we should check for a match and not for
an error.
=> pkg/utils, cmd/create: Properly check reference being an ID

playbooks/setup-env.yaml
An upgrade of glibc has caused an issue on Fedora Rawhide[0]. We need a
clear indicator that a change in glibc could cause it.
[0] https://github.com/containers/toolbox/issues/821
=> playbooks/setup-env: Show version of glibc

images/fedora/f33/extra-packages, images/fedora/f34/extra-packages, images/fedora/f35/extra-packages
While toolbox containers are started without network namespace isolation, in the current release of `fedora-toolbox` images there is no way to inspect and interact with network interfaces of the system (or even look up the ip address without exiting the container) - neither `ip` command, nor `ifconfig` commands are present.
This PR adds `iproute` to `extra-packages` list for all Fedora versions. This adds only *2.9 MB* extra size and results in installation of the following packages (for `f31` toolbox):
1. `iproute`
2. `libmnl`
3. `linux-atm-libs`
4. `iproute-tc`
=> Install iproute package in toolbox images

src/cmd/create.go
Having whole host filesystem mounted inside of a toolbox is a very handy
feature that makes the toolboxes much more complete environment and
covers systems with diverse root directories (e.g., Fedora Silverblue).
Thanks to the chnge we can drop several separate mounts which are being
handled now by mounting the whole host filesystem.
=> cmd/create: Mount whole host instead of its subsets

src/cmd/create.go, src/cmd/enter.go, src/cmd/root.go, src/cmd/run.go, src/pkg/utils/utils.go
The ResolveContainerAndImageNames() function does too much work. It
makes more sense to have two functions: one for resolving the image
name and another for resolving the container name.
https://github.com/containers/toolbox/pull/828
=> pkg/utils: Separate container & image name resolution

src/pkg/utils/utils.go
It was not apparent on first glance that the second parameter
represented a release (resp. tag).
=> pkg/utils: Rename parameter in ParseRelease

test/system/102-list.bats
The output of `podman build` has changed a bit. Each line of log
describing the build is now in the format of:
- STEP i/n: msg
instead of:
- STEP i: msg
where i is the current step and n the maximum number of steps.
The exact format is not important for the purpose of testing Toolbox, so
we may fallback to partial string testing.
Also the latest step ("COMMIT") seems to no longer be considered a step,
so just check for the word.
=> test/system: Adjust asserts for broken test

src/pkg/utils/utils.go
=> utils: bump the fallback Fedora version to 34

test/system/104-run.bats
This is a naive attempt to solve the flaking. It could be caused by what
is going inside of the run function.
Supersedes https://github.com/containers/toolbox/pull/705
=> test/system: Fix flaky test

src/cmd/create.go
It's not possible to programmatically detect when an image requires
logging into the registry [1]. Therefore, instead of trying to handle
'podman pull' failures due to lack of authorization, just mention that
private images require 'podman login' and that further details of the
failure can be found by using the --verbose option.
[1] https://github.com/containers/podman/issues/10858
https://github.com/containers/toolbox/issues/754
=> cmd/create: Mention that private images require 'podman login'

test/system/libs/helpers.bash
Using the current working directory for cache is not a good solution
since the test files may reside in a location that is unwritable (e.g.,
/usr/share). The `BATS_RUN_TMPDIR` variable should point to a location
that is sure to be writeable from the test suite.
=> test/system: Use BATS_RUN_TMPDIR for image cache

images/test/busybox/Containerfile, images/test/busybox/README.md, test/system/libs/helpers.bash
Due to docker rate limiting we can not rely in docker.io for retrieving the images.
This was detected when executing our tests for podman fedora gating pipeline. Our busybox image was not downloaded and
one of the list tests was failing.
=> tests: Changed container image source for busybox

test/system/002-help.bats, test/system/101-create.bats, test/system/102-list.bats, test/system/103-container.bats, test/system/104-run.bats, test/system/105-rm.bats, test/system/106-rmi.bats, test/system/libs/helpers.bash
Toolbox can't run properly if the XDG_RUNTIME_DIR is not set properly.
Now the tests can run in environments without it by setting it to /run/user/$UID if empty.
=> tests: Fixed tests to setup the XDG_RUNTIME_DIR variable when empty

test/system/102-list.bats
Signed-off-by: Alex Jia <chuanchang.jia@gmail.com>
=> test/system: fix typo in 102-list.bats

src/cmd/run.go
Currently, 'toolbox enter' can get into a loop if the user tried to
run something inside the shell that didn't exist, and quit immediately
afterwards:
⬢$ foo
bash: foo: command not found
⬢$
logout
Error: command /bin/bash not found in container fedora-toolbox-34
Using /bin/bash instead.
⬢$
This is because:
* The shell forwards the exit code of the last command that was
invoked as its own exit code. If the last command that was
attempted was absent then this exit code is 127.
* 'podman exec' uses 127 as the exit code when it can't invoke the
command. If it's able to successfully invoke the command, it
forwards the exit code of the command itself.
Therefore, in the above example 'podman exec' itself returns with an
exit code of 127 even though both the working directory and …
=> cmd/run: Unbreak 'enter' if the shell had exited with 127

src/cmd/create.go, src/cmd/enter.go, src/cmd/help.go, src/cmd/initContainer.go, src/cmd/list.go, src/cmd/rm.go, src/cmd/rmi.go, src/cmd/root.go, src/cmd/run.go, src/cmd/utils.go, src/meson.build, src/pkg/utils/utils.go
pkg/utils has been in Go Toolbox since its birth. Along the way it
accumulated a number of functions where a few of them are purely CLI
related. Since the majority of functions in the package are related to
some "deeper" functionality in Toolbox, it makes more sense to move the
selected few to package cmd. This will make pkg/utils a bit leaner and
create a dedicated space for cmd utility functions to live in.
In the process the error creation functions no longer require the
executableBase argument to be passed to them.
=> pkg/utils: Move cmd utility functions to cmd

src/cmd/utils.go, test/system/002-help.bats
Fixes #713
Fedora CoreOS systems do not have the man command installed. Running
toolbox --help on such a system results in a "man(1) not found" error.
As a compromise for systems without man, we added a simple help text
showing the most commonly used toolbox commands and an URL that direct
users to the Toolbox website where they can find the manuals in Markdown
format.
=> utils, help: Show basic help when "man" command is not available

src/cmd/create.go
This takes insperation from:
* https://github.com/flatpak/flatpak/blob/684e68be094d072da7740223b7cbc5d06e9550f4/common/flatpak-run.c#L359-L383
* https://github.com/containers/toolbox/pull/625
This should allow tools like `ykman` to work with yubikeys.
=> Mount Smart Card Daemon socket (pcsd) inside the toolbox container

profile.d/toolbox.sh
I would like to make the toolbox.sh welcome message appear in Fedora Kinoite as Fedora Kinoite is an official variant of Silverblue and also using toolbox.
=> Make welcome message appear on Fedora Kinoite

meson.build, src/go-build-wrapper, src/meson.build
The location for public shared libraries can change from one operating
system distribution to another. eg., while Fedora uses /usr/lib and
/usr/lib64, depending on the hardware architecture, Debian uses paths
like /usr/lib/x86_64-linux-gnu. Therefore, it's best not to assume
anything and ask the toolchain.
=> build: Don't assume that libc.so is always in /usr/lib or /usr/lib64

src/cmd/initContainer.go
When running rootless, files and directories bind mounted from the
host operating system can have their ownership listed as
`nobody:nobody`. This is because the UIDs and GIDs that actually own
those locations are not available inside the container.
Some distribution packages are particular about the file ownerships of
some of these locations. eg., Fedora's `filesystem` RPM. Encountering
`nobody:nobody` as the owner can fail package management transactions
involving such packages leading to unforeseen consequences.
Therefore, configure RPM to leave these locations alone.
=> cmd/initContainer: Avoid RPM failures due to unexpected file owners

README.md
Without capsh a toolbox might fail to be entered into with a message about not finding /bin/bash.
=> Add capsh as a container requirement in the docs

.zuul.yaml
- 33 -> 34
- 34 -> 35
F33 will EOL at the end of this month (Nov 2021)
Also motivated by wanting to find out why rawhide is failing.
=> zuul: pump the current fedora releases to 34 & 35

images/fedora/f34/extra-packages, images/fedora/f35/extra-packages, images/fedora/f36/extra-packages
Remove mlocate from the base image. mlocate being installed by default
will trigger disk wide file listing scanning updates after each dnf
operation via the updatedb process.
This is probably not wanted in most cases and especially for ephemeral
containers usage where the scanning will happen every time and thus be
very IO intensive.
=> images/fedora: Remove mlocate

src/pkg/shell/shell.go
We only need to check against `err != nil` once, not twice.
=> pkg/shell: Simplify code flow

src/cmd/initContainer.go
This will pair with a future change to `Run()` so that we capture
the child process stderr.
But actually this change on its own is enough.  Before:
`Error: failed to remove password for user walters`
After:
`Error: failed to remove password for user walters: passwd(1) not found`
which helps me immediately pinpoint the problem.
I didn't try to go through and change *all* the `Run()` invocations,
but if accepted I may do it (or someone else can).
=> initContainer: Include execution error in message

.zuul.yaml, test/system/000-setup.bats, test/system/103-container.bats, test/system/libs/helpers.bash
We need to know if the latest changes in the libc (that is dynamically
linked to the binary) causes problems in containers based on older
releases of Fedora.
The estimate of the version numbers ís very crude and does not follow
the upstream schedule. That should not be a problem.
A part of an existing test has been reused an made into a helper
function to implement this.
=> test/system: Test startup on Rawhide with supported versions

src/cmd/create.go
The Toolbox repository was moved to the 'containers' organization [some time ago](https://github.com/containers/toolbox/commit/de5e5df9b793edc746cde7125cd437b69f15ccd7) already. The label will remain supported but new containers will not be created with it.
=> cmd/create: Drop redundant label when creating a container

README.md
Now that there's a website at https://containertoolbx.org/ it makes
more sense to link to it instead of linking back to the same location
where the README.md resides.
=> README.md: Link to the website instead of the code repository

meson.build, playbooks/setup-env.yaml, src/go-build-wrapper, src/meson.build
Some downstream distributors like RHEL don't have patchelf(1). Relying
on patchelf(1) during the build will make it difficult for such
downstreams to distribute Toolbox.
Fortunately, the path of the dynamic linker (ie., PT_INTERP) is
hardcoded in the ABI specification of each architecture [1]. This means
that Toolbox's build system can keep it's own architecture to dynamic
linker mapping, and specify it during the build through the GNU ld
linker's --dynamic-linker flag, as opposed to using a tool like
patchelf(1) to change the path of the dynamic linker in the built
binary to the one inside /run/host. Currently, the list of
architectures covers the ones that Fedora builds for.
[1] https://sourceware.org/glibc/wiki/ABIList
=> build: Drop the use of patchelf(1)

doc/toolbox-create.1.md, doc/toolbox-enter.1.md, doc/toolbox-rm.1.md, doc/toolbox-rmi.1.md, doc/toolbox-run.1.md
Fedora 30 reached End of Life on 26th May 2020:
=> doc: Refer to a newer Fedora release in the examples

.zuul.yaml
Not all file are equal when it comes to testing. Unit tests are related
strictly to the source code and documentation changes do not concern it.
System tests have a wider range of influence but documentation and some
other areas also do not concern them.
I'm unsure about the effect of this change on the periodic pipeline
execution.
Split out from https://github.com/containers/toolbox/pull/918
=> zuul: Run tests only for relevant files

meson.build
In practice, this means that only Clang and GCC are accepted.
=> build: Be more strict when looking for a C compiler

.zuul.yaml
Currently, the CI has been frequently timing out on Fedora Rawhide
nodes, and it's not clear why that is. One possibility is that this is
due to Rawhide using Linux kernels that are built with debugging
enabled, which makes it slower than released Fedoras. So it might be a
matter of just increasing the timeout.
Currently, the timeout for stable Fedoras is 20 minutes, and that for
Rawhide is 22 minutes. Increase the Rawhide timeout to 30 minutes to
see if that makes the CI more stable.
=> .zuul: Try to prevent the CI from timing out on Fedora Rawhide

.zuul.yaml
Currently, the CI has been frequently timing out when running the unit
tests. It's possible that the current 5 minute timeout isn't enough,
because it's significantly lower than the 20 minute timeout on stable
Fedoras for the system tests.
Increase the timeout to 10 minutes to see if that makes the CI more
stable.
=> .zuul: Try to prevent the CI from timing out running the unit tests

.zuul.yaml
Defining the YAML anchor as part of the Rawhide tests, instead of the
Fedora 34 test, will prevent it from getting lost by mistake when
Fedora 34 reaches its End of Life.
=> .zuul: Shuffle some code around

src/pkg/utils/utils.go, test/system/libs/helpers.bash
Red Hat has published a new UBI image made specificaly for Toolbx.
Make use of it from now on.
Fixes: https://github.com/containers/toolbox/issues/961
=> pkg/utils: Use new UBI toolbox image

.github/workflows/linting.yaml
The option is mutually exclusive with the working-directory option that
we need to use due to Toolbx code residing in a subdirectory. The tool
itself does not work recursively.
Fallout from https://github.com/containers/toolbox/pull/974
https://github.com/containers/toolbox/pull/978
=> ci: Remove only-new-issues option from linter run

.github/workflows/image-factory.yaml
For the sake of greater control over the testing of images and for having an
infrustructure for hosting images that are not endorsed by the distirbutions.
=> ci: Build & Publish Fedora Toolbx images with GitHub Packages

meson.build, meson_post_install.py, playbooks/setup-env.yaml
It's only necessary to call 'systemd-tmpfiles --create' when building
and installing from source, and not when using a downstream package,
because:
* When 'meson install' is called as part of building the package,
that's not when the temporary files need to be created. They need
to be created when the package is later downloaded and installed
by the user.
* Downstream tools can sometimes handle it automatically. eg., on
Fedora, the systemd RPM installs a trigger that tells RPM to call
'systemd-tmpfiles --create' automatically when a tmpfiles.d snippet
is installed.
https://github.com/containers/toolbox/issues/955
=> build: Call 'systemd-tmpfiles --create' when installing

src/meson.build, src/meson_go_fmt.py
Gofmt returns with an exit code of 0 even when it's not happy with the
formatting of the source files. The recommendation is to check the
emptyness of the output [1].
[1] https://github.com/golang/go/issues/24230
=> build: Enforce gofmt on all Go sources

.mailmap
From now on, Harry Míchal <harrymichal@seznam.cz> will show up as
Ondřej Míchal <harrymichal@seznam.cz>.
=> Canonicalize Ondra's name

src/cmd/create.go, src/cmd/enter.go, src/cmd/run.go, src/cmd/utils.go, src/pkg/utils/utils.go, src/pkg/utils/utils_test.go, test/system/101-create.bats, test/system/104-run.bats, test/system/105-enter.bats
This change is rather big despite my efforts to keep it as small as possible. The handling needed some separation and along the way I noticed some possible problems or duplication.
Read commits for detailed information.
Fixes https://github.com/containers/toolbox/issues/937
=> More robustly handle values passed to --distro and --release

doc/toolbox-create.1.md, playbooks/setup-env.yaml, src/cmd/create.go, src/pkg/podman/podman.go, test/system/000-setup.bats, test/system/101-create.bats, test/system/999-teardown.bats, test/system/README.md, test/system/libs/helpers.bash
The option accepts a path to a file that is passed to an internal call
to 'podman pull' via the '--authfile' option. This will make it easier
to pull images from registries with authentication in-place.
The commit repurposes the test work I did for a rejected feature on
registry authentication. A registry is started locally and the use of
auth file is tested against it.
Fixes #689
Depends on: #818 & #1024
Requires a Docker registry image at quay.io/toolbox_tests/registry for running tests.
=> cmd/create: Add option --authfile

doc/toolbox-run.1.md, src/cmd/root.go, src/cmd/root_test.go, src/cmd/run.go, test/system/104-run.bats, test/system/libs/helpers.bash
When a command is executed with toolbox run and it returns a non-zero
exit code, it is just ignored if that exit code is not handled. This
prevents users to identify errors when executing commands in toolbox.
With this fix, the exit codes of the invoked command are propagated
and returned by 'toolbox run'. This includes even exit codes returned
by Podman on error.
Supersedes https://github.com/containers/toolbox/pull/867
=> cmd/run, root: Exit with exit code of invoked command

.zuul.yaml, test/system/104-run.bats
Bats 1.7.0 emits a warning if a command passed to 'run' returns with an
exit code of 127 [1].
This requires Bats >= 1.5.0, which is present in Fedora >=35, and
supports specifying the exit code as an argument to Bats' 'run'
command [2].
However, bats_require_minimum_version can't be used, because it's
only available from Bats 1.7.0, which is new enough that it's absent in
Fedora 35.
[1] Bats commit c6dc2f88361a4f5b
https://github.com/bats-core/bats-core/pull/586
https://bats-core.readthedocs.io/en/stable/warnings/BW01.html
[2] https://github.com/bats-core/bats-core/pull/367
https://github.com/bats-core/bats-core/pull/507
https://bats-core.readthedocs.io/en/stable/writing-tests.html
[3] Bats commit 71d6b71cebc3d32b
https://github.com/bats-core/bats-core/issues/556 …
=> test/system: Silence warning with Bats >= 1.7.0

.mailmap
From now on, Debarshi Ray <debarshir@gnome.org> will show up as
Debarshi Ray <rishi@fedoraproject.org>.
Toolbox isn't quite a GNOME project (it doesn't use elements from the
GNOME platform, like GLib), even though it's part of the same
ecosystem and many Toolbox contributors are also GNOME contributors.
Toolbox was conceived to improve the developer experience on Fedora
Silverblue, and expanded over time to cover other use-cases (eg.,
troubleshooting the operating system) and Fedora editions (eg., CoreOS
and Workstation).  Even though there's a growing number of users on
other distributions, they are not the primary reason for Toolbox to
exist.
Toolbox heavily depends on Podman, and as a result is more aligned with
the Containers organization on GitHub than anything else, which is
driven, …
=> .mailmap: Canonicalize my email

test/system/104-run.bats
This isn't causing any problems at the moment.  However, the test can
break if the order in which the command line arguments are validated
changes.  eg., if the presence of a command is checked before the
release, then the error message will be different.
Fallout from 8b6418d8aa6b1573a413e084e83bd1f695475406
=> test/system: Fix typo

meson.build, toolbox
This should address the confusion in https://github.com/containers/toolbox/pull/698
Also reverts [commit 8c1d4419161a1506](https://github.com/containers/toolbox/commit/8c1d4419161a15061ff7b483d1f0fbf16e809955) from https://github.com/containers/toolbox/pull/733
=> Link to the installation guide from the shell Toolbox

.zuul.yaml, playbooks/build.yaml, playbooks/dependencies.yaml, playbooks/setup-env-migration-path-for-coreos-toolbox.yaml, playbooks/setup-env.yaml
The `-Dmigration_path_for_coreos_toolbox` option enables a different code
path that's currently not tested by the CI at all.  In fact, since it's
a build-time option, the corresponding code path is not even built by
the CI.
To properly support the `-Dmigration_path_for_coreos_toolbox` option, it
needs to be covered by the CI.  This is a step in that direction by
running the unit tests on it.
=> Add builds with -Dmigration_path_for_coreos_toolbox to the CI

completion/meson.build, playbooks/setup-env-migration-path-for-coreos-toolbox.yaml, playbooks/setup-env.yaml
Otherwise, Meson complains:
completion/meson.build:4: WARNING: Project targeting '>= 0.58.0' but
tried to use feature deprecated since '0.56.0':
dependency.get_pkgconfig_variable. use
dependency.get_variable(pkgconfig : ...) instead
Fallout from bafbbe81c9220cb3749a19a244e45a61477553a6
=> build: Silence a WARNING

src/pkg/utils/utils.go
Figuring out the container name prefix for a given image only needs to
happen as part of resolving the final Toolbox container name from the
given command line and configuration options.
Fallout from c990fb43cad5f1704584f119ba4f57074c1d0bc9
=> pkg/utils: Mark a private function as such

src/cmd/utils.go, test/system/101-create.bats
Barring the first line, all other lines are terminated with a full stop
elsewhere.
=> cmd/utils, test/system: Tweak an error message for consistency

src/cmd/create.go, src/cmd/enter.go, src/cmd/rootMigrationPath.go, src/cmd/run.go, src/cmd/utils.go, src/pkg/utils/utils.go, src/pkg/utils/utils_test.go, test/system/101-create.bats, test/system/104-run.bats, test/system/105-enter.bats
This reverts https://github.com/containers/toolbox/pull/977 to address the problems with it with the intention to fix the first part of https://github.com/containers/toolbox/issues/937
https://github.com/containers/toolbox/issues/937 points out several problems.  This pull request only attempts to ensure that Toolbx errors out when the user specifies an invalid `distro`, instead of falling back to Fedora.  It doesn't try to improve the error reporting for a missing or invalid `release`.
=> Re-unify container & image name resolution and ensure that the 'distro' CLI and config file options are valid

src/cmd/create.go, src/cmd/enter.go, src/cmd/rootMigrationPath.go, src/cmd/run.go, src/cmd/utils.go, src/pkg/utils/utils.go, src/pkg/utils/utils_test.go, test/system/101-create.bats, test/system/104-run.bats, test/system/105-enter.bats
This builds on top of https://github.com/containers/toolbox/pull/1080  It intends to fix the third part of https://github.com/containers/toolbox/issues/937 by clarifying the error message if `--release` has an invalid argument.
=> Clarify the error message if the release is invalid

src/cmd/create.go, src/cmd/enter.go, src/cmd/rootMigrationPath.go, src/cmd/run.go, src/cmd/utils.go, src/meson.build, src/pkg/utils/errors.go, src/pkg/utils/utils.go, src/pkg/utils/utils_test.go, test/system/101-create.bats
Currently, the container name and release are only validated if they
were specified as command line options.  Neither the value of release
in the configuration file nor the container name generated from an
image are validated.
There's also a lot of repeated code in the command front-ends to
validate the container name and release.  This opens the door for
mistakes.  Any adjustment to the code must be repeated elsewhere, and
there are subtle interactions and overlaps between the validation code
and the code to resolve container and image names.
It's worth noting that the container and image name resolution happens
for both the command line and configuration file options, and generates
the container name from the image when necessary.
Therefore, validating everything while resolving cleans …
=> Increase the validation coverage for the container & release options

src/cmd/utils.go, src/pkg/utils/errors.go, src/pkg/utils/utils.go, test/system/101-create.bats, test/system/104-run.bats, test/system/105-enter.bats
This improves the error messages related to `--distro` to address the second point of https://github.com/containers/toolbox/issues/937
=> cmd/utils, pkg/utils: Improve the error messages for the distro option

doc/toolbox-create.1.md
When describing the --authfile option, the word "private" is used to refer to images needing authentication.  Using the same word shortens the text so that the word "custom" can be used in the same way as in the other examples.
=> doc/toolbox-create: Tweak an example for consistency

src/cmd/create.go, src/cmd/enter.go, src/cmd/root.go, src/cmd/run.go
While the use of Logrus is convenient, it causes unneeded fluff to be printed during a panic which distracts from finding the cause of the panic in the first place.
Fallout from d69ce6794b08972592b8528613e0dcbcbda6d5f8
Split out from https://github.com/containers/toolbox/pull/1055
=> cmd: Don't use Logrus to call panic

src/cmd/completion.go
We don't provide completion for PowerShell, we support only Linux and instructions for loading completion files are redundant in Toolbx.
Fallout from d69ce6794b08972592b8528613e0dcbcbda6d5f8
Split out from https://github.com/containers/toolbox/pull/1055
=> cmd/completion: Remove unneeded documentation

completion/meson.build, src/meson.build
By default, the value of the `build_by_default` argument is determined
by the value of the `install` argument, which has been set to `true`
ever since the Go implementation was considered stable enough for end
users.
Fallout from 0b3c66434e8e4bf138d902d115b87d0dbfac16df
=> build: Remove redundant build_by_default

src/go-build-wrapper, src/meson.build
Note that Meson's '@OUTPUT@' is not just the basename of the output, but
includes the relative path under the project's root directory.
=> build: Wire go-build-wrapper's output to Meson's

completion/meson.build
Fallout from bafbbe81c9220cb3749a19a244e45a61477553a6
Split from https://github.com/containers/toolbox/pull/1055
=> build: Fix typo in install dir for ZSH completions

src/cmd/completion.go
Bash completion v2 was introduced in Cobra v1.2.0 and v1 will be deprecated in the future:
https://github.com/spf13/cobra/releases/tag/v1.2.0
Since Toolbox already requires Cobra >= v1.3.0, it's better to use the new Bash completion.
Fallout from d69ce6794b08972592b8528613e0dcbcbda6d5f8
Split from https://github.com/containers/toolbox/pull/1055
=> cmd/completion: Use Cobra's Bash completion v2

completion/generate_completions.py, src/cmd/completion.go
Cobra provides a default command 'completion' that is always visible. The reverted change caused an additional command 'completion' to show up in the list because the then called command '__completion' didn't override the default one. This became apparent due to d69ce6794b089725 dynamically generating completion arguments for the 'help' command.
This reverts commit 4469774fb1986252aa9660892dba33c9447420ec.
Split from https://github.com/containers/toolbox/pull/1055
=> Revert "cmd/completion: Add prefix to command to hide it better"

completion/generate_completions.py, meson_post_install.py, src/meson_go_fmt.py
In short, it's a lot of effort to cover all possible exceptions that can
be thrown, and things work reasonably well even without handling them.
Since this is just part of the build, there's no point in complicating
things for aesthetic reasons.
More details in the commits.
=> build: Don't try to handle exceptions when spawning subprocesses

images/fedora/f35/extra-packages, images/fedora/f36/extra-packages, images/fedora/f37/extra-packages
The following packages have been added to the
image to make OpenGL and Vulkan work:
mesa-dri-drivers
mesa-vulkan-drivers
vulkan-loader
https://github.com/containers/toolbox/issues/1110
=> Added new packages

images/fedora/f38/extra-packages
The following packages have also been added to Fedora 38 image: mesa-dri-drivers
mesa-vulkan-drivers
vulkan-loader
Fixing up fedora 38 image to match the changes made earlier on fedora 37.
Signed-off-by: Nieves Montero <nmontero@redhat.com>
=> Add new packages to Fedora 38

images/fedora/f36/missing-docs, images/fedora/f37/missing-docs, images/fedora/f38/missing-docs
This pull request is based on the following one https://github.com/containers/toolbox/pull/1068
=> Add findutils and sudo to missing docs for images f36, f37 and f38

images/fedora/f37/Containerfile, images/fedora/f37/extra-packages, images/fedora/f38/Containerfile, images/fedora/f38/extra-packages
The following lines have been added to the fedora 37 and 38 images: RUN dnf -y swap glibc-minimal-langpack glibc-all-langpacks RUN rm /etc/rom/macros.image-language.conf
These two lines avoid redundant packages inside the images.
https://github.com/containers/toolbox/issues/1136
https://github.com/containers/toolbox/issues/1137
Signed-off-by: Nieves Montero <nmontero@redhat.com>
=> Add corrections to avoid duplicate packages

completion/meson.build, meson.build, meson_options.txt
The `bash-completion` and `fish` dependencies were already optional - the shell completions for Bash and fish won't be generated and installed if they are absent; and there's no dependency required for Z shell.  So the `install_completions` build option wasn't reducing the dependency burden.
The build option was a way to disable the generation and installation of the shell completions, regardless of whether the necessary dependencies are present or not.  The only use-case for this is when installing to a non-system-wide prefix while hacking on Toolbox as a non-root user, because the locations for the completions advertised by the shells' APIs might not be accessible.  Being able to disable the completions prevents the installation from failing.
A different way of ensuring a smooth …
=> build: Enable changing the completion paths & drop install_completions

completion/meson.build, meson.build, meson_options.txt, meson_post_install.py
If `systemd-tmpfiles --create` is called as a non-root user, then it causes:
```
--- stdout ---
Calling systemd-tmpfiles --create ...
--- stderr ---
Failed to open directory 'cryptsetup': Permission denied
Failed to open directory 'certs': Permission denied
Failed to create directory or subvolume "/var/spool/cups/tmp":
Permission denied
...
...
...
Traceback (most recent call last):
File "toolbox/meson_post_install.py", line 26, in <module>
subprocess.run(['systemd-tmpfiles', '--create'], check=True)
File "/usr/lib64/python3.10/subprocess.py", line 524, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['systemd-tmpfiles',
'--create']' returned non-zero exit status 73.
```
Since, `systemd-tmpfiles(8)` can't be used like this as a non-root user, …
=> build: Skip a needless failure when running systemd-tmpfiles  as non-root

data/config/meson.build, doc/meson.build, meson.build, playbooks/build.yaml, playbooks/setup-env.yaml, playbooks/unit-test.yaml
... at https://containertoolbx.org/install/
There are some minor benefits to always invoking `meson(1)`, as opposed to directly invoking the underlying build backend, like `ninja`.
It's one less command to be aware of.  Secondly, in theory, Meson can be used with backends other than Ninja (see `meson configure`), even though Ninja is the most likely option for building Toolbx because it's only supported on Linux.
=> playbooks: Use the same commands as mentioned in the documentation

data/config/meson.build, doc/meson.build, doc/toolbox-run.1.md, meson.build, playbooks/build.yaml, playbooks/setup-env.yaml, playbooks/unit-test.yaml
... with the toolbox-create(1) and toolbox-enter(1) manuals.
Fallout from ffd365342eefd3faae8737f02cf83407399ea000
=> doc/toolbox-run: Tweak the wording for consistency

src/cmd/list.go, src/cmd/run.go, src/go.mod
It was decided in commit 950f510872404da8 that golang.org/x/* would be used for the IsTerminal() API, not github.com/mattn/go-isatty.  However, github.com/mattn/go-isatty had crept in through commits f49df914f4b64fed and a22d7821cb8cea13.
The size savings seem to have been lost, because with Go 1.18.6, the binary size actually grew from 9410616 bytes to 9410912.  However, it seems better to stick to packages from the golang.org domain, whenever possible.
=> cmd/list, cmd/run: Consolidate the dependencies for the IsTerminal() API

src/cmd/list.go, src/cmd/run.go, src/go.mod, test/system/104-run.bats
Using 'true' is likely going to be quicker than launching the entire shell (ie., `/bin/sh`).
Note that 'toolbox run' already invokes a wrapper shell via capsh(1) before invoking the user-specified command.  So, this was the second instance of a shell.
=> test/system: Tweak

src/cmd/run.go, test/system/104-run.bats
For the most part, this fixes a minor cosmetic issue for users, but it does make the code less misleading to read for those hacking on Toolbx. Further details below.
Commands are invoked inside a Toolbx from a helper shell invoked by `capsh(1)`.  Unless `capsh(1)` is built with custom options, the helper shell is always `bash`, not `/bin/sh`:
```
$ capsh --caps="" -- -c 'echo "$(readlink /proc/$$/exe)"'
/usr/bin/bash
```
( The possibility of capsh(1) using a different shell, other than Bash,
through a custom build option is ignored for the time being.  If there
really are downstream distributors who do that, then this can be
addressed one way or another. )
Secondly, the name assigned to the embedded command string's `$0` should only be the basename of the helper shell's binary, not the …
=> cmd/run: Fix the name of the shell for running commands in containers

src/cmd/run.go, test/system/104-run.bats
Currently, commands invoked using `toolbox run` have a different environment than the interactive environment offered by `toolbox enter`. This is because 'toolbox run' was invoking the commands using something like this:
```
$ bash -c 'exec "$@"' bash [COMMAND]
```
... whereas, `toolbox enter` was using something like this:
```
$ bash -c 'exec "$@"' bash bash --login
```
In the first case, the helper Bash shell is a non-interactive non-login shell.  This means that it doesn't read any of the usual start-up files, and, hence, it doesn't pick up anything that's specified in them.  It runs with the default environment variables set up by Podman and the Toolbx image, plus the environment variables set by Toolbx itself.
In the second case, even though the helper Bash shell is still the same as …
=> cmd/run: Ensure that 'run' has the same container environment  as 'enter'

test/system/104-run.bats
It seems that as new test cases got developed they got appended towards the end of the file.  Now that there are a non-trivial number of test cases, it's difficult to look at the file and get a gist of all the scenarios being tested.
It will be better to have some logical grouping -- starting with the most basic functionality, then moving on to more advanced features, and then finally the errors.
This a step towards that.
=> test/system: Group the test cases somewhat logically

test/system/104-run.bats
This needs a directory that's going to be present on the host operating system across various configurations of all supported distributions, such as the hosts running the CI, but not inside the Toolbx containers.
It looks like `/etc/kernel` is present on both Debian and Fedora, but absent from the fedora-toolbox images.  On a Debian 10 server, it's owned by several packages:
```
$ dpkg-query --search /etc/kernel
dkms, systemd, grub2-common, initramfs-tools, apt: /etc/kernel
```
... while on Fedora 36 Workstation:
```
$ rpm --file --query /etc/kernel
systemd-udev-250.8-1.fc36.x86_64
```
Currently, there's no way to get `assert_line` to use the `stderr_lines` array [1].  This is worked around by assigning `stderr_lines` to the `lines` array.
[1] …
=> test/system: Ensure that $HOME is used as a fallback working directory

src/cmd/run.go
Here's some historical context to understand what's going on.
In the past, before commit a22d7821cb8cea13, Podman's standard error stream was only revealed when `--verbose` was used.
During that time, the standard error and output streams of the process running inside the Toolbx container, but not `podman exec ...` itself, were merged into the standard output stream read and revealed by the Toolbx binary.
Then commit a22d7821cb8cea13 ensured that a nested pseudo-terminal device is only created for the process running inside the container, if the Toolbx binary's standard input and output streams are connected to a terminal.  This meant that the standard error stream of the container process stayed separate from the standard output stream received by the Toolbx binary, when terminal devices …
=> cmd/run: Suppress errors from Podman when interactive and not verbose

test/system/104-run.bats
Commit a22d7821cb8cea13 ensured that a nested pseudo-terminal device is only created for the process running inside the container, if the Toolbx binary's standard input and output streams are connected to a terminal.
Therefore, 'echo ...' no longer ends with an unwanted extra carriage return when terminal devices are absent - there's only a line feed for the trailing newline.  Hence, there's no need to use the -n flag to skip the trailing newline.
This reverts parts of commit 16b0c5d88fcc404d52c6e37a7f46bd430b352369.
https://github.com/containers/toolbox/issues/157
=> test/system: Remove workaround for carriage return without a terminal

playbooks/dependencies.yaml, playbooks/setup-env-migration-path-for-coreos-toolbox.yaml, playbooks/setup-env.yaml, playbooks/system-test.yaml, playbooks/unit-test.yaml
Currently, `meson compile` and `meson install` were being invoked from pre-run playbooks.  This meant that a genuine build failure from either of those commands would be shown as a `RETRY_LIMIT` failure by the CI.
This was misleading.  It made it look as if the failure was caused by some transient networking problem or that the CI node was too slow due to momentary heavy load, whereas the failure was actually due to a problem in the Toolbx sources.  A genuine problem in the sources should be reflected as a `FAILURE`, not `RETRY_LIMIT`.
However, it's worth noting that `meson compile` invokes `go build`, which downloads all the Go modules required by the Toolbx sources.  This is worth retaining in the pre-run playbooks since it primarily depends on Internet infrastructure beyond the Toolbx …
=> playbooks: Highlight failures from 'meson compile' and 'meson install'

test/system/104-run.bats
Currently, there's no way to get assert_line to use the stderr_lines array [1].  This is worked around by assigning stderr_lines to the 'lines' array.
[1] https://github.com/bats-core/bats-assert/issues/42
=> test/system: Ensure that error messages go to the standard error stream

test/system/104-run.bats
The long options are easier to `grep(1)` for in the sources than their shorter aliases.
=> test/system: Use long options, instead of their shorter aliases

src/cmd/create.go
Fallout from e935ed893d5b72ac9f08987bc2c7ede9f7d506cc
=> cmd/create: Fix typo

.zuul.yaml
On a couple of occasions the relevant tests didn't get triggered because some files weren't listed [1], and on another a commit forgot to update the list of files.
The objective of the CI is to reduce stress for the maintainers, and make it easy for contributors to find out if their changes work or not. Missing tests don't help with that, and there's no need to optimize the tests like this unless there's a real problem to be solved.
[1] Commit deca452b273378e5
Commit 5c27d730212312d6
[2] Commit b1743c492708826c
This reverts commit c28d902089467884a31de276ec9c8dbb0ef76fa8.
=> Revert ".zuul: Run tests only for relevant files"

playbooks/dependencies.yaml
... because it was replaced by `crun(1)` as Podman's default OCI runtime
during the migration to cgroups v2 in Fedora 31 [1].  eg., on Fedora 36:
```
...
containerd-0:1.6.1-1.fc36.x86_64
containerd-0:1.6.9-3.fc36.x86_64
containers-common-4:1-53.fc36.noarch
containers-common-extra-4:1-62.fc36.noarch
moby-engine-0:20.10.12-3.fc36.x86_64
moby-engine-0:20.10.20-1.fc36.x86_64
```
... and it doesn't get installed on Fedora 35 either:
```
TASK [Check versions of crucial packages]
ci-node-35 | glibc-gconv-extra-2.34-43.fc35.x86_64
ci-node-35 | glibc-2.34-43.fc35.x86_64
ci-node-35 | glibc-common-2.34-43.fc35.x86_64
ci-node-35 | glibc-langpack-en-2.34-43.fc35.x86_64
ci-node-35 | kernel-core-6.0.5-100.fc35.x86_64
ci-node-35 | kernel-core-6.0.7-100.fc35.x86_64
ci-node-35 | …
```
=> playbooks: Don't worry about runc(8)

.codespellexcludefile, meson.build, playbooks/dependencies.yaml
The [documentation](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/package_module.html) for Ansible's built-in 'package' module says this about the `use` parameter:
```
You should only use this field if the automatic selection is not
working for some reason.
```
=> playbooks: Remove unnecessary parameter

profile.d/toolbox.sh
Commit dcdfa3a1f5a34213 ensured that the rest of the `os-release(5)` fields don't get injected into the shell as environment variables, but missed ID and VARIANT_ID.
Fallout from c6e37cdef37e2276207b34a42919f1e0ac4a04dc
=> profile.d: Don't leak ID and VARIANT_ID into the shell

README.md
Using the word *containerized* gives the false impression of heightened security.  As if it's a mechanism to run untrusted software in a sandboxed environment without access to the user's private data (such as `$HOME`), hardware peripherals (such as cameras and microphones), etc.. That's not what Toolbx is for.
Toolbx aims to offer an interactive command line environment for development and troubleshooting the host operating system, without having to install software on the host.  That's all.  It makes no promise about security beyond what's already available on the usual command line environment on the host that everybody is familiar with.
https://github.com/containers/toolbox/issues/1020
=> README.md: Clarify that Toolbx isn't a security mechanism

src/meson.build
Currently, only a so-called high-confidence subset of the default checks in `go vet` are being run by `go test` [1].  Since `go vet` is part of the core Go tools, it's worth trying to use more of it.  After all, golangci-lint, which is currently being run through a GitHub Action, is running the default `go vet` checks as one of its linters [2].
It's good to have as much of the testing wrapped inside `meson test`, as possible, because it's easier to run locally and on other non-GitHub CI environments like those of downstream distributors.
[1] https://pkg.go.dev/cmd/go/internal/test
[2] https://golangci-lint.run/usage/linters/
https://golangci-lint.run/usage/linters/#govet
=> build: Enforce all the default 'go vet' checks on all Go  sources

src/cmd/list.go
Fallout from 2369da5d31830e5cd3e1a13857a686365875ae61
=> cmd/list: Remove redundant initializations

test/system/libs/helpers.bash
This was making it difficult to read the Bats assertions on test failures, by polluting it with unexpected and irrelevant output from `podman images`.  For example [1]:
```
not ok 39 list: Images with and without names in 12332ms
#
#
```
Fallout from 7973181136494a4ba147808c9ad51ace9aa4305f
[1] https://github.com/containers/toolbox/pull/1192
=> test/system: Remove stray (possibly for debugging) 'podman images'

.zuul.yaml, src/cmd/completion.go, src/cmd/list.go, src/cmd/rmi.go, src/pkg/podman/podman.go, test/system/102-list.bats, test/system/107-rmi.bats, test/system/libs/helpers.bash
This PR should fix #1043.
It makes `toolbox list` behave in the same way as `podman images`
```
[test@fedora build]$ podman images 
REPOSITORY                                                       TAG         IMAGE ID      CREATED      SIZE
registry.access.redhat.com/ubi9/toolbox                          latest      c24104d7b237  2 weeks ago  596 MB
<INTERNAL_URL>/toolbox-container                             9.0.0-9     c24104d7b237  2 weeks ago  596 MB
[test@fedora build]$ toolbox list 
IMAGE ID      IMAGE NAME                                                               CREATED
c24104d7b237  registry.access.redhat.com/ubi9/toolbox:latest                           2 weeks ago
c24104d7b237  <INTERNAL_URL>/toolbox-container:9.0.0-9                            2 weeks ago
```
As mentioned …
=> Make toolbox list behave in the same way podman images does

.zuul.yaml
The 'unit tests' are no longer just unit tests.  They also run a bunch of static analysis tools like ShellCheck, codespell, gofmt and 'go vet'. Since newer versions of these tools are generally better at catching problems in the codebase, it will be better to run the 'unit tests' on Fedora Rawhide with the latest versions than older stable Fedoras.
The timeout for the 'unit tests' need to be increased because Fedora Rawhide is slower than stable Fedoras.  Currently, the timeout for the 'unit tests' running on Fedora 36 is 10 minutes.  Increasing it to 20 minutes when running on Fedora Rawhide wasn't enough, so maybe 30 will be sufficient.
Note that this is only feasible because the Fedora Rawhide builds are now more robust against stale DNF caches [1].  Otherwise, it wouldn't have been …
=> .zuul: Use the latest version of the tools for static analysis

toolbox
Fedora Rawhide now has ShellCheck-0.9.0, which flags these new problems, while so far it only had ShellCheck-0.8.0.
=> Silence ShellCheck-0.9.0

doc/toolbox-create.1.md, doc/toolbox-enter.1.md, doc/toolbox-help.1.md, doc/toolbox-init-container.1.md, doc/toolbox-list.1.md, doc/toolbox-rm.1.md, doc/toolbox-rmi.1.md, doc/toolbox-run.1.md, doc/toolbox.1.md, doc/toolbox.conf.5.md, test/system/002-help.bats
Currently, the titles of the manuals are rendered with a pair of empty parentheses and no section title:
```
toolbox(1)()                                              toolbox(1)()
NAME
toolbox - Tool for containerized command line environments...
```
However, they should be:
```
toolbox(1)             General Commands Manual              toolbox(1)
NAME
toolbox - Tool for containerized command line environments...
```
This is because the troff generated by go-md2man from Markdown has a faulty invocation of the `.TH` macro [1]:
```
.nh
.TH toolbox(1)
.SH NAME
.PP
toolbox - Tool for containerized command line environments on Linux
```
It should be:
```
.nh
.TH toolbox 1
.SH NAME
.PP
toolbox - Tool for containerized command line environments on Linux
```
Original patch from Andrew Denton for …
=> doc: Fix the titles of the manuals

.zuul.yaml
Currently, the CI has been timing out on Fedora 36 nodes [1].  It's possible that this is due to the recent expansion of the test suite, which already required increasing the timeout for Fedora Rawhide [2].
[1] https://github.com/containers/toolbox/pull/1191
https://github.com/containers/toolbox/pull/1208
[2] Commit e8f4e9c3671ee31c
https://github.com/containers/toolbox/pull/1195
=> .zuul: Try to prevent the CI from timing out on stable Fedoras

playbooks/dependencies-centos-9-stream.yaml, playbooks/dependencies-fedora.yaml
Building Toolbx requires a C compiler [1], which defaults to GCC on Fedora and CentOS Stream.  It's good to explicitly require it, so that it doesn't go missing from the build.
Showing the version of the C compiler is a big help when debugging weird build problems involving the toolchain.  A following commit will use CGO to link to libsubid.so, which will only increase the relevance of the C compiler.
[1] Commit c8aaed52c547e24e
https://github.com/containers/toolbox/pull/923
=> playbooks: Require GCC and show its version

meson.build, playbooks/dependencies-centos-9-stream.yaml, playbooks/dependencies-fedora.yaml, src/cmd/root.go, src/meson.build, src/pkg/utils/libsubid-wrappers.c, src/pkg/utils/libsubid-wrappers.h, src/pkg/utils/utils_cgo.go
On enterprise FreeIPA set-ups, the subordinate user and group IDs are provided by SSSD's sss plugin for the GNU Name Service Switch (or NSS) functionality of the GNU C Library.  They are not listed in /etc/subuid and /etc/subgid.  Therefore, its necessary to use libsubid.so to check the subordinate ID ranges.
The CGO interaction with libsubid.so is loosely based on 'readSubid' in github.com/containers/storage/pkg/idtools [1].
However, unlike 'readSubid', this code considers the absence of any range (ie., nRanges == 0) to be an error as well.
More importantly, this code uses dlopen(3) and friends to dynamically load the symbols from libsubid.so, instead of linking to libsubid.so at build-time and having the dependency noted in the /usr/bin/toolbox binary.  This is done because libsubid.so …
=> Support subordinate user and group ID ranges on enterprise set-ups

src/cmd/run.go
Go's encoding/json package parses all JSON numbers as float64 [1].  This oddity was noticed when this code was first written [2], and was later confirmed.
[1] https://pkg.go.dev/encoding/json#Unmarshal
[2] Commit cf5c58ab00223cee
https://github.com/containers/podman/issues/6105
=> cmd/run: Remove unused code

images/fedora/f36/Containerfile, images/fedora/f36/ensure-files, images/fedora/f36/missing-docs, images/fedora/f37/Containerfile, images/fedora/f37/ensure-files, images/fedora/f37/missing-docs, images/fedora/f38/Containerfile, images/fedora/f38/ensure-files, images/fedora/f38/missing-docs
... and add the manuals for `cat(1)`, `cp(1)`, `ls(1)`, etc. to the list.
Only the images for currently maintained Fedoras (ie., 36, 37 and 38) were updated.
=> images: Ensure that the desired manuals are indeed present

images/fedora/f36/ensure-files, images/fedora/f36/missing-docs, images/fedora/f37/ensure-files, images/fedora/f37/missing-docs, images/fedora/f38/ensure-files, images/fedora/f38/missing-docs
Note that in the past, it was observed that the util-linux package was no longer part of the fedora base images starting from Fedora 35 [1], and indeed it wasn't [2].  However, later the util-linux-core subset was restored from Fedora 36 onwards [3].  Hence, the need to restore the util-linux-core documentation that was stripped out in the base image.
Only the images for currently maintained Fedoras (ie., 36, 37 and 38) were updated.
Original patch from Jens Petersen for Fedora [4].
[1] Commit df05e276b219aef4
https://github.com/containers/toolbox/issues/929
[2] fedora-kickstarts commit 1f3645b72d46a0a7
https://pagure.io/fedora-kickstarts/c/1f3645b72d46a0a7
https://bugzilla.redhat.com/show_bug.cgi?id=1951111
[3] fedora-kickstarts commit 4477181faf75e105 …
=> images: Ensure that the kill(1), mount(8), etc. manuals are available

images/fedora/f36/README.md, images/fedora/f37/README.md, images/fedora/f38/README.md
The canonical copy of README.md contains banners and labels in the header that aren't useful when the file is shipped as part of the images.  Hence, those were removed.
Only the images for currently maintained Fedoras (ie., 36, 37 and 38) were updated.
=> images: Synchronize README.md

src/cmd/initContainer.go
These two commits adds two new bind mounts to newly created toolboxes.
The first one binds `/run/systemd/sessions`, so that systemd calls such as `sd_session_get_seat()` works.
The second one binds `/run/udev/tags`. This makes it possible to run device enumerators that matches against some tag. Here is an example that would now work:
```c
/* gcc -o udev-enumerate `pkg-config --cflags libudev --libs libudev` udev-enumerate.c */
#include <libudev.h>
#include <stdio.h>
int
main(int argc, char **argv)
{
struct udev *udev;
struct udev_enumerate *e;
struct udev_list_entry *entry;
udev = udev_new();
e = udev_enumerate_new(udev);
udev_enumerate_add_match_subsystem(e, "drm");
udev_enumerate_add_match_tag(e, "seat");
udev_enumerate_scan_devices(e);
udev_list_entry_foreach(entry, …
```
=> Add two bind mounts needed by display servers

src/cmd/create.go
Podman creates a cgroup namespace for cgroups v2 by default. The host
cgroupfs is mounted at /sys/fs/cgroup giving an inconsistent view of the
cgroups. There is no need for a cgroup namespace with toolbox so just
use the host namespace.
=> cmd/create: use the host cgroup namespace

src/cmd/initContainer.go
Required for systemd --user to realize the system was booted with
systemd.
=> cmd/initContainer: Bind mount /run/systemd/system

src/cmd/initContainer.go
Just like /run/systemd/sessions makes it possible to get the seat for a session ID, /run/systemd/users can make it possible to get the seat and the session ID for a user's UID.
The absence of /run/systemd/users inside Toolbx containers isn't currently causing problems for any use-case, but it seems very close to the sort of things that were necessary to run a non-nested display server from within a Toolbx container on a virtual terminal.  It's not impossible that in future some implementation details of the display server stack may make /run/systemd/users necessary.
https://github.com/containers/toolbox/issues/992
=> cmd/initContainer: Give access to /run/systemd/users from the host

src/pkg/utils/utils.go
Fedora 34 reached End of Life on 7th June 2022:
=> pkg/utils: Update fallback release to 37 for non-fedora hosts

meson.build, src/cmd/root.go
Ever since commit bafbbe81c9220cb3, the shell completions are generated while building Toolbx using the 'completion' command.  This involves running toolbox(1) itself, and hence invoking 'podman version' to decide if 'podman system migrate' is needed or not.
Unfortunately, some build environments, like Fedora's, are set up inside a chroot(2) or systemd-nspawn(1) or similar, where 'podman version' may not work because it does various things with namespaces(7) and clone(2) that can, under certain circumstances, encounter an EPERM.
Therefore, it's better to avoid using podman(1) when generating the shell completions, especially, since they are generated by Cobra itself and podman(1) is not involved at all.
Note that podman(1) is needed when the generated shell completions are actually used …
=> cmd/root: Don't use podman(1) when generating the completions

.zuul.yaml, playbooks/dependencies-fedora-restricted.yaml, playbooks/setup-env-restricted.yaml, src/cmd/root.go
Ever since commit bafbbe81c9220cb3, the shell completions are generated
while building Toolbx using the 'completion' command.  This involves
running toolbox(1) itself, and hence validating the subordinate user and
group ID ranges.
Unfortunately, some build environments don't have subordinate ID ranges
set up.  Therefore, it's better to avoid validating them when generating
the shell completions, especially, since they are generated by Cobra
itself and subordinate ID ranges are not involved at all.
Note that subordinate ID ranges may be needed when the generated shell
completions are actually used in interactive command line environments.
The shell completions invoke the hidden '__complete' command to get the
results that are presented to the user, and, if needed, the subordinate
ID ranges …
=> cmd/root: Don't validate subordinate IDs when generating the completions

src/cmd/create.go, src/cmd/run.go
So far the minimum required Podman version was 1.4.0, based on what used to be available in RHEL 7.  These days, Podman 1.6.4 is old enough to be in RHEL 7.9.  Hence it's time to bump the baseline.
=> cmd/create, cmd/run: Rely on podman >= 1.6.4 always being present

src/cmd/initContainer.go
Bind mounting the locations at runtime doesn't really have anything to do with whether /run/host/etc is present inside the Toolbx container.
The only possible exception could have been /etc/machine-id, but it isn't, because the bind mount is only performed if the source at /run/host/etc/machine-id is present.
This is a historical mistake that has persisted for a long time, since, in practice, /run/host/etc will almost always exist inside the Toolbx container.  It's time to finally correct it.
Fallout from 9436bbece01d7aa4dc91b4013ed9f80d0b8d34f4
=> cmd/initContainer: Bind mount locations regardless of /run/host/etc

src/cmd/create.go
Fallout from 8e80dd5db1e6f40b827a564c16823fd0dad083f0
=> cmd/create: Simplify code

meson.build, playbooks/dependencies-centos-9-stream.yaml, playbooks/dependencies-fedora-restricted.yaml, playbooks/dependencies-fedora.yaml, src/cmd/create.go, src/meson.build, src/pkg/skopeo/skopeo.go
https://github.com/containers/toolbox/issues/752
Signed-off-by: Nieves Montero <nmontero@redhat.com>
=> Report pulled image size

src/pkg/utils/utils_test.go
Fallout from b5474bff84179c746e30c07255f8d7de9dcd4b14
=> pkg/utils: Simplify the definition of parseRelease() unit test cases

.github/CODEOWNERS
Toolbx was conceived to address the needs of Fedora Linux.  Even though it works on host operating systems outside the Fedora family, it hasn't treated them with the same importance as Fedora Linux and derivatives like Red Hat Enterprise Linux.  Subsequent commits will change that by adding first-class support for host operating systems beyond the Fedora universe.  eg., Arch Linux and Ubuntu.
The current Toolbx maintainers, Ondřej Míchal and myself, are Fedora developers and don't have the bandwidth to drive changes and track down bugs in OSes outside the Fedora family.  Therefore, maintenance of some parts of the code base will be delegated to contributors from those other OS communities.
This is a step in that direction by clearly specifying which part of the code base is maintained by …
=> .github: Add CODEOWNERS

test/system/101-create.bats, test/system/107-rmi.bats
Currently, some of the names of the tests were too long, and had inconsistent and verbose wording.  This made it difficult to look at them and get a gist of all the scenarios being tested.  The names are like headings.  They shouldn't be too long, should capture the primary objective of the test and be consistent in their wording.
=> test/system: Shorten the names of the tests and use consistent wording

src/cmd/utils.go
fmt.Scanf [1] is fragile when it comes to space-separated input.  It stores successive space-separated values into successive arguments as determined by the format string.  This breaks with untrusted input that can have an unknown number of space-separated values.
Here are some examples:
```
$ toolbox create
Image required to create toolbox container.
Download registry.fedoraproject.org/fedora-toolbox:39 (294.8MB)?
[y/N]: no no not at all
$ no not at all
bash: no: command not found...
$ toolbox create
Image required to create toolbox container.
Download registry.fedoraproject.org/fedora-toolbox:39 (294.8MB)?
[y/N]: foo bar
Download registry.fedoraproject.org/fedora-toolbox:39 (294.8MB)?
[y/N]: Download registry.fedoraproject.org/fedora-toolbox:39
(294.8MB)? [y/N]:
```
Instead this is what …
=> cmd/utils: Handle space-separated input when asking for confirmation

images/ubuntu/16.04/Containerfile, images/ubuntu/16.04/extra-packages, images/ubuntu/18.04/Containerfile, images/ubuntu/18.04/extra-packages, images/ubuntu/20.04/Containerfile, images/ubuntu/20.04/extra-packages, images/ubuntu/22.04/Containerfile, images/ubuntu/22.04/extra-packages, images/ubuntu/22.10/Containerfile, images/ubuntu/22.10/extra-packages, src/pkg/utils/utils.go, src/pkg/utils/utils_test.go, test/system/000-setup.bats, test/system/101-create.bats, test/system/102-list.bats, test/system/104-run.bats, test/system/libs/helpers.bash
For the full discussion, see: https://github.com/containers/toolbox/pull/483
This is meant to land the first two patches from the [original](https://github.com/containers/toolbox/pull/483) pull request that:
* Allows using the `--distro` and `--release` options to create and enter Ubuntu containers
* Adds the ubuntu-toolbox image definitions
This doesn't include the details of publishing the images to `quay.io/toolbx-images`.  Follow the [original](https://github.com/containers/toolbox/pull/483) pull request for further updates on that.
=> Offer built-in support for Ubuntu and ubuntu-toolbox image definitions

.github/CODEOWNERS
... to be at the root of the repository.  Without the leading slash, the documentation suggests that it could be a data/gfx directory anywhere in the repository [1].
[1] https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
Fallout from 3773ceb0c557b59415a92828839b477cbf35ca97
=> .github/CODEOWNERS: Clarify the location of the data/gfx directory

.github/CODEOWNERS
This partly reflects the value of the 'maintainer' LABELs of the current images.  Oliver is the original author, but he has lots of other duties these days, and wanted me to help him co-maintain the images.
Note that the toolbox image definitions for RHEL do need a maintainer who is a Red Hat employee.  Otherwise they won't be able to actually build and publish the images at registry.access.redhat.com.
=> .github/CODEOWNERS: Clarify ownership of the images for RHEL

images/ubuntu/16.04/Containerfile, images/ubuntu/18.04/Containerfile, images/ubuntu/20.04/Containerfile, images/ubuntu/20.04/extra-packages, images/ubuntu/22.04/Containerfile, images/ubuntu/22.04/extra-packages, images/ubuntu/22.10/Containerfile, images/ubuntu/22.10/extra-packages
* images: ubuntu: Move flatpak-xdg-utils installation to Containerfile
Since `flatpak-xdg-utils` is essential to images, not 'extra'.
* images: ubuntu: Remove APT ESM hook
This was recently introduced with `ubuntu-advantage-tools` and it tries to poke at some system services introducing annoying delay and messages.
Even if the services are present (on Ubuntu host) and systemd is accessible (rootful container) - that wouldn't be appropriate still.
=> Ubuntu image improvements

images/ubuntu/23.04/Containerfile, images/ubuntu/23.04/extra-packages
Which is the next non-LTS to be released on Apr 20th 2023 (and supported for 9 months).
=> images: ubuntu: Add 23.04 Lunar image

.github/workflows/ubuntu-images.yaml
This adds Ubuntu 16.04, 18.04, 20.04, 21.10 and 22.04 images that play well with `toolbox`:
password-less `sudo`, able to resolve its own hostname (so that `sudo` does not complain), SELinux is masked off, etc.
Since 18.04 Ubuntu images on the Docker Hub are 'minimized', so we have to undo that.
Pushed images to https://hub.docker.com/r/jmennius/ubuntu-toolbox for the time being.
Users may want to generate their locale after toolbox creation with `sudo sed -i "/${LANG}/s/^# //g" /etc/locale.gen && sudo locale-gen` (assuming that you have `LANG` set) to avoid `perl` and others complain about it.
I've been using an 18.04 image for ~several months~ 1.5yrs now with great success.
Some things I'd like to resolve or discuss at least (need help/guidance/decisionmaking/PRs):
I'd be grateful for …
=> Introduce Ubuntu LTS and latest non-LTS images

src/pkg/utils/utils.go
The VERSION_ID field in os-release(5) is optional [1].  It's absent on Arch Linux, which follows a rolling-release model and uses the BUILD_ID field instead:
BUILD_ID=rolling
A subsequent commit will add built-in support for Arch Linux.  Hence, the code to get the default release from the host operating system can no longer assume the presence of the VERSION_ID field in os-release(5).
[1] https://www.freedesktop.org/software/systemd/man/os-release.html
=> pkg/utils: Support host operating systems without VERSION_ID

src/pkg/utils/utils.go, src/pkg/utils/utils_test.go, test/system/000-setup.bats, test/system/101-create.bats, test/system/102-list.bats, test/system/104-run.bats, test/system/libs/helpers.bash
This allows using the --distro option to create and enter Arch Linux
containers.  Due to Arch's rolling-release model, the --release option
isn't required.  If --release is used, the accepted values are 'latest'
and 'rolling'.
=> pkg/utils: Offer built-in support for Arch Linux

.github/CODEOWNERS
This reflects the value of the 'maintainer' LABELs of the images.
/cc @Jmennius
=> .github/CODEOWNERS: Clarify ownership of Ubuntu image publication

test/system/107-rmi.bats
Commit e22a82fec8e59c5a already added a dependency on Bats >= 1.7.0, which is present on Fedora >= 36.  Therefore, it should be exploited wherever possible to simplify things.
Earlier, when the line counts were checked only with Bats >= 1.7.0, there was a need to separately check the whole standard error and output streams with 'assert_output' for the tests to be useful on Fedora 35, which only had Bats 1.5.0.  Now that the line counts are being checked unconditionally, there's no need for that anymore.
Note that bats_require_minimum_version itself is only available from Bats 1.7.0 [1].
[1] Bats commit 71d6b71cebc3d32b
https://github.com/bats-core/bats-core/issues/556
https://bats-core.readthedocs.io/en/stable/warnings/BW02.html
=> test/system: Simplify the line count checks by relying on Bats >= 1.7.0

test/system/001-version.bats, test/system/104-run.bats, test/system/107-rmi.bats, test/system/108-completion.bats
Bats 1.7.0 emits a warning if a feature that is only available starting
from a certain version of Bats onwards is used without specifying that
version [1]:
```
BW02: Using flags on `run` requires at least BATS_VERSION=1.5.0. Use
`bats_require_minimum_version 1.5.0` to fix this message.
(from function `bats_warn_minimum_guaranteed_version' in file
/usr/lib/bats-core/warnings.bash, line 32,
from function `run' in file
/usr/lib/bats-core/test_functions.bash, line 227,
in test file test/system/001-version.bats, line 27)
```
Note that `bats_require_minimum_version` itself is only available from
Bats 1.7.0 [2].  Hence, even though the specific feature here (using
flags on 'run') only requires Bats >= 1.5.0, in practice Bats >= 1.7.0
is needed.  Fortunately, commit e22a82fec8e59c5a already added …
=> test/system: Fix warnings by specifying the minimum needed Bats version

src/go.mod, src/meson.build
Go 1.14 added experimental support for 64-bit RISC-V on Linux (GOOS=linux, GOARCH=riscv64) [1], and the path of the dynamic linker (ie., PT_INTERP) was taken from the ABI specification [2].
Tested in Arch Linux rv64gc qemu user image.
[1] https://tip.golang.org/doc/go1.14#riscv
[2] https://sourceware.org/glibc/wiki/ABIList
https://github.com/containers/toolbox/pull/1159
=> build: Make it build on riscv64

test/system/README.md, test/system/setup_suite.bash
We wasted some time trying to get the tests
running locally, when all we were missing was
git submodules init.
Add some more obvious hints about this possible
stumbling block.
=> tests: Add an obvious error message

playbooks/dependencies-centos-9-stream.yaml, playbooks/dependencies-fedora-restricted.yaml, playbooks/dependencies-fedora.yaml
Ansible's 'shell' module is almost exactly like the 'command' module, except that it runs the command through a command line shell so that environment variables like HOSTNAME and operations like '*', '<' and '>' work.  None of those things are necessary are here.  Hence, it's better to use the 'command' module as elsewhere.
=> playbooks: Use Ansible's 'command' module, instead of 'shell'

.github/workflows/ubuntu-tests.yaml
Now that Toolbx offers built-in support for Ubuntu containers [1],
adding an Ubuntu host to the upstream CI will help ensure that Toolbx
continues to work well on Ubuntu.  Ubuntu 22.04 is the latest long term
support (or LTS) release [2] from Ubuntu, and is the latest Ubuntu
version that GitHub provides runners for [3].
Ubuntu 22.04 only has Bats 1.2.1 [4], while Toolbx requires 1.7.0 [5];
and Shadow 4.8 [6], while Toolbx requires 4.9 because it needs
libsubid.so [7,8].  Hence, newer versions of these dependencies need to
be built to run the tests.  The build flags for Shadow were taken from
the Debian package [9].
A separate sub-directory inside $GITHUB_WORKSPACE [10] is used for
Toolbx itself to prevent codespell from getting triggered by spelling
mistakes in these dependencies …
=> .github/workflows: Run the CI on Ubuntu 22.04

meson.build, test/meson.build, test/system/101-create.bats, test/system/102-list.bats, test/system/104-run.bats, test/system/201-ipc.bats, test/system/203-network.bats, test/system/libs/helpers.bash, test/system/meson.build
BATS_TMPDIR is the base directory used by Bats for all temporary files and directories, and BATS_TEST_TMPDIR is unique to each test [1].  It's better to limit the scope of the tests' temporary files as much as possible to avoid unexpected collisions with Bats' own internal temporary files.
[1] https://bats-core.readthedocs.io/en/stable/writing-tests.html
=> test/system: Limit the scope of temporary files used by a single test

test/system/210-ulimit.bats, test/system/meson.build
The following caveats must be noted:
* Podman sets the Toolbx container's soft limit for the maximum number
of open file descriptors to the host's hard limit, which is often
greater than the host's soft limit [1].
* The ulimit(1) options -b, -k, P and -T don't work on Fedora 38
because the corresponding resource arguments for getrlimit(2) are
absent from the operating system.  These are RLIMIT_SBSIZE,
RLIMIT_KQUEUES, RLIMIT_NPTS and RLIMIT_PTHREAD respectively.
[1] https://github.com/containers/podman/issues/17681
=> test/system: Test the resource limits

test/system/104-run.bats
```
Line 202:
run echo "$name"
^---^ SC2154 (warning): name is referenced but not assigned.
```
See: https://www.shellcheck.net/wiki/SC2154
=> test/system: Silence SC2154

playbooks/dependencies-fedora-restricted.yaml, playbooks/dependencies-fedora.yaml
The Ansible version that is installed in Zuul is 2.13.7 that is expecting python3-dnf library to be installed on the host.
I have done a test on the rawhide host and it seems that the ansible-core package that is available in Fedora repo (2.15) is fine and it does not require python3-dnf package. It means, that if the pull request will be merged, we should revert it later, after Zuul update.
=> playbooks: Add workaround for Fedora Rawhide

playbooks/dependencies-fedora-restricted.yaml, playbooks/dependencies-fedora.yaml, test/system/setup_suite.bash
First, it's not a good idea to use awk(1) as a grep(1) replacement. Unless one really needs the AWK programming language, it's better to stick to grep(1) because it's simpler.
Secondly, it's better to look for a specific os-release(5) field instead of looking for the occurrence of 'rawhide' anywhere in the file, because it lowers the possibility of false positives.
=> test/system: Simplify the check for Fedora Rawhide

test/system/libs/helpers.bash
Fallout from 54a2ca1ead343c3db2c7443cc58b9d9e896d3c46
=> test/system: Fix typos in conditional expressions

src/cmd/initContainer.go, test/system/104-run.bats, test/system/libs/helpers.bash
Sometimes locations such as `/var/lib/flatpak`, `/var/lib/systemd/coredump` and `/var/log/journal` sit on security hardened mount points that are marked as `nosuid,nodev,noexec` [1].  In such cases, when Toolbx is used rootless, an attempt to bind mount these locations read-only at runtime with `mount(8)` fails because of permission problems:
```
mount: <containerPath>: filesystem was mounted, but any subsequent
operation failed: Unknown error 5005.
```
(Note that the above error message from mount(8) was subsequently improved to show something more meaningful than 'Unknown error' [2].)
The problem is that `init-container` is running inside the container's mount and user namespace and the source paths were mounted inside the host's namespace with `nosuid,nodev,noexec`.  The above …
=> Be aware of security hardened mount points

.github/workflows/ubuntu-tests.yaml, test/system/102-list.bats, test/system/201-ipc.bats, test/system/203-network.bats, test/system/210-ulimit.bats
Until Bats 1.10.0, `run --keep-empty-lines` had a bug where it counted the trailing newline on the last line as a separate line [1].  However, Bats 1.10.0 is only available in Fedora >= 39 and is absent from Fedoras 37 and 38.
[1] Bats commit 6648e2143bffb933
https://github.com/bats-core/bats-core/commit/6648e2143bffb933
https://github.com/bats-core/bats-core/issues/708
=> test/system: Unbreak the line count checks with Bats >= 1.10.0

test/system/206-user.bats, test/system/meson.build
These tests assume that the group and user information on the host operating system can be provided by different plugins for the GNU Name Service Switch (or NSS) functionality of the GNU C Library.  eg., on enterprise FreeIPA set-ups.  However, it's expected that everything inside the Toolbx container will be provided by `/etc/group`, `/etc/passwd`, `/etc/shadow`, etc..
While `/etc/group` and `/etc/passwd` can be read by any user, `/etc/shadow` can only be read by root.  However, it's awkward to use `sudo(8)` in the test cases involving `/etc/shadow`, because they ensure that `root` and `$USER` don't need passwords to authenticate inside the container, and `sudo(8)` itself depends on that.  If `sudo(8)` is used, the test suite can behave unexpectedly if Toolbx didn't set up the container …
=> test/system: Test that group and user IDs work

src/cmd/initContainer.go, test/system/211-dbus.bats, test/system/meson.build
Followup to 1cc9e07b7c36fe9f9784b40b58f0a2a3694dd328
Sometimes the parent location might be mounted with nosuid,nodev,noexec and trying to remount it as ro would remove those and thus fails.
See commit mentioned above for more details.
https://github.com/containers/toolbox/issues/911
=> cmd/initContainer: Do not try to remount /etc/machine-id as ro

src/cmd/initContainer.go
Until now, `configureUsers()` was pushing the burden of deciding whether
to add a new user or modify an existing one on the callers, even though
it can trivially decide itself.  Involving the caller loosens the
encapsulation of the user configuration logic by spreading it across
`configureUsers()` and it's caller, and adds an extra function parameter
that needs to be carefully set and is vulnerable to programmer errors.
Fallout from 9ea6fe5852ea8f5225114d825e8e6813e2a3cfea
=> cmd/initContainer: Simplify code by removing a function parameter

playbooks/dependencies-fedora-restricted.yaml, playbooks/dependencies-fedora.yaml
The DNF5 Change [1] was dropped from Fedora 39 (and Rawhide) [2] and postponed for a later Fedora.  Therefore, there's no need for this workaround.
This reverts commit 96791726a35d9a19c53064bbb17204f4aba92e46.
[1] https://fedoraproject.org/wiki/Changes/ReplaceDnfWithDnf5
[2] https://pagure.io/fesco/issue/3039
=> Revert "playbooks: Add workaround for Fedora Rawhide"

src/cmd/initContainer.go
It's one less invocation of an external command, which is good because
spawning a new process is generally expensive.
One positive side-effect of this is that on some Active Directory
set-ups, the entry point no longer fails with:
```
Error: failed to remove password for user login@company.com: failed
to invoke passwd(1)
```
... because of:
```
passwd: Libuser error at line: 210 - name contains invalid char `@'.
```
This is purely an accident, and isn't meant to be an intential change to
support Active Directory.  Tools like `useradd(8)` and `usermod(8)` from
Shadow aren't meant to work with Active Directory users, and, hence, it
can still break in other ways.  For that, one option is to expose `$USER`
from the host operating system to the Toolbx container through a Varlink
interface that …
=> cmd/initContainer: Simplify removing the user's password

test/system/001-version.bats, test/system/002-help.bats, test/system/101-create.bats, test/system/102-list.bats, test/system/103-container.bats, test/system/104-run.bats, test/system/105-enter.bats, test/system/106-rm.bats, test/system/107-rmi.bats, test/system/108-completion.bats, test/system/libs/helpers.bash, test/system/setup_suite.bash
These files aren't marked as executable, and shouldn't be, because they
aren't meant to be standalone executable scripts.  They're meant to be
part of a test suite driven by Bats.  Therefore, it doesn't make sense
for them to have shebangs, because it gives the opposite impression.
The shebangs were actually being used by external tools like Coverity to
deduce the shell when running shellcheck(1).  Shellcheck's inline
'shell' directive is a more obvious way to achieve that.
=> test/system: Replace the shebangs with 'shell' directives

test/system/libs/helpers.bash
Bats' `run` helper is not necessary to merely check if a command succeeded or not [1].  In this case, it's idiomatic to pipe the *output* directly to `grep(1)` and use it as the condition for an `if` branch.
[1] https://bats-core.readthedocs.io/en/stable/writing-tests.html
=> test/system: Simplify checking if the container started or not

test/system/libs/helpers.bash
```
Line 505:
. "$os_release"
^-----------^ SC1090 (warning): ShellCheck can't follow non-constant
source. Use a directive to specify location.
```
See: https://www.shellcheck.net/wiki/SC1090
=> test/system: Silence SC1090

test/system/101-create.bats, test/system/103-container.bats, test/system/104-run.bats, test/system/105-enter.bats, test/system/setup_suite.bash
```
Line 624:
local system_id="$(get_system_id)"
^-------^ SC2155 (warning): Declare and assign separately to
avoid masking return values.
```
See: https://www.shellcheck.net/wiki/SC2155
=> test/system: Silence SC2155

test/system/libs/helpers.bash
```
Line 442:
for TRIES in 1 2 3 4 5; do
^-^ SC2034 (warning): TRIES appears unused. Verify use (or export if
used externally).
```
See: https://www.shellcheck.net/wiki/SC2034
This also makes the code consistent with the rest.
=> test/system: Silence SC2034

test/system/libs/helpers.bash
Until Bats 1.10.0, `run` with options had a bug where it would overwrite
the value of the `i` variable even outside `run` [1].
In these particular instances, no options are being passed to 'run',
and, hence, currently there's no problem.  However, in case a future
commit adds an option, then it could lead to hard-to-debug problems.
eg., `--separate-stderr` sets `i` to 1, `--show-output-of-passing-tests`
sets it to 2, etc..  Therefore, depending on the flag and the loop, the
loop might get terminated prematurely or run infinitely or something
else.
Moreover, Bats 1.10.0 is only available in Fedora >= 39 and is absent
from Fedoras 37 and 38.  Therefore, it's not possible to consider this
bug fixed.
Hence, it's better to preemptively work around it to avoid any future
issues.
[1] Bats commit …
=> test/system: Avoid future problems caused by Bat's 'run' overwriting 'i'

test/system/libs/helpers.bash
Bats' `run` helper returns with an exit code of 0 even when the command that it was given to run failed with a non-zero exit code [1].  This is to enable making further assertions about the command after `run` has finished.  If there's nothing that checks for failures, then it will continue as if everything is alright.
Therefore, currently, if `podman logs` fails, there's no indication of it and the test only fails later because it thinks that the container failed to initialize:
```
not ok 106 container: Check container starts without issues
test/system/libs/bats-assert/src/assert.bash, line 114,
#
#
```
Instead, from now on, it will be more obvious:
```
not ok 106 container: Check container starts without issues
test/system/libs/bats-assert/src/assert.bash, line 114,
#
#
```
One …
=> test/system: Make it easier to debug 'podman logs' failures

test/system/libs/helpers.bash
Currently, if a Toolbx container's entry point fails to initialize the
container, there's no way to see the debug logs and error messages from
the entry point:
```
not ok 106 container: Check container starts without issues
test/system/libs/bats-assert/src/assert.bash, line 114,
#
#
```
Instead, from now on, they will be visible:
```
not ok 106 container: Check container starts without issues
test/system/libs/bats-assert/src/assert.bash, line 114,
#
/usr/bin/toolbox"
#
```
=> test/system: Make it easier to debug why a container didn't initialize

test/system/libs/helpers.bash
Contrary to what the documentation might seem to imply [1], Bats' `fai`' helper only aborts a test case under certain circumstances.  eg., when called from `setup_suite()`, but not from within a child function, and a `@test` case, but not from within the `run` helper.
If `fail` is called from within `run`, then the code after it will continue to execute.  The test case will only fail if `run` eventually catches a non-zero exit code that's caught by `assert_success` [2]. Similarly, it doesn't abort if called from within a child function in `setup_suite()`.
Currently, `_pull_and_cache_distro_image()` is a child function called from `setup_suite()`.  So `fail` won't abort if an invalid distribution is specified.
Fortunately, `pull_distro_image()` is being called from within `@test` cases, …
=> test/system: Ensure failure if an invalid distribution is specified

.zuul.yaml, playbooks/dependencies-centos-9-stream.yaml, playbooks/dependencies-fedora-restricted.yaml, playbooks/dependencies-fedora.yaml, test/system/002-help.bats, test/system/102-list.bats
See:
https://github.com/cpuguy83/go-md2man/issues/99
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1049968
=> test/system: Unbreak the 'help' tests on Fedora >= 39 with GNU roff 1.23

images/fedora/f39/ensure-files
The translations for the RPM manuals were removed upstream during the RPM 4.19 development cycle [1].  So, replace them with rpm2cpio(8), which is another popular command shipped by the rpm package.
[1] RPM commit 4df74a9644b18136
https://github.com/rpm-software-management/rpm/commit/4df74a9644b18136
https://github.com/rpm-software-management/rpm/pull/2245
=> images: Update the tests for Fedora 39

gen-docs-list, test/system/002-help.bats
GNU roff 1.23 stopped remapping unescaped Hyphen-Minus (ie., - or 0x2D)
characters in the input to Hyphen-Minus in the output.  Instead, it
follows the specified behaviour of converting unescaped Hyphen-Minus
characters in the input to Hyphen (ie., ‐ or 0x2010) in the output.  To
get Hyphen-Minus characters in the output, one needs to escape the
Hyphen-Minus with a backslash (ie., \-) in the input [1].
Therefore, the command line options documented in the manuals are no
longer prefixed with the Hyphen-Minus character that's needed to
ctually use them.  This breaks copying and pasting from the manuals and
searching within them.
Unfortunately, escaping the Hyphen-Minus characters in Markdown doesn't
have the intended effect of having Hyphen-Minus in the generated manual
pages [2]. …
=> test/system: Unbreak the manual page checks with GNU roff >= 1.23

test/system/201-ipc.bats, test/system/203-network.bats, test/system/206-user.bats
https://github.com/containers/toolbox/issues/1410
=> test/system: Test that DNS A and AAAA records can be queried

src/pkg/utils/utils.go
=> utils.go: bump fedora fallback version to 38

test/system/104-run.bats
The test "run: Ensure that $HOME is used as a fallback working directory" assumes `/etc/kernel` will not be present in containers, but this is not the case for Ubuntu (and Debian) containers. This patch switches the test to using a temporary directory (under `/var/tmp` which is not mounted by toolboxes) to ensure fallback is activated.
=> test/system: switch HOME fallback to tmp dir (fix for Ubuntu hosts)

src/go.mod, src/go.sum
... to improve performance by not using regular expressions [1]. However, the potential reduction in binary size is lost because Toolbx already uses the 'regexp' package to check if a string might be the ID of an image or a valid container name.
[1] go-units commit 737572633c434ce2
https://github.com/docker/go-units/commit/737572633c434ce2
https://github.com/docker/go-units/pull/40
=> build: Bump github.com/docker/go-units to 0.5.0

README.md, images/fedora/f38/README.md, images/fedora/f39/README.md
Only the images for currently maintained Fedoras (ie., 38 and 39) were updated.
https://github.com/containers/toolbox/issues/1417
=> README.md, images/fedora: Unbreak OSTree URL

.github/workflows/ubuntu-tests.yaml, src/cmd/create.go, src/cmd/list.go, src/cmd/run.go, src/cmd/utils.go, src/go.mod, src/go.sum, src/meson.build, src/pkg/shell/shell.go, src/pkg/shell/shell_test.go, src/pkg/skopeo/skopeo.go, src/pkg/term/term.go, src/pkg/term/term_test.go
It takes `skopeo inspect` a few seconds to fetch the image size from the
remote registry, and while that happens the user can't interact with the
image download prompt:
```
$ toolbox create
Image required to create toolbox container.
<wait for a few seconds>
Download registry.fedoraproject.org/fedora-toolbox:39 (359.8MB)? [y/N]:
```
This feels awkward because it's not clear to the user what's going on
during those few seconds.  Moreover, while knowing the image size can be
convenient at times, for example when disk space and network bandwidth
are limited, it's not always important.
It will be better if `skopeo inspect` ran in the background, while
waiting for the user to respond to the image download prompt, and once
the image size has been fetched, the prompt can be updated to include …
=> Don't block user interaction while fetching the image size

src/cmd/initContainer.go, test/system/203-network.bats
On some Toolbx images with `systemd-resolved(8)`, like the `fedora-toolbox`
images for Fedora 39 onwards, `/etc/resolv.conf` can end up being a
symbolic link inside the container that expects the host operating
system to also use `systemd-resolved(8)`:
```ShellSession
$ ls -l /etc/resolv.conf
lrwxrwxrwx. 1 root root 39 Nov 28 08:50 /etc/resolv.conf ->
../run/systemd/resolve/stub-resolv.conf
```
This happens because `systemd-resolved(8)` already makes `/etc/resolv.conf`
a symbolic link inside the image, and, hence, the container's entry
point doesn't change it to point at the host's copy of the file at
`/run/host/etc/resolv.conf`.  Instead, it's left pointing at the host's
copy of the files maintained by `systemd-resolved(8)` under
`/run/systemd/resolve`, which happen to be also available …
=> Fix DNS queries in images with systemd-resolved on hosts  without it

src/cmd/utils.go
Without a sufficient buffer size the discard function does not read fast/efficiently enough causing multiple lines indicating "passed and discarded input" to show up.
I used an already defined constant[0] for the buffer size to prevent the use of a yet-another magical constant.
[0] https://pkg.go.dev/bytes#pkg-constants
=> cmd/utils: Increase buffer size when discarding terminal input

src/cmd/enter.go, src/cmd/rootMigrationPath.go
Prompt is a new terminal emulation application [1] designed for a container-oriented desktop that implements the OSC 777 escape sequence to track and preserve the user's current Toolbx container [2].  Hence, Fedora's fork of GNOME Terminal is no longer the only one to offer this.
Therefore, it's time let users of all host operating systems enjoy this feature.
This reverts commits a3e8d8d12bac6dd63010b71c6e091486fb585f37 and 3a96feba478448cd0c5628238619c3805c6aca1e.
[1] https://gitlab.gnome.org/chergert/prompt
[2] https://gitlab.freedesktop.org/terminal-wg/specifications/-/issues/17
https://github.com/containers/toolbox/issues/218
=> cmd: Let the terminal know the active container on all host OSes

src/cmd/create.go, test/system/101-create.bats
To limit the possible misbehaviour of Toolbx when ued in scripting, require the presence of valid terminal on stdin when an image needs to be pulled to create a new toolbx.
=> cmd/create: Require valid terminal when prompting to pull an image

test/system/220-environment-variables.bats
Bash automatically sets the `HOSTNAME` environment variable to the name of
the current host [1] as returned by `gethostname(2)`, which is the same as
`hostname(1)`.
However, on Fedora, from Fedora 33 onwards, `/etc/profile` sets the
`HOSTNAME` environment variable to `hostnamectl --transient` [2], and,
from Fedora 35 onwards, it has a fallback to `hostname(1)` [3].  These two
approaches return different values when used inside a Toolbx container.
The former picks up the hostname of the host operating system, while the
fallback gets the name that was set when creating the container with
`podman create --hostname toolbox ...`.
Hence, the value of `HOSTNAME` inside a Toolbx container for Fedora
depends on whether the corresponding version of the `fedora-toolbox` image
contained …
=> test/system: Test that the HOSTNAME environment variable is set

images/arch/Containerfile
The `--noconfirm` pacman flag automatically accepts the default answer for each questions and the default answer to removing cached packages when using `pacman -Scc` is "N" (no).
That means that `pacman -Scc --noconfirm` does not actually remove cached packages.
Since pacman doesn't have a way to choose to answer yes or no automatically *(yet?)*, a simple workaround is to use `yes | pacman -Scc ` instead. However, while it is [recommended to set `pipefail` when using pipes](https://docs.docker.com/develop/develop-images/instructions/#using-pipes), it is not possible with the `yes` command (see [this comment](https://stackoverflow.com/a/70852402) for more details).  
Although, it should be safe to just use a piped `yes` without setting `pipefail` as I don't see how it could be a cause of …
=> Fix pacman cache removal in Arch image

test/system/101-create.bats, test/system/102-list.bats, test/system/104-run.bats, test/system/203-network.bats, test/system/206-user.bats, test/system/211-dbus.bats, test/system/220-environment-variables.bats, test/system/setup_suite.bash
Red Hat Enterprise Linux 8.7 reached End of Life on 31st May 2023: https://access.redhat.com/articles/4038291
https://access.redhat.com/support/policy/updates/errata
Since the tests are intended for Toolbx, not the Red Hat infrastructure, it will be better to use a newer image, because it will be closer to what the users are seeing.
=> test/system: Replace the RHEL toolbox:8.7 image with toolbox:8.9

meson.build, meson_options.txt
It is difficult for downstream to track dependencies when they are automatic. This results in shell completion scripts not being installed in packages because builders do not have the right dependency. This commit adds meson feature arguments to guard those dependencies so that downstream distributions can use `-Dauto_features=enabled`.
For more explanation, see rule #3 of:
https://blogs.gnome.org/mcatanzaro/2022/07/15/best-practices-for-build-options/
=> build: Do not use use auto dependencies for shell completion scripts

images/fedora/f38/ensure-files, images/fedora/f38/extra-packages, images/fedora/f38/missing-docs, images/fedora/f39/ensure-files, images/fedora/f39/extra-packages
Currently, the libpwquality package mentions cracklib-dicts as a weak dependency [1,2].  However, the libpwquality package is part of the fedora base image, which doesn't include weak dependencies [3], and that leads to cracklib-dicts going missing.
The absence of the cracklib-dicts package causes various operations that go through libpwquality (eg., pwmake(1)) to fail [1], and sometimes in confusing ways [4].
[1] Fedora libpwquality commit f84a5e3ba6c166e5
https://src.fedoraproject.org/rpms/libpwquality/c/f84a5e3ba6c166e5
https://bugzilla.redhat.com/show_bug.cgi?id=2158891
[2] Fedora libpwquality commit 303154338d6d3650
https://src.fedoraproject.org/rpms/libpwquality/c/303154338d6d3650
https://bugzilla.redhat.com/show_bug.cgi?id=2006063
[3] fedora-kickstarts commit 1c39c0adb0d44866 …
=> images/fedora: Add cracklib-dicts to Fedora 38 and 39

.zuul.yaml
With the recent expansion of the test suite, it's necessary to increase the timeout for the Fedora 38 and 39 nodes to prevent the CI from timing out.
=> .zuul: Try to prevent the CI from timing out on Fedora 38 and 39

test/system/206-user.bats
https://github.com/containers/toolbox/issues/608
=> test/system: Ensure that the user is part of a group with the same name, and the process started by 'podman exec' has all groups

test/system/setup_suite.bash
The paths to `bats-assert` and `bats-support` are broken, if `bats(1)` is invoked from any other location than the parent directory of the `tests` directory.  eg., Podman's downstream Fedora CI invokes the tests as:
```
$ cd /path/to/toolbox/test/system
$ bats .
```
... and it led to [1]:
```
1..306
not ok 1 setup_suite
```
Fallout from 2c0960660330dc6be6861502988695f9812c475a
[1] https://bugzilla.redhat.com/show_bug.cgi?id=2263968
=> test/system: Unbreak Podman's downstream Fedora CI

test/system/101-create.bats, test/system/libs/helpers.bash
`BATS_RUN_DIR` is the directory used by Bats for its own internal temporary files, and `BATS_SUITE_TMPDIR` is for creating files common to all tests in the test suite [1].  It's better to stay away from Bats' own internal temporary files to avoid unexpected collisions.
[1] https://bats-core.readthedocs.io/en/stable/writing-tests.html
=> test/system: Limit the scope of temporary files used by all tests

images/fedora/f38/Containerfile, images/fedora/f38/ensure-files, images/fedora/f38/extra-packages, images/fedora/f39/Containerfile, images/fedora/f39/ensure-files, images/fedora/f39/extra-packages
Only the images for currently maintained Fedoras (ie., 38 and 39) were updated.
=> images/fedora: Add translations for gawk, and all the iconv converter modules for glibc

test/system/104-run.bats, test/system/201-ipc.bats, test/system/203-network.bats, test/system/206-user.bats, test/system/210-ulimit.bats, test/system/211-dbus.bats, test/system/220-environment-variables.bats
The working directory from which `bats(1)` is invoked might not be part of the Toolbx container.  eg., Podman's downstream Fedora CI invokes the tests as:
```
$ cd /path/to/toolbox/test/system
$ bats .
```
... and it led to [1]:
```
not ok 110 run: Smoke test with true(1)
./libs/bats-assert/src/assert.bash, line 255,
#
#
file or directory: OCI runtime attempted to invoke a command that
was not found
container fedora-toolbox-41
#
```
[1] https://bugzilla.redhat.com/show_bug.cgi?id=2263968
=> test/system: Unbreak Podman's downstream Fedora CI (part 2)

src/pkg/utils/utils.go, test/system/220-environment-variables.bats
As discussed [here](https://github.com/containers/toolbox/issues/1449#issuecomment-1966175099).
- Adds `XTERM_VERSION` to the list of preserved environment variables
=> Preserve xterm version

.github/workflows/ubuntu-tests.yaml, NEWS, gen-docs-list, meson_post_install.py, playbooks/dependencies-fedora-restricted.yaml, playbooks/dependencies-fedora.yaml, playbooks/setup-env-migration-path-for-coreos-toolbox.yaml, playbooks/setup-env-restricted.yaml, playbooks/setup-env.yaml, playbooks/system-test.yaml, playbooks/unit-test.yaml, src/cmd/completion.go, src/cmd/rootDefault.go, src/go-build-wrapper, src/meson_generate_completions.py, src/meson_go_fmt.py, src/pkg/shell/shell.go, src/pkg/skopeo/skopeo.go, src/pkg/term/term.go, src/pkg/term/term_test.go, src/pkg/utils/errors.go, src/pkg/utils/libsubid-wrappers.c, src/pkg/utils/libsubid-wrappers.h, src/pkg/utils/utils.go, src/pkg/utils/utils_cgo.go, src/pkg/utils/utils_test.go, src/toolbox.go, test/system/103-container.bats, test/system/README.md
The system tests download several images when setting up the test suite, and cache them for later use by the tests [1].  This saves time and avoids hitting rate limits imposed by OCI registries by not downloading the same images repeatedly for several tests, but at the cost of increased use of storage space to cache the images.
The images are cached under `BATS_TMPDIR`.  It defaults to the `TMPDIR` environment variable, and if that's not set then to `/tmp` [2].  Normally, `TMPDIR` isn't set, and the images end up getting cached under `/tmp`.  Now, `/tmp` is typically on `tmpfs` backed by RAM or swap, which means that it should be used for smaller size-bounded files only, and `/var/tmp` should be used for everything else [3].
The images are big enough that a collection of them can't be …
=> playbooks/system-test, test/system: Avoid running out of storage space

.github/workflows/ubuntu-tests.yaml
**Changes**
- Update `ubuntu-tests` so that it uses `checkout@v4` instead of `checkout@v3`
Closes #1459.
=> Bump actions/checkout from v3 to v4

playbooks/dependencies-centos-9-stream.yaml, playbooks/dependencies-fedora.yaml
Ansible's built-in 'package' module doesn't show any details when installing the RPMs.  All that can be seen is:
```
TASK [Install RPM packages]
fedora-rawhide | changed
```
Therefore, there's no way to know what version of the packages got installed.
In this case, not knowing the Bats version being used by the CI makes it difficult to know why the tests are generating this spew on Fedora Rawhide [1]:
```
TASK [Run system tests]
test/system/libs/helpers.bash: line 7: TEMP_BASE_DIR: readonly variable
test/system/libs/helpers.bash: line 8: TEMP_STORAGE_DIR: readonly variable
test/system/libs/helpers.bash: line 10: IMAGE_CACHE_DIR: readonly variable
test/system/libs/helpers.bash: line 11: ROOTLESS_PODMAN_STORE_DIR: readonly variable
test/system/libs/helpers.bash: line 12: …
```
=> playbooks: Show the Bats version

test/system/libs/helpers.bash
The specific port used by the local temporary Docker registry inside the
container doesn't matter.  The container is running only one service and
its users only see the corresponding port on the host operating system.
The default port within the container is 5000 [1] and there's no reason
to change it.
[1] https://github.com/distribution/distribution-library-image
=> test/system: Drop unnecessary port configuration from registry container

src/cmd/create.go, src/meson.build, src/pkg/podman/errors.go, src/pkg/podman/podman.go, test/system/101-create.bats
Currently, it's not possible to create a Toolbx container from an image
without a name:
```ShellSession
$ podman build --squash images/fedora/f39
STEP 1/21: FROM registry.fedoraproject.org/fedora:39
STEP 2/21: ARG NAME=fedora-toolbox
STEP 3/21: ARG VERSION=39
...
--> 2f9bdf11c8d4
2f9bdf11c8d4d7674dfb17d8edcfd13475d8636077f1a6208ecd616de77d7f80
$ toolbox create --image 2f9bdf11c8d4
Error: empty RepoTag for image 2f9bdf11c8d4
```
The image's fully qualified name is fetched from its `RepoTags` for purely
cosmetic reasons to show a human-readable name in the debug logs.
Therefore, there's no reason to fail the creation of a Toolbx container
in the absence of it.
Note that an image without a name will have an empty `RepoTags` array in
the JSON returned by `podman inspect --format json --type …
=> cmd/create, pkg/podman: Let 'create' use an image without a name

src/cmd/create.go, src/cmd/run.go, src/meson.build, src/pkg/podman/errors.go, src/pkg/podman/podman.go, test/system/101-create.bats
In future, it will be good if `podman.Inspect()` returned a `Container` or
`Image` object instead of a `[]map[string]interface{}` that the caller has
to parse.  This is because parsing the `[]map[string]interface{}` involves
tracking changes in the JSON output by different Podman versions, and
it's better to limit such details to the `podman` package.
Splitting `podman.Inspect()` into two separate functions for containers
and images is one way of achieving that.
=> cmd/run, pkg/podman: Split Inspect() into two for containers and images

src/cmd/create.go, src/cmd/list.go, src/cmd/rm.go, src/cmd/run.go, src/pkg/podman/container.go, src/pkg/podman/containerInspect_test.go, src/pkg/podman/podman.go, test/system/104-run.bats
https://github.com/containers/toolbox/issues/1070
=> cmd/run: Optimize 'enter' and 'run' for already running containers, and turn IsToolboxContainer() into Container.IsToolbx()

src/cmd/run.go, test/system/104-run.bats
Currently, the `enter` and `run` commands poll at one second intervals
to check if the Toolbx container's entry point has created the
initialization stamp file to indicate that the container has been
initialized.  This came from the POSIX shell implementation [1], where
it was relatively easier to poll than to use `inotify(7)` to monitor the
file system.
The problem with polling is that the interval is always going to be
either too short and waste resources or too long and cause delays.  The
current one second interval is sufficiently long to add a noticeable
delay to the `enter` and `run` commands.
It will be better to use `inotify(7)` to monitor the file system, which is
quite easy to do with the Go implementation, so that the commands can
proceed as soon as the initialization stamp …
=> Optimize 'enter' and 'run' for a container getting initialized

src/go.mod, src/go.sum
=> build: Bump github.com/sirupsen/logrus to 1.9.3

.github/workflows/ubuntu-tests.yaml, test/system/104-run.bats
The `SHELL` environment variable goes mysteriously missing from the
runtime environment of the GitHub Actions workflow [1].  This breaks the
`create` and `enter` commands with:
```
Error: failed to get the current user's default shell
```
... and therefore tests involving them can't be run until this is
resolved.
It's been a year since this problem was first encountered and no
solution is in sight.  Therefore, it will be better to work around this
by explicitly setting the `SHELL` environment variable on Ubuntu 22.04 to
increase the number of tests run by the CI.
[1] https://github.com/orgs/community/discussions/59413
=> .github/workflows: Enable more tests on Ubuntu 22.04 by setting SHELL

src/cmd/create.go, src/cmd/initContainer.go, src/cmd/root.go
When a Toolbx container is started for the first time and the entry point invokes `passwd --delete root` to actually remove the password for root, `passwd(1)` writes the following to its standard error stream:
```
passwd: Note: deleting a password also unlocks the password.
```
This doesn't happen when the same container is stopped and started once again.
Since, `passwd(1)` directly writes to its standard error stream without going through Logrus, the corresponding log entry in `podman logs` doesn't have a `level` key, and is assumed by the log parser in the `enter` and `run` commands to be an error.  If the entry point doesn't actually encounter an error, then this confusion doesn't have any user-visible effect.  However, if the entry point does encounter an error after this point, then …
=> cmd/initContainer: Prevent passwd(1) from confusing the log parser

playbooks/dependencies-fedora-restricted.yaml, playbooks/dependencies-fedora.yaml
The Zuul executor got updated from Ansible 2.13.7 to 2.15.10, which now
has support for DNF5 [1] and the previous DNF5 Change [2] for Fedora 39
is now aiming at Fedora 41 (and Rawhide) [3].  Unfortunately, Ansible's
`dnf5` module is still under development and doesn't seem to match the
state of DNF5 in Fedora Rawhide, which causes:
```
TASK [Install RPM packages]
fedora-rawhide | ERROR
fedora-rawhide | {
fedora-rawhide |   "failures": [],
fedora-rawhide |   "msg": "Could not import the libdnf5 python module
using /usr/bin/python3 (3.12.3 (main, Apr 17 2024, 00:00:00) [GCC
14.0.1 20240411 (Red Hat 14.0.1-0)]). Please install
python3-libdnf5 package or ensure you have specified the correct
ansible_python_interpreter. (attempted
['/usr/libexec/platform-python', '/usr/bin/python3', …
```
=> playbooks: Avoid using potentially broken DNF5

test/system/101-create.bats, test/system/102-list.bats, test/system/104-run.bats, test/system/203-network.bats, test/system/206-user.bats, test/system/211-dbus.bats, test/system/220-environment-variables.bats, test/system/setup_suite.bash
Red Hat Enterprise Linux 8.9 reached End of Life when RHEL 8.10 was released on 22nd May 2024:
https://access.redhat.com/articles/3078
https://access.redhat.com/support/policy/updates/errata
For what it's worth, RHEL 8's full support phase ended on the 31st of May 2024 and it wil be in maintenance support, as RHEL 8.10, until the corresponding day in 2029.
=> test/system: Replace the RHEL toolbox:8.9 image with toolbox:8.10

.zuul.yaml
Fedora 38 reached End of Life on 21st May 2024:
=> .zuul: Drop testing on Fedora 38

.zuul.yaml, test/system/101-create.bats, test/system/103-container.bats, test/system/104-run.bats, test/system/105-enter.bats, test/system/106-rm.bats, test/system/201-ipc.bats, test/system/203-network.bats, test/system/206-user.bats, test/system/210-ulimit.bats, test/system/211-dbus.bats, test/system/220-environment-variables.bats, test/system/230-cdi.bats, test/system/libs/helpers.bash
It's far more consistent and understandable if all tests start with a
clean state without any containers or images present.  Otherwise, the
subtle side-effects of having some image left behind from a previous
test can lead to surprises, and there's no need to spend time wondering
whether some tests should only clean up the containers or both
containers and images.
=> test/system: Consolidate teardown() to remove both containers & images

.github/workflows/ubuntu-tests.yaml, src/pkg/utils/utils.go, test/system/002-help.bats, test/system/101-create.bats, test/system/102-list.bats, test/system/104-run.bats, test/system/501-create.bats, test/system/504-run.bats, test/system/meson.build
https://github.com/containers/toolbox/issues/957
https://github.com/containers/toolbox/pull/1052
=> pkg/utils, test/system: Retain errors without -v when forwarding to host

src/cmd/root.go, src/cmd/root_test.go, src/cmd/run.go, test/system/101-create.bats
This will make it easier to propagate the exit codes of subordinate
processes through an `exitError` instance, when `toolbox(1)` is invoked
inside a container, and invocation is forwarded to the host.
Cobra doesn't honour the root command's `SilenceErrors`, if an error
occurred when parsing the command line for a command, even though the
command was found.  However, Cobra does honour `SilenceErrors`, if the
error occurred afterwards.
Therefore, to avoid setting `SilenceErrors` in each and every command, it
was set in the `PersistentPreRunE` hook (ie., `preRun`), which is called
after all command line parsing has been successfully completed.
https://github.com/containers/toolbox/issues/957
=> cmd/root, cmd/run: Handle printing all errors but the CLI parsing ones

.github/workflows/ubuntu-tests.yaml, src/cmd/create.go, src/cmd/enter.go, src/cmd/help.go, src/cmd/list.go, src/cmd/rm.go, src/cmd/rmi.go, src/cmd/root.go, src/cmd/rootMigrationPath.go, src/cmd/root_test.go, src/cmd/run.go, src/pkg/utils/utils.go, test/system/104-run.bats, test/system/501-create.bats, test/system/504-run.bats, test/system/505-enter.bats, test/system/meson.build
Some changes by Debarshi Ray.
https://github.com/containers/toolbox/issues/957
https://github.com/containers/toolbox/pull/1052
=> cmd, test/system: Retain exit codes when forwarding to host

images/arch/Containerfile
This pull request brings the Arch Linux toolbx image in line with the other toolbx-provided images by providing man pages with the default install.
As of right now, it seems like every well-supported Arch Linux image available is a minimized install without man pages or visual enhancements enabled for pacman. This is great for containerized applications and CI, but this isn't so great for frequent users of Arch Linux in toolbx or distrobox.
I've been working around this problem for a long while by maintaining my own local dockerfiles, but I kind of expected this issue to be solved upstream by now. Since it looks like we're not going to get any more Arch Linux docker images from upstream (at least for a very long while), I figured this is the best place to stick this fix.
EDIT: I should …
=> Add man pages and progress bars to Arch Linux image

src/cmd/run.go, src/go.mod, src/pkg/nvidia/nvidia.go
The proprietary NVIDIA driver has a kernel space part and a user space
part, and they must always have the same matching version.  Sometimes,
the host operating system might end up with mismatched parts.  One
reason could be that the different third-party repositories used to
distribute the driver might be incompatible with each other.  eg., in
the case of Fedora it could be RPM Fusion and NVIDIA's own repository.
This shows up in the systemd journal as:
```
$ journalctl --dmesg
...
kernel: NVRM: API mismatch: the client has the version 555.58.02, but
NVRM: this kernel module has the version 560.35.03.  Please
NVRM: make sure that this kernel module and all NVIDIA driver
NVRM: components have the same version.
...
```
Without any special handling of this scenario, users would be presented …
=> cmd/run, pkg/nvidia: Detect mismatched NVIDIA kernel & user space driver

src/cmd/initContainer.go
NVIDIA Container Toolkit 0.16.0 changed the hook arguments in the
Container Device Interface specification generated by it [1].  Having
the unknown hook arguments show up in the debug logs makes it easier to
understand what happened.
[1] NVIDIA Container Toolkit commit 179d8655f9b5fce6
https://github.com/NVIDIA/nvidia-container-toolkit/commit/179d8655f9b5fce6
https://github.com/NVIDIA/nvidia-container-toolkit/issues/435
=> cmd/initContainer: Log unknown Container Device Interface hook arguments

.zuul.yaml, test/system/230-cdi.bats
Commit 87eaeea6f0c2b245 already added a dependency on Bats >= 1.10.0,
which is present on Fedora >= 39.  Therefore, it should be exploited
wherever possible to simplify things.
Currently, the CI has been frequently timing out on stable Fedora nodes.
So, increase the timeout from 1 hour 50 minutes to 2 hours to avoid
that.
For what it's worth, the timeout for Fedora Rawhide nodes is 2 hours 10
minutes and it seems enough.
=> .zuul, test/system: Simplify line count checks by using Bats >= 1.10.0

.zuul.yaml, src/cmd/initContainer.go, test/system/230-cdi.bats, test/system/data/cdi-hooks-create-symlinks-00.json, test/system/data/cdi-hooks-create-symlinks-01.json, test/system/data/cdi-hooks-create-symlinks-02.json, test/system/data/cdi-hooks-create-symlinks-03.json, test/system/data/cdi-hooks-create-symlinks-04.json, test/system/data/cdi-hooks-create-symlinks-05.json, test/system/data/cdi-hooks-create-symlinks-06.json, test/system/data/cdi-hooks-create-symlinks-07.json, test/system/data/cdi-hooks-create-symlinks-08.json, test/system/data/cdi-hooks-create-symlinks-30.json, test/system/data/cdi-hooks-create-symlinks-31.json, test/system/data/cdi-hooks-create-symlinks-32.json, test/system/data/cdi-hooks-create-symlinks-33.json, test/system/data/cdi-hooks-create-symlinks-34.json, test/system/data/cdi-hooks-create-symlinks-35.json, test/system/data/cdi-hooks-create-symlinks-36.json, test/system/data/cdi-hooks-create-symlinks-37.json
NVIDIA Container Toolkit 0.16.0 started using `create-symlinks` hooks in
the Container Device Interface specification generated by it [1].  For
example:
```
"hookName": "createContainer",
"path": "/usr/bin/nvidia-cdi-hook",
"args": [
"nvidia-cdi-hook",
"create-symlinks",
"--link",
"libnvidia-allocator.so.560.35.03::/usr/lib64/libnvidia-allocator.so.1",
"--link",
"../libnvidia-allocator.so.1::/usr/lib64/gbm/nvidia-drm_gbm.so"
]
```
Fallout from 649d02f8a6e1d3531324b571ce8a683b6989c41f
[1] NVIDIA Container Toolkit commit aae3da88c33d9cf2
https://github.com/NVIDIA/nvidia-container-toolkit/commit/aae3da88c33d9cf2
https://github.com/NVIDIA/nvidia-container-toolkit/pull/548
=> [WIP] cmd/initContainer, test/system: Handle NVIDIA's create-symlinks CDI hook

.zuul.yaml, playbooks/system-test-commands-options.yaml, playbooks/system-test-runtime-environment-arch-fedora.yaml, playbooks/system-test-runtime-environment-ubuntu.yaml, playbooks/system-test-runtime-environment.yaml, playbooks/system-test.yaml, test/system/001-version.bats, test/system/002-help.bats, test/system/101-create.bats, test/system/102-list.bats, test/system/103-container.bats, test/system/104-run.bats, test/system/105-enter.bats, test/system/106-rm.bats, test/system/107-rmi.bats, test/system/108-completion.bats, test/system/201-ipc.bats, test/system/203-network.bats, test/system/206-user.bats, test/system/210-ulimit.bats, test/system/211-dbus.bats, test/system/220-environment-variables.bats, test/system/230-cdi.bats, test/system/501-create.bats, test/system/504-run.bats, test/system/505-enter.bats, test/system/libs/helpers.bash, test/system/setup_suite.bash
The test suite has expanded to 415 system tests.  These tests can be
very I/O intensive, because many of them copy OCI images from the test
suite's image cache directory to its local container/storage store,
create containers, and then delete everything to run the next test with
a clean slate.  This makes the system tests slow.
Unfortunately, Zuul's max-job-timeout setting defaults to an upper limit
of 3 hours or 10800 seconds for jobs [1], and this is what Software
Factory uses [2].  So, there comes a point beyond which the CI can't be
prevented from timing out by increasing the timeout.
One way of scaling past this maximum time limit is to run the tests in
parallel across multiple nodes.  This has been implemented by splitting
the system tests into different groups, which are run …
=> .zuul, playbooks, test/system: Optimize the CI on Fedora nodes

.zuul.yaml, playbooks/system-test-commands-options.yaml, playbooks/system-test-runtime-environment-arch-fedora.yaml, playbooks/system-test-runtime-environment-ubuntu.yaml, playbooks/system-test-runtime-environment.yaml, playbooks/system-test.yaml, test/system/001-version.bats, test/system/002-help.bats, test/system/101-create.bats, test/system/102-list.bats, test/system/103-container.bats, test/system/104-run.bats, test/system/105-enter.bats, test/system/106-rm.bats, test/system/107-rmi.bats, test/system/108-completion.bats, test/system/201-ipc.bats, test/system/203-network.bats, test/system/206-user.bats, test/system/210-ulimit.bats, test/system/211-dbus.bats, test/system/220-environment-variables.bats, test/system/230-cdi.bats, test/system/501-create.bats, test/system/504-run.bats, test/system/505-enter.bats, test/system/libs/helpers.bash, test/system/setup_suite.bash
The system tests can be very I/O intensive, because many of them copy
OCI images from the test suite's image cache directory to its local
container/storage store, create containers, and then delete everything
to run the next test with a clean slate.  This makes them slow.
The runtime environment tests, which includes the resource limit tests,
are particularly slow because they don't skip the I/O even when testing
error handling.  This makes them a good target for optimizations.
The resource limit tests query the values for different resources from
the same default container without changing its state.  Therefore, a lot
of disk I/O can be avoided by creating the default container only once
for all the tests.
This can save even 30 minutes.
=> test/system: Optimize the resource limits tests

profile.d/toolbox.sh
Add an extra space after the ⬢ so things are less
smooshed together.
=> Add whitespace padding to the PS1 profile

src/pkg/nvidia/nvidia.go
The NVIDIA Management Library API expects nvmlShutdown() to be called once it's no longer in use [1].
Fallout from 8dd2f8e80aad1b76659b44f20c346f75e647d65d
[1] https://docs.nvidia.com/deploy/nvml-api/group__nvmlInitializationAndCleanup.html
=> pkg/nvidia: Clean up NVIDIA Management Library when no longer in use

meson.build
... because they serve no purpose.
=> [WIP] build: Exclude the meson.build files when installing the system tests

test/system/002-help.bats, test/system/501-create.bats, test/system/504-run.bats, test/system/505-enter.bats
The working directory from which `bats(1)` is invoked might not be part of the Toolbx container.  eg., the downstream Fedora CI invokes the tests as:
```
$ cd /path/to/toolbox/test/system
$ bats .
```
... and it led to:
```
not ok 8 help: Try unknown command (forwarded to host)
./libs/bats-assert/src/assert.bash, line 488,
"Error: unknown command \"foo\" for \"toolbox\""' failed
#
No such file or directory: OCI runtime attempted to invoke a
command that was not found
#
```
=> test/system: Unbreak the downstream Fedora CI

src/pkg/utils/utils.go
Fedora 38 reached End of Life on 21st May 2024:
https://bugzilla.redhat.com/show_bug.cgi?id=2316312
=> pkg/utils: Update fallback release to 40 for non-fedora hosts

playbooks/dependencies-centos-9-stream.yaml, playbooks/dependencies-fedora.yaml, test/system/libs/helpers.bash
The bug in pasta(1) that necessitated this workaround has since been fixed in passt 2024_05_10.7288448 [1].  Some host operating systems like CentOS Stream 10 no longer have slirp4netns(1), and it's generally better to test the defaults.
This reverts commit b58f9a51088afbfc22edb0b25776cfa2c4d8cc40.
[1] https://github.com/containers/podman/issues/22575
https://archives.passt.top/passt-dev/20240508090338.2735208-1-sbrivio@redhat.com/
https://archives.passt.top/passt-user/20240510225714.6aa8e6c0@elisabeth/
=> Revert "playbooks, test/system: Work around bug in pasta(1) networks"

images/ubuntu/24.04/Containerfile
Fixes #1566
`/usr/local/sbin/unminimize` has been remove and has been replaced with `unminimize` in apt
https://github.com/docker-library/official-images/pull/17708#issuecomment-2407308768
https://discourse.ubuntu.com/t/oracular-oriole-release-notes/44878#unminimize-33
=> Replace `/usr/local/sbin/unminimize` with `unminimize` in apt

.github/workflows/ubuntu-images.yaml
16.04 and 18.04 are not updated anymore (2 years and over 1 year respectively) so there is no point in rebuilding them all the time. Keep image recipes.
With changes by @tom-reinders from #1567 to not stop the workflow early in case one of the versions fails.
=> Ubuntu workflow: Disable 16.04 and 18.04 builds, do not fail early

src/pkg/nvidia/nvidia.go
If the proprietary NVIDIA driver is installed, particularly `libnvidia-ml.so.1`, but the kernel driver is not being used, then `enter` fails with:
```
Error: failed to initialize NVIDIA Management Library
```
This was tested on Fedora 39 Workstation with the proprietary NVIDIA driver from RPM Fusion, which makes it possible to easily disable the driver without uninstalling it [1].
Note that, with and without this change, there's a delay of a few seconds inside `nvmlInit()` from the NVIDIA Management Library.
[1] https://rpmfusion.org/Howto/NVIDIA
https://github.com/containers/toolbox/issues/1573
=> pkg/nvidia: Unbreak 'enter' if proprietary driver is there but not used

src/cmd/initContainer.go
If the NVIDIA Persistence Daemon is used, then `enter` fails with:
```
$ sudo systemctl start nvidia-persistenced.service
Error: mount: /run/nvidia-persistenced/socket: mount point does not exist.
dmesg(1) may have more information after failed mount system call.
failed to apply mount from Container Device Interface for NVIDIA
```
This is due to the socket at `/run/nvidia-persistenced/socket` being listed in the Container Device Interface specification when the NVIDIA Persistence Daemon is used.
Fallout from 6e848b250b4cde98fb9a40b17421f1f54eacd8f3
https://github.com/containers/toolbox/issues/1572
=> cmd/initContainer: Unbreak 'enter' if NVIDIA Persistence Daemon is used

src/go.mod, src/go.sum
Note that github.com/briandowns/spinner 1.18.1 introduced an undesired dependency on github.com/mattn/go-isatty for the IsTerminal() API, which was later removed in 1.23.1 [1].  Fewer dependencies are always good because it reduces the amount of code in use.
[1] github.com/briandowns/spinner commit 8f269dd04fbfe236
https://github.com/briandowns/spinner/commit/8f269dd04fbfe236
https://github.com/briandowns/spinner/pull/156
=> build: Bump github.com/briandowns/spinner to 1.23.1 (part 1)

src/go.mod, src/go.sum
Note that github.com/briandowns/spinner 1.18.1 introduced an undesired dependency on github.com/mattn/go-isatty for the IsTerminal() API, which was later removed in 1.23.1 [1].  Fewer dependencies are always good because it reduces the amount of code in use.
[1] github.com/briandowns/spinner commit 8f269dd04fbfe236
https://github.com/briandowns/spinner/commit/8f269dd04fbfe236
https://github.com/briandowns/spinner/pull/156
=> build: Bump github.com/briandowns/spinner to 1.23.1 (part 2)

src/cmd/create.go, src/go.mod, src/go.sum
A new API was added to `github.com/briandowns/spinner` 1.23.0 to deprecate
the `io.Writer` output in favour of a pointer to an `os.File` [1].  This new
API enables the spinner to automatically detect whether the output is
connected to a terminal or not, which is convenient.
Commit 944b3ac95fe9c651 already bumped the required
`github.com/briandowns/spinner` version to 1.23.0, so take advantage of
that.
[1] github.com/briandowns/spinner commit 1445186377e2e283
https://github.com/briandowns/spinner/commit/1445186377e2e283
https://github.com/briandowns/spinner/issues/142
=> cmd/create: Replace deprecated github.com/briandowns/spinner API

playbooks/dependencies-centos-9-stream.yaml
Fallout from 6626b11e1565412e411f585657ebe9615ec58cad
=> playbooks/dependencies-centos-9-stream: Show the Bash version

playbooks/dependencies-centos-9-stream.yaml, playbooks/dependencies-fedora-restricted.yaml, playbooks/dependencies-fedora.yaml
The package providing `/usr/share/pkgconfig/bash-completion.pc` changed
from `bash-completion` to `bash-completion-devel` in Fedora 41 onwards [1].
This meant that the Bash completions were no longer being generated and
installed by the CI.
[1] Fedora bash-completion commit d1f5dc48c0440cc6
https://src.fedoraproject.org/rpms/bash-completion/c/d1f5dc48c0440cc6
https://bugzilla.redhat.com/show_bug.cgi?id=1457164
=> playbooks: Restore the generation & installation of the Bash completions

test/system/102-list.bats, test/system/203-network.bats
https://github.com/containers/toolbox/issues/1438
=> test/system: Handle Arch Linux hosts

.zuul.yaml
Fedora 39 reached End of Life on 26th November 2024:\
=> .zuul: Drop testing on Fedora 39

src/go.mod, src/go.sum
=> build: Bump github.com/stretchr/testify to 1.10.0

.github/workflows/ubuntu-tests.yaml, playbooks/dependencies-centos-9-stream.yaml, playbooks/dependencies-fedora-restricted.yaml, playbooks/dependencies-fedora.yaml, src/go.mod, src/go.sum
=> build: Bump github.com/briandowns/spinner to 1.23.2

.github/workflows/ubuntu-tests.yaml, src/go.mod, src/go.sum
=> build: Bump NVIDIA Container Toolkit to 1.17.3

src/pkg/utils/utils.go
The runtime directory is needed a few times during the course of commonly used Toolbx commands.  It's used at start-up for all commands except `completion` and `init-container` to synchronize the invocation of `podman system migrate`.  The entry point (ie., `init-container`) uses it to read the generated Container Device Interface specification and create the initialization stamp file.  The `enter` and `run` commands use it to write the CDI specification and twice to detect the creation of the initialization stamp file.
Since the runtime directory is always the same within a process, there's no need to repeatedly go through all the steps of parsing the user and group IDs, creating the directory, setting its ownership, and logging the name of directory.  Once the directory is successfully …
=> pkg/utils: Optimize getting the runtime directory

src/go.mod, src/go.sum
=> build: Bump github.com/NVIDIA/go-nvlib to 0.7.1

src/go.mod, src/go.sum
... for CVE-2025-23359 or GHSA-4hmh-pm5p-9j7j.
=> build: Bump github.com/NVIDIA/nvidia-container-toolkit to 1.17.4

.github/workflows/ubuntu-tests.yaml, src/cmd/initContainer.go, src/cmd/run.go, src/pkg/utils/utils.go, test/system/250-kerberos.bats, test/system/270-rpm.bats, test/system/meson.build
This will prevent any silly bug in getting the initialization stamp path
from breaking the communication protocol between the `enter` or `run`
commands on the host and the Toolbx container's entry point process.
=> cmd, pkg/utils: Split out the code to get the initialization stamp path

src/cmd/initContainer.go, src/cmd/rootMigrationPath.go, src/cmd/run.go, src/cmd/utils.go, test/system/002-help.bats, test/system/250-kerberos.bats, test/system/270-rpm.bats
When the `fmt.Fprintf()` [1] function is used to write to a
`strings.Builder` [2] instance, it uses the `io.Writer` [3] interface, which
is the `strings.Builder.Write()` method.  This method is practically the
same as the `strings.Builder.WriteString()` method, other than the fact
that the former accepts a slice of bytes and the latter accepts a
string.  So, the difference is the initial call to `fmt.Fprintf()`.
Therefore, unless format verbs [4] are needed to build the string,
`fmt.Fprintf()` can be replaced with `strings.Builder.WriteString()`.  It
reduces one function call and is shorter to type.
Fallout from the following:
* e390f15469959a4b7458fd37069f4a2c8e0b9a4c
* 7542f5fc867b57bf3dc67bbae02cc09ccc0b5df2
* e58992066f6a576b943987789b84a01894ef6193
* …
=> cmd: Simplify string building

test/system/002-help.bats, test/system/206-user.bats
The system tests can be very I/O intensive, because many of them copy
OCI images from the test suite's image cache directory to its local
container/storage store, create containers, and then delete everything
to run the next test with a clean slate.  This makes them slow.
A lot of disk I/O can be avoided by reducing the number of times this
happens.
=> test/system: Optimize the help, group and user tests

src/cmd/initContainer.go, test/system/002-help.bats, test/system/206-user.bats
Use a `strings.Builder` [1] instance instead of raw string literals for
consistency.
Fallout from 772b66bf3e962785730e55f6242fa74066de0743
[1] https://pkg.go.dev/strings#Builder
=> cmd/initContainer: Style fix

.github/workflows/ubuntu-images.yaml, images/arch/extra-packages, images/ubuntu/18.04/extra-packages, images/ubuntu/20.04/extra-packages, images/ubuntu/22.04/extra-packages, images/ubuntu/24.04/extra-packages, images/ubuntu/24.10/extra-packages, src/cmd/initContainer.go, test/system/002-help.bats, test/system/206-user.bats
A subsequent commit will use this to give Toolbx containers access to
the certificates from certificate authorities on the host.  This commit
was kept separate from the changes to `toolbox(1)` to ensure that the
`arch-toolbox` and `ubuntu-toolbox` images are ready before that
happens.
https://github.com/containers/toolbox/issues/626
=> images/arch, images/ubuntu: Add p11-kit-client.so

.github/workflows/ubuntu-images.yaml, images/arch/extra-packages, images/ubuntu/18.04/extra-packages, images/ubuntu/20.04/extra-packages, images/ubuntu/22.04/extra-packages, images/ubuntu/24.04/extra-packages, images/ubuntu/24.10/extra-packages, src/cmd/initContainer.go, test/system/002-help.bats, test/system/203-network.bats, test/system/206-user.bats
The system tests can be very I/O intensive, because many of them copy
OCI images from the test suite's image cache directory to its local
container/storage store, create containers, and then delete everything
to run the next test with a clean slate.  This makes them slow.
The runtime environment tests, which includes the networking tests, are
particularly slow because they don't skip the I/O even when testing
error handling.  This makes them a good target for optimizations.
The networking tests check the behaviour and configuration of the
network in different containers without changing their state.
Therefore, a lot of disk I/O can be avoided by creating these containers
only once for all the tests.
This can reduce the time needed to run the networking tests from almost
15 minutes to …
=> test/system: Optimize the networking tests

.github/CODEOWNERS, src/meson.build, src/pkg/utils/arch.go, src/pkg/utils/fedora.go, src/pkg/utils/rhel.go, src/pkg/utils/ubuntu.go, src/pkg/utils/utils.go
This will reduce the size of the `src/pkg/utils/utils.go` file and make it easier to specify which part of the code base is maintained by whom.
=> Move the distro-specific support code into their own separate files

test/system/211-dbus.bats
The system tests can be very I/O intensive, because many of them copy OCI images from the test suite's image cache directory to its local container/storage store, create containers, and then delete everything to run the next test with a clean slate.  This makes them slow.
The runtime environment tests, which includes the D-Bus tests, are particularly slow because they don't skip the I/O even when testing error handling.  This makes them a good target for optimizations.
The D-Bus tests check if methods can be called across the user or session and system D-Bus instances from different containers without changing their state.  Therefore, a lot of disk I/O can be avoided by reating these containers only once for all the tests.
This can reduce the time needed to run the D-Bus tests from almost …
=> test/system: Optimize the D-Bus tests

src/pkg/utils/utils.go
It's been a while since it's been necessary to read the `ID` field from `os-release(5)` outside this package or the `VARIANT_ID` field anywhere at all.  Therefore, it's time to adjust the code to reflect this reality.
Fallout from 8caa7cd828c31e558b796846380e58cb9354b3a0
=> pkg/utils: Mark a private function as such and drop one that's unused

images/arch/Containerfile, images/ubuntu/18.04/Containerfile, images/ubuntu/20.04/Containerfile, images/ubuntu/22.04/Containerfile, images/ubuntu/24.04/Containerfile, images/ubuntu/24.10/Containerfile
It's better to ensure that the `/etc/pkcs11/modules` directory exists in the image, instead of having the Toolbx container's entry point create it at runtime, because it can be a confirmation that p11-kit was built to read the module configuration from this location.
https://github.com/containers/toolbox/issues/626
=> images: Create the directory for configuring PKCS#11 modules

test/system/libs/helpers.bash, test/system/setup_suite.bash
The `XDG_CACHE_HOME` environment variable is supposed to default to `$HOME/.cache` [1], just as it did in the test suite, and this location is meant to be used as a cache for 'normal' use by the user.  Test suites generally don't qualify as 'normal' use.
One expects that deleting the cache shouldn't affect 'normal' use other than degrading performance.  However, deleting these temporary files used by the test suite will cause actual breakage.  Even if the user doesn't manually delete the cache, two concurrent invocations of the test suite can do so or lead to other unexpected collisions, because the paths are constant across multiple invocations.
Therefore, it's better to limit the scope of the test suite's temporary files within the sandbox offered by Bats [2].  The sandbox is clearly …
=> test/system: Don't use XDG_CACHE_HOME or HOME for temporary files

test/system/220-environment-variables.bats
The system tests can be very I/O intensive, because many of them copy
OCI images from the test suite's image cache directory to its local
container/storage store, create containers, and then delete everything
to run the next test with a clean slate.  This makes them slow.
The runtime environment tests, which includes the environment variable
tests, are particularly slow because they don't skip the I/O even when
testing error handling.  This makes them a good target for
optimizations.
The environment variable tests query the values of different environment
variables from different containers without changing their state.
Therefore, a lot of disk I/O can be avoided by creating these containers
only once for all the tests.
=> test/system: Optimize the environment variable tests

src/pkg/utils/utils.go
Fedora 40 reached End of Life on 13th May 2025:
=> pkg/utils: Update fallback release to 42 for non-fedora hosts

src/go.mod, src/go.sum
=> build: Bump github.com/fsnotify/fsnotify to 1.8.0

src/cmd/create.go, src/cmd/run.go, src/cmd/utils.go
The POSIX shell implementation used to read and respect the `HOME` environment variable.  It broke when the Go implementation started using `user.Current()` [1], because it uses `getpwuid_r(3)`, which only uses the GNU Name Service Switch's (or NSS') password database and ignores HOME.
This created a strange situation where the `toolbox(1)` binary ignored the `HOME` environment variable, while the `profile.d/toolbox.sh` shell start-up snippet and Podman read and respected it.
Restoring the `HOME` environment variable will enable users to create Toolbx containers with different home directories from the host for increased isolation, and to isolate the host's `HOME` from the system tests.
Fallout from e8d7f25e831725d0bafbbd3171b9a5262d2d1113
[1] https://pkg.go.dev/os/user#Current …
=> cmd/create, cmd/run, cmd/utils: Unbreak overriding the HOME variable

.github/workflows/ubuntu-tests.yaml
Fallout from eb736926183b1c20c1efdc018874f0d9bc30cc7d
=> .github/workflows: Bump Go to 1.22 for CI on Ubuntu 22.04

.github/workflows/ubuntu-tests.yaml, test/system/210-ulimit.bats
ulimit is a shell builtin, so the shell it is run from changes the version that is used. Ubuntu (and Debian) use dash as their system shell, instead of bash. The means that toolbox run also used dash with Ubuntu containers, caused an unexpected version of ulimit to be used in tests. Tests were updated to force the use of bash and its version of ulimit.
=> .github/workflows, test/system: Enable 210-ulimit.bats on Ubuntu 22.04

src/cmd/initContainer.go
The `os.IsNotExist()` function [1] predates the introduction of the `errors.Is()` function [2] in Go 1.13 [3].  From Go >= 1.16, the documentation explicitly recommends the use of `errors.Is()` instead of `os.IsNotExist()` [4].
The Go implementation of Toolbx never used any Go older than 1.13 [5], and currently it requires Go >= 1.22 [6].  So, there's no reason not to use the more modern and recommended alternative.
[1] https://pkg.go.dev/os#IsNotExist
[2] https://pkg.go.dev/errors#Is
[3] https://go.dev/blog/go1.13-errors
[4] Go commit b641f0dcf48aa748
https://github.com/golang/go/commit/b641f0dcf48aa748
https://github.com/golang/go/issues/41122
[5] Commit d857471aa2f233e5
https://github.com/containers/toolbox/commit/d857471aa2f233e5
https://github.com/containers/toolbox/pull/318
[6] …
=> cmd/initContainer: Use errors.Is() instead of os.IsNotExist()

src/cmd/initContainer.go
An error like this shouldn't happen unless Podman did something
unexpected or was used wrong or something else happened that inserted an
unexpected mount point in the container to surprise the entry point.
eg., removing the `--no-hosts` option from `podman create` will trigger
this.
This change replaces the more generic error message:
```ShellSession
Error: failed to redirect /etc/hosts to /run/host/etc/hosts: remove
/etc/hosts: device or resource busy
```
... to something more precise:
```ShellSession
Error: failed to redirect /etc/hosts to /run/host/etc/hosts:
/etc/hosts is a mount point
```
=> cmd/initContainer: Detect mount points when creating symbolic links

toolbox
Detected by https://www.shellcheck.net/:
```
Line 1255:
if ! localtime_target=$(readlink /etc/localtime >/dev/null 2>&3) \
^-- SC2327 (warning): This command substitution
will be empty because the command's output
gets redirected away.
^-- SC2328 (error):
This redirection
takes output away
from the command
substitution.
```
See:
https://www.shellcheck.net/wiki/SC2327
https://www.shellcheck.net/wiki/SC2328
Fallout from 8db414ddc2d73719c628ca56f345556281e33ebf
=> Fix resolving /etc/localtime

src/cmd/run.go, test/system/104-run.bats, test/system/libs/helpers.bash
Added deprecation message when running a container that was created with Toolbx 0.0.96 and older, as described in #1684
=> Deprecation message when using 0.0.96 and older Toolbx container + tests

README.md
Closes #1399.
See also containers/containertoolbx.org#1.
=> Add a note to the README about the name change

test/system/203-network.bats
The existing code would never properly select the IPv4 address instead a fallback value was selected when the IPv4 option was used, the script is updated to that both IPv4 and IPv6 will be properly selected.
=> test/system: Fix issue with python resolver IP type
