fedora-toolbox

Fallout from cc0caef627249009a1cdbbf6216c1f7ba64a4b99
https://github.com/debarshiray/fedora-toolbox/issues/19

Unbreak creating the toolbox if the toolbox image already exists

---

fedora-toolbox

https://github.com/debarshiray/fedora-toolbox/issues/15

Give access to the FUSE kernel module

---

toolbox

See: https://wiki.ubuntu.com/DashAsBinSh
Detected by the checkbashisms [1] tool.
[1] https://packages.debian.org/sid/devscripts
https://github.com/debarshiray/toolbox/issues/53

POSIX only supports single digit file descriptors

---

toolbox

https://github.com/debarshiray/toolbox/issues/59

Clarify the error message if the toolbox container is not found

---

toolbox

Detected by the checkbashisms [1] tool.
[1] https://packages.debian.org/sid/devscripts
https://github.com/debarshiray/toolbox/issues/53

Avoid a Bash-ism (ie. UID) and stick to POSIX (ie. id -ru)

---

toolbox

Detected by the checkbashisms [1] tool.
[1] https://packages.debian.org/sid/devscripts
https://github.com/debarshiray/toolbox/issues/53

Avoid a Bash-ism (ie. $'...') and stick to POSIX (ie. $(printf '...'))

---

data/meson.build
data/tmpfiles.d/meson.build
data/tmpfiles.d/toolbox.conf
meson.build
toolbox

Based on 4a2a15f2eb3a6b810fcf9b699272fcc9a7871c6e and as suggested by
Daniel J Walsh.
https://github.com/debarshiray/toolbox/issues/3

Give access to removable devices and other temporary mounts

---

toolbox

See the individual commits for further details.

Include images tagged with c.gh.debarshiray.toolbox in 'toolbox list' and the tag to containers and images produced by 'toolbox create'

---

toolbox

This should smoothen the onboarding experience by making the commands
self-documenting.
https://github.com/debarshiray/toolbox/issues/59

Mention the name of the created toolbox container and how to enter it

---

toolbox

Instead of overwhelming the user with the entire reference
documentation, highlight some of the more common commands that a new
user is likely to be interested in. This is concise enough to not annoy
seasoned users who might have just committed a typo.
This should smoothen the onboarding experience by making the commands
self-documenting.
https://github.com/debarshiray/toolbox/issues/59

Suggest a way forward if no command has been specified

---

toolbox

https://github.com/debarshiray/toolbox/issues/104

Allow connecting to Wayland displays other than "wayland-0"

---

toolbox

This should smoothen the onboarding experience by making the commands
self-documenting.
https://github.com/debarshiray/toolbox/issues/59

Suggest a way forward if the requested container is already present

---

toolbox

https://github.com/debarshiray/toolbox/issues/131

Set default release to 29 when running on non-fedora hosts

---

toolbox

Fallout from b718fbdcda74b0f98ec5035e9a41809132f2da05
https://github.com/debarshiray/toolbox/issues/134

Don't prompt for localhost and cached base images

---

toolbox

See: https://github.com/koalaman/shellcheck/wiki/SC2086

Quote a few variables to avoid triggering SC2086 in future

---

doc/toolbox-enter.1.md

https://github.com/debarshiray/toolbox/issues/128

doc/toolbox-enter: Mention the 'initial setup' and fallback behaviour

---

toolbox

https://github.com/debarshiray/toolbox/issues/174

Check if /etc/subgid and /etc/subuid have entries for the user

---

profile.d/toolbox.sh

I'm still waging a fight against this.  Please stop saying "immutable"
for this, it's more misleading than useful.
Previously e.g. https://github.com/debarshiray/toolbox/pull/43

Drop the "immutable" term

---

toolbox

https://github.com/debarshiray/toolbox/issues/213

Use host ulimits when creating containers

---

src/cmd/list.go
src/cmd/rm.go
src/cmd/rmi.go

Podman is nearing a new major version (V2). We need to preserve compatibility.

Podman V2 compatibility fixes

---

README.md

Based on work done by Natanael in https://github.com/containers/toolbox/pull/259

README.md: List out dependencies and installation instructions

---

src/cmd/root.go

This shouldn't cause any user visible change.

Some minor changes to the migration code

---

README.md

Based on this list of langauges:
https://github.com/github/linguist/blob/master/lib/linguist/languages.yml

README.md: Enable syntax highlighting in code blocks

---

src/cmd/list.go
src/go.mod

https://github.com/containers/toolbox/issues/596

cmd/list: Color the output only when displaying on a terminal

---

src/cmd/create.go
src/cmd/initContainer.go
src/cmd/root.go
src/cmd/run.go
src/pkg/utils/utils.go

https://github.com/containers/toolbox/issues/267

Don't rely on XDG_RUNTIME_DIR when running as root

---

src/cmd/initContainer.go

It's not mandatory to have a /etc/localtime. If it's absent then it
means that the UTC timezone is being used. One such example of an
operating system is Fedora CoreOS.
Fallout from b9a0bd5f0c2a2421ec15eea286ca20f03b7152d2

cmd/initContainer: Unbreak 'enter' on hosts without a /etc/localtime

---

GOALS.md
README.md

... to prevent the README.md file from becoming too long.

GOALS.md, README.md: Move the Goals and Use Cases to a separate file

---

playbooks/fedora-34/setup-env.yaml

I made a mistake in previous commit and did not update the pulled image
name.

ci: Fix pulled image name

---

playbooks/setup-env.yaml
playbooks/system-test.yaml

* Specify the precise versions of bats-assert & bats-support
* Specify the artifact generated at each step of the build

Miscellaneous improvements to the Ansible playbooks

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md

Recently the issue labels were updated. The templates need to be updated
to auto-set labels correctly.

.github: Update issue templates

---

src/cmd/create.go

Showing spinner after a lot of work on creating a toolbox is done (even
though not really time consuming) does not make much sense.
When a spinner is started successfully, a stop command is deferred.
There's no need to stop it additionally.

cmd/create: Start spinner earlier

---

src/go.mod
src/go.sum
src/pkg/shell/shell_test.go

Hi @HarryMichal!
I've created the first unit test using on cmd/pkg/shell. I've chosen only this package in order to get you opinion on the mechanism that I've proposed.
As we discussed on #473, I used [testify](https://github.com/stretchr/testify) library in order to get more easy and cleaner test cases.
Please, let know what you think and anything kind of suggestion will be very appreciate!

[unit test] Add cmd/pkg/shell

---

src/cmd/rm.go
src/cmd/rmi.go

Instead of using own ways of getting all toolbox images/containers (and
thus unnecessary duplication of code) use a dedicated function.

cmd/rm,rmi: Use function for getting list of images/containers

---

completion/bash/toolbox

Our bash completion is very lacking and hard to use. This is an attempt to make it a bit more usable. See descriptions of commit messages for detailed info of what this changes.
Took some ideas from my old work in https://github.com/containers/toolbox/pull/304.
This fixes https://github.com/containers/toolbox/issues/296 but does not close it because we'll reuse the ticket for further discussion about completion.

Update bash completion

---

src/cmd/list.go

Fallout from https://github.com/containers/toolbox/pull/776
https://github.com/containers/toolbox/pull/782

list: Fix typo

---

src/cmd/root.go
test/system/002-help.bats

This reverts commit 6bbbedf675a2fcfc03e720a252d501e1507561a4.

cmd/root: Unbreak handling of unknown flags

---

completion/bash/toolbox

Follow up to 7fafcd271e519df4e8e2f073bfe84921dcb685d7

completion/bash: Completely drop flag --very-verbose

---

README.md
images/fedora/f28/Containerfile
images/fedora/f29/Containerfile
images/fedora/f30/Containerfile
images/fedora/f31/Containerfile
images/fedora/f32/Containerfile
images/fedora/f32/README.md
images/fedora/f33/Containerfile
images/fedora/f33/README.md
images/fedora/f34/Containerfile
images/fedora/f34/README.md
images/fedora/f35/Containerfile
images/fedora/f35/README.md

Removed the deprecated label in all the toolbox image definitions

Images: Removed deprecated com.github.debarshiray.toolbox tag

---

src/pkg/utils/utils_test.go

https://github.com/containers/toolbox/pull/841

pkg/utils: Test ParseRelease

---

.gitignore
.gitmodules
meson.build
playbooks/setup-env.yaml
test/system/README.md

This will make it easier to work with system tests.

test/system: Track bats libs as submodules & install them better

---

test/system/101-create.bats

Follow-up to https://github.com/containers/toolbox/pull/852

test/system: Test pull failure

---

src/cmd/enter.go
src/cmd/run.go

Double negation is hard to wrap your head around.

cmd/enter: Don't use double negation

---

src/cmd/utils.go
test/system/002-help.bats

Minor fix-ups to https://github.com/containers/toolbox/pull/837

Style fixes

---

README.md

Fallout from 819bb46aaa65034536f1fdec5785975dc4d55ef9
https://github.com/containers/toolbox/issues/929

README.md: Require mount(8) in images

---

README.md
images/fedora/f34/Containerfile
images/fedora/f35/Containerfile
images/fedora/f36/Containerfile

https://github.com/containers/toolbox/issues/885

images, README.md: Remove misleading and redundant CMD and update the requirements around ENTRYPOINT

---

src/cmd/root.go

... and not just the username.
https://github.com/containers/toolbox/issues/954

cmd/root: Search subordinate ID files for also the UID

---

.github/workflows/linting.yaml

Use machines to do (at least some) of the work humans had to do!

ci: Add golangci linter

---

src/cmd/create.go
src/cmd/initContainer.go
src/cmd/run.go

Issues included:
- unreachable code
- unneeded type assertions
- unhandled errors
- use of deprecated API
- unused code
https://github.com/containers/toolbox/pull/979

cmd: Fix issues raised by Golangci

---

.zuul.yaml
meson_post_install.py

Fallout from be2ba6d2e203e2d5f42f122df9aea7e16f58e99f

build: Add copyright and license notice

---

doc/toolbox-create.1.md
doc/toolbox-enter.1.md
doc/toolbox-run.1.md
doc/toolbox.1.md

Split from https://github.com/containers/toolbox/pull/977

doc: Add section about supported distribution images, and other clarifications

---

.zuul.yaml
test/system/103-container.bats
test/system/999-teardown.bats
test/system/README.md
test/system/libs/helpers.bash

While working on #935 I ended up making a series of changes to the system tests. Split them out here to lower the footprint of that one PR.

test/system: Maintenance & small updates

---

src/pkg/utils/utils.go

It turns out that Viper's custom error implementations use non-pointer
receivers, whereas often people assume pointer receivers.  This can
cause confusion when trying to use errors.As(...) with those errors [1].
Secondly, Viper may or may not throw ConfigFileNotFoundError depending
on its build tags.
[1] https://github.com/spf13/viper/issues/1139

pkg/utils: Address the confusion around handling errors from Viper

---

test/system/libs/helpers.bash

In 54a2ca1 image caching has been done by first pulling using Podman and
then moving the image from the local container store to a directory. The
pull to the local container store can be skipped and instead we can use
Skopeo to directly save the pulled image into a directory.
On my machine this reduced the time of the system test setup "test" by
about 50 seconds. This speed-up largely depends on the available network
connection, though.

test/system: Drop extra pull when caching images

---

images/fedora/f37/extra-packages
images/fedora/f38/extra-packages

This new packet allows the user to set a locale inside the toolbox and make locale dependent commands work
https://github.com/containers/toolbox/issues/60
Signed-off-by: Nieves Montero <nmontero@redhat.com>

Add package glibc-all-langpacks to f37 and f38

---

completion/meson.build
meson.build

Split from https://github.com/containers/toolbox/pull/1123

build: Some clean-ups for the shell completions

---

doc/toolbox-run.1.md
src/cmd/enter.go
src/cmd/rootMigrationPath.go
src/cmd/run.go
test/system/104-run.bats

This mirrors the `--preserve-fds` argument of podman.
Fixes #1066
Welcome to "I've never written anything in Go before" hour :)

cmd/run: add `--preserve-fds` command-line argument

---

CONTRIBUTING.md
doc/toolbox-rm.1.md
doc/toolbox-rmi.1.md
src/cmd/completion.go
src/cmd/initContainer.go
test/system/001-version.bats
test/system/105-enter.bats
test/system/108-completion.bats
test/system/libs/helpers.bash

Split from https://github.com/containers/toolbox/pull/1149

Fix spelling mistakes using codespell

---

src/cmd/initContainer.go
src/cmd/run.go

... in https://github.com/containers/toolbox/pull/979

cmd/initContainer, cmd/run: Some fix-ups for the golangci-lint clean-ups

---

src/cmd/list.go

Fallout from 2369da5d31830e5cd3e1a13857a686365875ae61

cmd/list: Simplify code

---

src/cmd/list.go
src/pkg/podman/podman.go
test/system/000-setup.bats
test/system/101-create.bats
test/system/102-list.bats
test/system/103-container.bats
test/system/README.md
test/system/libs/helpers.bash

This builds on top of commit e7722078310a79b0.

cmd/list, pkg/podman: Don't unmarshal the 'podman images' JSON twice and limit access to it

---

doc/toolbox.conf.5.md
playbooks/dependencies.yaml
src/cmd/initContainer.go

This is necessary for https://github.com/containers/toolbox/pull/1171

Various fixes and tweaks towards testing on CentOS Stream 9 (part 1)

---

.codespellexcludefile
profile.d/toolbox.sh
test/system/101-create.bats
test/system/libs/helpers.bash
toolbox

This is necessary for https://github.com/containers/toolbox/pull/1171

Various fixes and tweaks towards testing on CentOS Stream 9 (part 2)

---

src/cmd/root.go

This is necessary for https://github.com/containers/toolbox/pull/1180

Some miscellaneous improvements to the subordinate checks

---

src/meson_go_fmt.py

Fallout from afbed7a057565b085463b8134d79b564e437c9e7

build: Fix indentation

---

.zuul.yaml
test/system/101-create.bats
test/system/107-rmi.bats

... and a few other improvements to the system tests.

.zuul: Enable testing on Fedora 38

---

profile.d/toolbox.sh

Since Sericea is an official variant of Fedora, it should have an official welcome message like another ones.

profile.d/toolbox.sh: Add welcome message for Fedora Sericea

---

SECURITY.md

https://github.com/containers/common/issues/549

SECURITY.md: Update URL

---

CODE-OF-CONDUCT.md

Message "Branch master was renamed to main." when opening the link.

CODE-OF-CONDUCT.md hyperlink update

---

test/system/211-dbus.bats
test/system/meson.build

Fixes https://github.com/containers/toolbox/issues/1330

Test that D-Bus works

---

test/system/001-version.bats
test/system/002-help.bats
test/system/101-create.bats
test/system/102-list.bats
test/system/103-container.bats
test/system/104-run.bats
test/system/106-rm.bats
test/system/107-rmi.bats
test/system/108-completion.bats
test/system/libs/helpers.bash

```
Line 28:
run --separate-stderr $TOOLBOX --version
^------^ SC2086 (info): Double quote to prevent
globbing and word splitting.
```
See: https://www.shellcheck.net/wiki/SC2086

test/system: Silence SC2086

---

.github/workflows/ubuntu-images.yaml

* Add ppc64le into the build matrix

Build ubuntu-toolbx:ppc64le images

---

src/meson.build

Fallout from:
* f8e21a31b317a65f57773c280926aa471ae060ff
* 3cc6ece1f2572cb07e94ff518332a982cf733469
* b27b41eff84ff8426656c151264d28cc878c27eb

build: Add the *_test.go files for unit tests to src/meson.build

---

src/cmd/initContainer.go

Currently, inotify(7) is used to keep /etc/timezone inside the Toolbx container synchronized with the host operating system's /etc/localtime. However, /etc/timezone is only there for compatibility with Java.  The vast majority of non-ancient code bases use /etc/localtime, which does not need inotify(7) to stay synchronized.
Therefore, it's not worth preventing the container from starting when the operating system is suffering from a shortage of resources needed for inotify(7).  Especially because this shortage can be caused by a bug in another program that's consuming too many inotify(7) instances and watches.
https://github.com/containers/toolbox/issues/1329

cmd/initContainer: Defend against insufficient resources for inotify(7)

---

.github/CODEOWNERS

.github/CODEOWNERS: Clarify ownership of the CI on Ubuntu

---

.github/workflows/ubuntu-tests.yaml

This should have been part of commit 571dc9780bdf9a9e.

playbooks/system-test: Avoid running out of storage space (part 2)

---

README.md

https://github.com/containers/toolbox/issues/1451

README.md: Add a badge for the Ubuntu package, logos and update hyperlinks for Fedora CoreOS and Silverblue

---

src/cmd/list.go
src/pkg/podman/podman.go
src/pkg/utils/utils.go

This builds on top of commit e7722078310a79b0.

cmd/list, pkg/podman: Don't unmarshal the 'podman ps' JSON twice and limit access to it

---

src/cmd/initContainer.go
src/cmd/utils.go

Fallout from e1635c06f3d2038097c875b7b1c293c7bc40bb1b

cmd/initContainer: Simplify creating a daily ticker

---

src/go.mod
src/go.sum

build: Bump golang.org/x/sys to 0.19.0

---

src/go.mod
src/go.sum

build: Bump github.com/fsnotify/fsnotify to 1.7.0

---

README.md

... from https://star-history.com/.

README.md: Add GitHub star history chart

---

test/system/501-create.bats

https://github.com/containers/toolbox/issues/957

test/system: Test attempts to create the same container twice

---

src/go.mod
src/go.sum
test/system/501-create.bats

The src/go.sum file was updated with `go mod tidy`.

build: Bump golang.org/x/sys to 0.22.0

---

src/go.mod
src/go.sum

build: Bump golang.org/x/sys to 0.23.0

---

src/go.mod
src/go.sum

build: Bump golang.org/x/sys to 0.26.0

---

src/cmd/initContainer.go
src/cmd/run.go

cmd/initContainer: Style fixes

---

src/pkg/utils/utils.go

Fallout from d323143c468e5e59dba4d209a4e4767d88dfc19e

pkg/utils: Remove unused GetMountPoint() and GetMountOptions()

---

src/cmd/initContainer.go

When a Toolbx container is set up to use the `p11-kit-client.so` PKCS #&NoBreak;11
module instead of the usual `p11-kit-trust.so` module, the
`P11_KIT_SERVER_ADDRESS` environment variable must be set inside the
container, so that it can communicate with the host operating system.
Currently, this works as described above with the `enter` and `run`
commands, but not within child sessions started by an `sshd(8)` [1]
instance running inside a container, because `P11_KIT_SERVER_ADDRESS` is
absent.
To make this work, `sshd(8)` [1] must be configured [2] to set
`P11_KIT_SERVER_ADDRESS` in its child sessions.
If `sshd(8)` uses the `/etc/ssh/sshd_config.d` directory for configuration,
then the entry point will automatically do this from now on.  This
requires at least OpenSSH 8.2, which added …

cmd/initContainer: Unbreak access to CA certificates in sshd(8) sessions

---

NEWS
test/system/001-version.bats
test/system/101-create.bats
test/system/104-run.bats
test/system/105-enter.bats
test/system/106-rm.bats
test/system/108-completion.bats

Fallout from fbffd45384932551071c980a30825166fe87bb63 and 40e3c5a63f3c37547ef906fd724e1cf4550c8b85

NEWS: Add missing entry about the PODMAN & SKOPEO environment variables
